if exists (select 1 from CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_REFINANCIAMIENTOS')
BEGIN
  DELETE CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_REFINANCIAMIENTOS'
END
INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") 
VALUES('JOB_CASE_CENTER_REF','CC_REFINANCIAMIENTOS',NULL,0);
COMMIT;
