DROP TABLE IF EXISTS "STG_SAT"."PTOPERAC";
DROP TABLE IF EXISTS "STG"."PTOPERAC";

drop table IF EXISTS STG_SAT.PTOPERAC;  CREATE TABLE IF NOT EXISTS STG_SAT.PTOPERAC  ( 	OP_FECHA_CORTE	DATE		--FECHA DE CORTE DE LA INFORMACIÓN 
--LISTADO DE OPERACIONES	 	 		
,	OP_FILIAL	DECIMAL	(1,0)	--IDENTIFICACION DE LA FILIAL 
,	OP_PRODUCTO	DECIMAL	(2,0)	--CÓDIGO DEL PRODUCTO 
,	OP_OPERACION	DECIMAL	(10,0)	--CODIGO OPERACIÓN 
,	OP_NUM_OP_IFI	VARCHAR	(20)	--NUMERO DE REFERENCIA 
,	OP_OFICIAL	VARCHAR	(10)	--CÓDIGO DEL FUNCIONARIO  
,	OP_CLIENTE	VARCHAR	(24)	--CÓDIGO DEL CLIENTE / NÚMERO ÚNICO DEL BANCO. 
,	OP_CIUDAD	DECIMAL	(4,0)	--CÓDIGO CIUDAD 
,	OP_OFICINA	DECIMAL	(5,0)	--CÓDIGO OFICINA 
,	OP_MONEDA	DECIMAL	(1,0)	--CÓDIGO MONEDA 
,	OP_SECTOR_CONTABLE	VARCHAR	(2)	--SECTOR ECONÓMICO CONTABLE 
,	OP_SECTOR_REAL	VARCHAR	(2)	--CODIGO SECTOR REAL 
,	OP_DESTINO	VARCHAR	(10)	--DESTINO ECONÓMICO 
,	OP_TIPO_OPER	VARCHAR	(2)	--TIPO OPERACIÓN 
,	OP_CATEG_CONT	VARCHAR	(1)	--CATEGORÍA CONTABLE 
,	OP_CATEGORIA_OPER	VARCHAR	(2)	--CÓDIGO TIPO DE ACTIVO 
,	OP_CLASE_GTIA	VARCHAR	(2)	--CÓDIGO DE GARANTIA 
,	OP_TIPO_CARTERA	VARCHAR	(2)	--CÓDIGO TIPO CARTERA 
,	OP_TIPO_TRAMITE	VARCHAR	(1)	--CÓDIGO TIPO DE TRÁMITE 
,	OP_FECHA_INI	DATE		--FECHA DE OTORGAMIENTO 
,	OP_FECHA_FIN	DATE		--FECHA DE VENCIMIENTO 
,	OP_FECHA_FIN_LEGAL	DATE		--FECHA DE VENCIMIENTO LEGAL
,	OP_FECHA_CAS	DATE		--FECHA CASTIGO (SANEAMIENTO)
,	OP_FECHA_PAG	DATE		--FECHA DE ÚLTIMO PAGO 
,	OP_FECHA_CAN	DATE		--FECHA DE CANCELACIÓN 
,	OP_PLAZO	DECIMAL	(4,0)	--PLAZO DE LA OPERACIÓN 
,	OP_TOTAL_CUOTAS	DECIMAL	(3,0)	--NÚMERO TOTAL DE CUOTAS 
,	OP_TIPO_AMORTIZ	VARCHAR	(10)	--CÓDIGO TIPO DE AMORTIZACIÓN 
,	OP_GRACIA_CAP	DECIMAL	(2,0)	--DIAS DE GRACIA CAPITAL 
,	OP_GRACIA_INT	DECIMAL	(2,0)	--DIAS DE GRACIA INTERESES 
,	OP_PERIODO_CAP	DECIMAL	(2,0)	--PERIODO DE CAPITAL 
,	OP_PERIODO_INT	DECIMAL	(2,0)	--PERIODO DE INTERESES 
,	OP_MOROSIDAD_CAP	DECIMAL	(5,0)	--DIAS MORA CAPITAL 
,	OP_MOROSIDAD_INT	DECIMAL	(5,0)	--DIAS MORA INTERESES 
,	OP_TASA_ORIGINAL	DECIMAL	(6,4)	--TASA INTERES INICIAL 
,	OP_TASA_ACTUAL	DECIMAL	(6,4)	--TASA INTERES ACTUAL 
,	OP_TASA_REF	DECIMAL	(6,4)	--TASA INTERES REFERENCIA 
,	OP_TASA_EFECTIVA	DECIMAL	(6,4)	--TASA INTERES EFECTIVA 
,	OP_FORMA_REAJUSTE	VARCHAR	(1)	--FORMA DE REAJUSTE 
,	OP_ORIGEN_FONDOS	VARCHAR	(5)	--CÓDIGO ORIGEN DE FONDOS 
,	OP_VALOR_ORIGINAL	DECIMAL	(19,4)	--MONTO OTORGADO O LIMITE DE LA TARJETA 
,	OP_SALDO_CAPITAL	DECIMAL	(19,4)	--SALDO TOTAL CAPITAL 
,	OP_DESEMBOLSOS	DECIMAL	(19,4)	--DESEMBOLSOS PENDIENTES 
,	OP_CAPITAL_VCDO	DECIMAL	(19,4)	--CAPITAL VENCIDO 
,	OP_CAPITAL_MORA	DECIMAL	(19,4)	--CAPITAL MORA 
,	OP_SALDO_INTERES	DECIMAL	(19,4)	--SALDO TOTAL INTERESES 
,	OP_INTERES_VCDO	DECIMAL	(19,4)	--INTESESES VENCIDOS 
,	OP_INTERES_MORA	DECIMAL	(19,4)	--INTERESES EN MORA 
,	OP_RIESGO	DECIMAL	(19,4)	--SALDO DEL RIESGO ADEUDADO 
,	OP_ABONO_PEND	DECIMAL	(19,4)	--ABONOS PENDIENTES 
,	OP_VAL_ACTUAL_GTIA	DECIMAL	(19,4)	--VALOR ACTUAL DE LA GARANTIA 
,	OP_VAL_REAL_GTIA	DECIMAL	(19,4)	--VALOR REAL DE LA GARANTIA 
,	OP_COB_ACTUAL_GTIA	DECIMAL	(19,4)	--COBERTURA CON VALOR ACTUAL DE LA GARANTÍA 
,	OP_COB_REAL_GTIA	DECIMAL	(19,4)	--ES LA COBERTURA REAL O DE MERCADO CNSOLIDADA. 
,	OP_GARANTIA_INSCRITA	VARCHAR	(1)	--IDENTIFICAR DE GARANTIA INSCRITA 
,	OP_GARANTE_CART_PIG	VARCHAR	(2)	--IDENTIFICAR DE GARANTE 
,	OP_TIPO_CERTIFICADO	VARCHAR	(2)	--IDENTIFICADOR DE TIPO CERTIFICADO 
,	OP_FACTOR_MLO	DECIMAL	(8,4)	--FACTOR DE CAMBIO MONEDA 
,	OP_ESTADO_OPER	VARCHAR	(10)	--ESTADO REAL DE LA OPERACIÓN 
,	OP_USUARIO_MODIF	VARCHAR	(14)	--ID USUARIO QUE MODIFICA DATOS 
,	OP_FECHA_MODIF	DATE		--FECHA DE MODIFICACION 
,	OP_MORA	DECIMAL	(19,4)	--SALDO INTERES MORA 
,	OP_TASA_MORA	DECIMAL	(6,4)	--TASA INTERES MORA 
,	OP_CUOTAS_MORA	DECIMAL	(2,0)	--CUOTAS EN MORA 
,	OP_CALIFICACION	VARCHAR	(10)	--CATEGORIA DE RIESGO 
,	OP_RANGO_PLAZO	DECIMAL	(2,0)	--RANGO DEL PLAZO 
,	OP_RANGO_MORA_CAP	DECIMAL	(2,0)	--RANGO DE DIAS MORA CAPITAL 
,	OP_RANGO_MORA_INT	DECIMAL	(2,0)	--RANGO DE DIAS MORA INTERESES 
,	OP_RESERVA_REQUERIDA	DECIMAL	(19,4)	--RESERVA DE SANEAMIENTO REQUERIDA 
,	OP_RESERVA_CONSTITUIDA	DECIMAL	(19,4)	--RESERVA DE SANEAMIENTO CONSTITUIDA 
,	OP_DEDUCCIONES	DECIMAL	(19,4)	--DEDUCCIONES 
,	OP_COBERTURA_GTIA	DECIMAL	(19,4)	--COBERTURA DE LA GARANTIA 
,	OP_ETAPA_COBRO	VARCHAR	(10)	--ETAPA DE COBRO 
,	OP_CALIF_ANT	VARCHAR	(10)	--CATEGORIA DE RIESGO DEL MES PASADO 
,	OP_RES_REQUE_ANT	DECIMAL	(19,4)	--RESERVAS DE SANEAMIENTO REQUERIDA DEL MES ANTERIOR 
,	OP_RES_CONST_ANT	DECIMAL	(19,4)	--RESERVAS DE SANEAMIENTO CONSTITUIDA DEL MES ANTERIOR 
,	OP_RESULTADO_CALIF	DECIMAL	(1,0)	--CÓDIGO RESULTADO DE LA EVALUACIÓN 
,	OP_TIPO_MOROSIDAD	DECIMAL	(1,0)	--CÓDIGO TIPO MOROSIDAD 
,	OP_RANGO_MOROSIDAD	DECIMAL	(2,0)	--RANGO DE DIAS MORA MAYOR 
,	OP_RANGO_SALDO_TOTAL	DECIMAL	(2,0)	--RANGO DE SALDO 
,	OP_TIPO_OPER_SSF	VARCHAR	(10)	--CÓDIGO TIPO OPERACIÓN SEGÚN SSF 
,	OP_DESTINO_OPER_SSF	VARCHAR	(10)	--CODIGO DE DESTINO DE LA OPERACIÓN SEGÚN CODIFICACIÓN DE LA SSF.
,	OP_RANGO_PLAZO_FALTANTE	DECIMAL	(2,0)	--RANGO DE PLAZO FALTANTE 
,	OP_TIPO_LINEA_CR	VARCHAR	(10)	--CODIGO DE TIPO DE LINEA 
,	OP_CUENTA_CAP	VARCHAR	(20)	--CÓDIGO DE LA CUENTA CONTABLE DE CAPITAL 
,	OP_CUENTA_INT	VARCHAR	(20)	--CÓDIGO DE LA CUENTA CONTABLE DE INTERESES
,	OP_CUOTA	DECIMAL	(19,4)	--VALOR DE LA CUOTA
,	OP_NUM_LINEA	DECIMAL	(4,0)	--NÚMERO DE LINEA 
,	OP_OPERACION_CANCELO	VARCHAR	(24)	--OPERACIÓN CANCELADA 
,	OP_CLASE_GASTO	VARCHAR	(10)	--CÓDIGO DE CLASE DE GASTO 
,	OP_UNIDAD_MEDIDA	VARCHAR	(10)	--CÓDIGO DE UNIDAD DE MEDIDA 
,	OP_CANTIDAD_FINANCIADAS	DECIMAL	(19,4)	--CANTIDAD FINANCIADA 
,	OP_TRAMITE	DECIMAL	(4,0)	--NÚMERO DE TRAMITE 
,	OP_CUPOS_TERCEROS	VARCHAR	(10)	--CÓDIGO DE CUPOS TERCEROS 
,	OP_ULT_PAGCAP	DATE		--FECHA DE ÚLTIMO PAGO DE CAPITAL 
,	OP_ULT_PAGINT	DATE		--FECHA DE ÚLTIMO PAGO DE INTERÉS 
,	OP_FULT_REAJ	DATE		--FECHA DE ÚLTIMO REAJUSTE 
,	OP_FECHA_ESCRITURACION	DATE		--FECHA DE ESCRITURACIÓN 
,	OP_FECHA_DESDE_MORA_CAP	DATE		--FECHA DE INICIO DE MORA CAPITAL 
,	OP_FECHA_DESDE_MORA_INTS	DATE		--FECHA DE INICIO DE MORA INTERES 
,	OP_CUOT_MOCAP	DECIMAL	(5,0)	--NÚMERO DE CUOTAS EN MORA DE CAPITAL 
,	OP_CUOT_MOINT	DECIMAL	(5,0)	--NÚMERO DE CUOTAS EN MORA DE INTERES 
,	OP_PAGO_ADECAP	DECIMAL	(19,4)	--PAGO DE ADELANTO DE CAPITAL 
,	OP_CUOTAS_PAG	DECIMAL	(2,0)	--NÚMERO DE CUOTAS PAGADAS 
,	OP_DIAS_ANIO	DECIMAL	(3,0)	--NÚMEROS DE DIAS DEL AÑO 
,	OP_FECPROXCUO	DATE		--FECHA DE LA PRÓXIMA CUOTA 
,	OP_CLABAS	VARCHAR	(10)	--CLASIFICACION BASICA DEL PRESTAMO  
,	OP_VAL_GTIA_HIPO	DECIMAL	(19,4)	--  VALOR ACUMULADO DE GARANTIAS HIPOTECARIAS 
,	OP_VAL_GTIA_OTRAS	DECIMAL	(19,4)	--VALOR ACUMULADO DE OTRAS GARANTIAS NO HIPOTECARIAS 
,	OP_RIESGOS_A_RVA	DECIMAL	(19,4)	--RIESGO NETO 
,	OP_MONTO_SEGURO	DECIMAL	(19,4)	--MONTO DEL SEGURO DEL CREDITO 
,	OP_TIPO_PLAZO	VARCHAR	(10)	--TIPO DE PLAZO 
,	OP_MODIFICADO	VARCHAR	(1)	--BANDERA DE MODIFICACION 
,	OP_TIPO_DIVIDENDO	VARCHAR	(10)	--TIPO DIVIDENDO 
,	OP_RIESGO_A_RVA_ANT	DECIMAL	(19,4)	--RIESGO NETO DEL MES ANTERIOR 
,	OP_TASA_INI	DECIMAL	(6,4)	--TASA  INTERES INICIAL 
,	OP_DIAS_PRORROGA	DECIMAL	(4,0)	--DIAS DE PRORROGA 
,	OP_FECHA_INI_PRORR	DATE		--FECHA INICIO DE PRORROGA 
,	OP_TIPO_TASA_REFERENCIA	VARCHAR	(10)	--TIPO DE LA TASA DE REFERENCIA 
,	OP_FECHA_PROX_REAJUSTE	DATE		--FECHA DEL PROXIMO AJUSTE 
,	OP_TIPOTC	VARCHAR	(1)	--TIPO DE TARJETA DE CRÉDITO 
,	OP_CLASETC	VARCHAR	(1)	--CLASE DE TARJETA DE CRÉDITO 
,	OP_PRODUCTOTC	VARCHAR	(20)	--PRODUCTO DE LA TARJETA DE CRÉDITO 
,	VEHICULO_LEGAL	VARCHAR	(3)	--VEHICULO LEGAL 
,	EPP_POST_ACCOUNT	VARCHAR	(19)	--PAN 
,	OP_STATUS	VARCHAR	(1)	--STATUS DE CUENTA
,	CODBLQ1	DECIMAL	(2,0)	--CODIGO DE BLOQUEO 1 
,	CODBLQ2	DECIMAL	(2,0)	--CODIGO DE BLOQUEO 2 
,	FECBLQ1	DATE		--FECHA DE BLOQUEO 1 DE CUENTA 
,	FECBLQ2	DATE		--FECHA DE BLOQUEO 2 DE CUENTA 
,	LOGO	VARCHAR	(4)	--CODIGO DE SUBPRODUCTO
,	LOAD_DATE	DATE null default getdate()		--FECHA DE CARGA
); COMMIT;	 	 		