DROP TABLE IF EXISTS "STG"."PTMOINTR";

CREATE TABLE IF NOT EXISTS "STG"."PTMOINTR" (
	"FECHA" DATE NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"NUMREFEREN" VARCHAR(24) NULL ,
	"INTNVOSRF" DECIMAL(9,2) NULL ,
	"PAGINTRF" DECIMAL(9,2) NULL ,
	"TOTAL_BALANCE" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;
