DROP TABLE IF EXISTS "STG_SAT"."PTOCONC";

CREATE TABLE IF NOT EXISTS "STG_SAT"."PTOCONC" (
	"FECHA" DATE NULL ,
	"OP_TIPO_OPER_SSF" VARCHAR(10) NULL ,
	"OP_TIPO_OPER" VARCHAR(2) NULL ,
	"OP_CLABAS" VARCHAR(10) NULL ,
	"OP_COSTUMER_TYPE" VARCHAR(10) NULL ,
	"OP_CAPITAL_VIG" DECIMAL(9,2) NULL ,
	"OP_CAPITAL_VEN" DECIMAL(9,2) NULL ,
	"OP_INTERES_VIG" DECIMAL(9,2) NULL ,
	"OP_INTERES_VEN" DECIMAL(9,2) NULL ,
	"TOTAL" DECIMAL(9,2) NULL ,
	"LEGAL_VEHICLE" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;
