DROP TABLE IF EXISTS "STG_SAT"."PTREDEIN";
DROP TABLE IF EXISTS "STG"."PTREDEIN";

drop table IF EXISTS STG_SAT.PTREDEIN;  CREATE TABLE IF NOT EXISTS STG_SAT.PTREDEIN  ( 	FEC_MOV 	DATE		--FECHA 
--LISTADO RESUME DEFERRED INTERES	 	 		
,	SDO_ANT_DIF 	DECIMAL	(11,2)	--SALDO ANTERIOR DE INTERES DIFERIDO 
,	NUEVOS_INT_DIF	DECIMAL	(11,2)	--SALDOS  DE  INTERES  (REFINANCIAMIENTO OTORGADOS DEL MES) 
,	PAGOS_INT_DIF 	DECIMAL	(11,2)	--PAGOS DEL MES DE INTERES DIFERIDOS 
,	SDO_ACT_INT_DIF 	DECIMAL	(11,2)	--SALDO  ACTUAL  DE  INTERES  DIFERIDO. (SALDO ANTERIOR+ NUEVO INTERESES DIFERIDOSPAGOS INTERESES DIFERIDOS)
,	VEHICULO_LEGAL            	VARCHAR	(3)	--VEHICULO_LEGAL 
,	LOAD_DATE	DATE null default getdate()		--FECHA DE CARGA
); COMMIT;	 	 		