DROP TABLE IF EXISTS "SAT"."PTCHARGE";

CREATE TABLE IF NOT EXISTS "SAT"."PTCHARGE" (
	"CAPITAL" DECIMAL(9,2) NULL ,
	"CIF" VARCHAR(24) NULL ,
	"CUENTA" VARCHAR(24) NULL ,
	"FECOTOR" DATE NULL ,
	"FECVENT" DATE NULL ,
	"FVENCT" DATE NULL ,
	"INTERES" DECIMAL(9,2) NULL ,
	"MONTO" DECIMAL(9,2) NULL ,
	"NIT" VARCHAR(24) NULL ,
	"NOMBRE" VARCHAR(100) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;
