drop table IF EXISTS SAT.PTDEDEIN;  CREATE TABLE IF NOT EXISTS SAT.PTDEDEIN  ( 	IDW_FECHA	DATE		--FECHA 
--LISTADO DETAILED DEFEREED INTERES	 	 		
,	OP_CLIENTE 	VARCHAR	(24)	--CÓDIGO DEL CLIENTE / NÚMERO ÚNICO DEL BANCO. 
,	REFERENCIA 	VARCHAR	(24)	--NUMERO DE REFERENCIA QUE POSEE EL DEUDOR POR LA DEUDA 
,	FEC_REF 	DATE		--FECHA DE REFINANCIAMIENTO 
,	SDO_ORG_DIF 	DECIMAL	(11,2)	--BALANCE INTERESES DEVENGADOS 
,	VEHICULO_LEGAL         	VARCHAR	(3)	--VEHICULO_LEGAL 
,	LOAD_DATE	DATE null default getdate()		--FECHA DE CARGA
); COMMIT;	 	 		