DROP TABLE IF EXISTS "STG_SAT"."PTCREBAL";
DROP TABLE IF EXISTS "STG"."PTCREBAL";

drop table IF EXISTS STG_SAT.PTCREBAL;  CREATE TABLE IF NOT EXISTS STG_SAT.PTCREBAL  ( 	IDW_DATE	DATE		--FECHA 
--LISTADO CREDIT BALANCE	 	 		
,	NIT_PERSONA 	VARCHAR	(24)	--NUMERO DE IDENTIFICACION TRIBUTARIA 
,	PRIMAPELL 	VARCHAR	(20)	--PRIMER PAELLIDO 
,	SEGUAPELL 	VARCHAR	(20)	--SEGUNDO APELLIDO 
,	APECASADA 	VARCHAR	(20)	--APELLIDO DE CASADA 
,	PRIMNOMB 	VARCHAR	(22)	--PRIMER NOMBRE 
,	SEGUNOMB 	VARCHAR	(20)	--SEGUNDO NOMBRE  
,	NOMSOCIE 	VARCHAR	(100)	--NOMBRE DE LA SOCIEDAD 
,	NUMREFEREN 	VARCHAR	(20)	--NUMERO DE REFERENCIA QUE POSEE EL DEUDOR POR LA DEUDA 
,	MONTOREFER 	DECIMAL	(11,2)	--MONTO OTORGADO ORIGINALMENTE 
,	SALDO 	DECIMAL	(11,2)	--SALDO TOTAL DE LA REFERENCIA 
,	FECOTOGAM 	DATE		--FECHA EN LA QUE FUE OTORGADO 
,	FECVENCIMI 	DATE		--FECHA VENCIMIENTO 
,	TASAINTE 	DECIMAL	(6,4)	--TASA VIGENTE EN EL MES REPORTADO 
,	ESTADO_OPER 	VARCHAR	(10)	--ESTADO DE LA OPERACIÓN PARA OBTENER SI LA CUENTA ESTÁ SANEADA 
,	VEHICULO_LEGAL            	VARCHAR	(3)	--VEHÍCULO LEGAL 
,	LOAD_DATE	DATE null default getdate()		--FECHA DE CARGA
); COMMIT;	 	 		
