DROP TABLE IF EXISTS "STG_SAT"."PTCTRIRE";
DROP TABLE IF EXISTS "STG"."PTCTRIRE";

drop table IF EXISTS STG_SAT.PTCTRIRE;  CREATE TABLE IF NOT EXISTS STG_SAT.PTCTRIRE  ( 	IDW_FECHA	DATE		--FECHA 
--LISTADO CTRIRECA	 	 		
,	OP_CLIENTE 	VARCHAR	(24)	--CÓDIGO DEL CLIENTE / NÚMERO ÚNICO DEL BANCO. 
,	CODCARTERA 	VARCHAR	(2)	--CÓDIGO DE TIPO DE CARTERA NUEVO 
,	CODACTIVO 	VARCHAR	(2)	--ACTIVO DE RIESGOS NUEVO 
,	NUMREFEREN 	VARCHAR	(24)	--NUEVO NÚMERO DE REFERENCIA 
,	CODCARTCAN 	VARCHAR	(2)	--CÓDIGO DE TIPO DE CARTERA NUEVO 
,	CODACTICAN 	VARCHAR	(2)	--ACTIVO DE RIESGOS ANTERIOR 
,	NUMREFECAN 	VARCHAR	(24)	--NUMERO DE REFERENCIA ANTERIOR 
,	TOTPAGCAP 	DECIMAL	(11,2)	--TOTAL DE PAGO CAPITAL 
,	TOTPAGINT 	DECIMAL	(11,2)	--TOTAL PAGO DE INTERESES 
,	SDOTOTINT 	DECIMAL	(11,2)	--SALDO TOTAL DE INTERESES 
,	VEHICULO_LEGAL            	VARCHAR	(3)	--VEHICULO_LEGAL 
,	LOAD_DATE	DATE null default getdate()		--FECHA DE CARGA
); COMMIT;	 	 		