DROP TABLE IF EXISTS "STG_SAT"."PTCHARGE";
DROP TABLE IF EXISTS "STG"."PTCHARGE";

drop table IF EXISTS STG_SAT.PTCHARGE;  CREATE TABLE IF NOT EXISTS STG_SAT.PTCHARGE  ( 	IDW_DATE	DATE		--FECHA 
--LISTADO CHARGE OFF ACCOUNT	 	 		
,	CUENTA 	VARCHAR	(24)	--NÚMERO DE REFERENCIA DEL DEUDOR 
,	CIF 	VARCHAR	(24)	--NUMERO DE CIF ASIGNADO AL DEUDOR 
,	NIT 	VARCHAR	(24)	--NÚMERO DE IDENTIDAD 
,	NOMBRE 	VARCHAR	(100)	--NOMBRE DEL DEUDOR 
,	FECOTOR 	DATE		--FECHA DE OTORGAMIENTO 
,	FVENCT 	DATE		--FECHA DE VENCIMIENTO 
,	MONTO 	DECIMAL	(11,2)	--MONTO ORIGINAL 
,	CAPITAL 	DECIMAL	(11,2)	--SALDO CAPITAL 
,	INTERES 	DECIMAL	(11,2)	--SALDO DE INTERÉS 
,	FECVENT 	DATE		--FECHA DE TRASLADO A SANEADA 
,	VEHICULO_LEGAL  	VARCHAR	(3)	--VEHICULO_LEGAL 
,	ORG 	VARCHAR	(4)	--CÓDIGO DE ENTIDAD 
,	LOAD_DATE	DATE null default getdate()		--FECHA DE CARGA
); COMMIT;	 	 		