DROP TABLE IF EXISTS "SAT"."PTDEDEIN";

CREATE TABLE IF NOT EXISTS "SAT"."PTDEDEIN" (
	"FECHA" DATE NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"NUMREFEREN" VARCHAR(24) NULL ,
	"FEC_REF" DATE NULL ,
	"SDO_ORG_DIF" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;
