DROP TABLE IF EXISTS "STG"."PTCTRIRE";

CREATE TABLE IF NOT EXISTS "STG"."PTCTRIRE" (
	"FECHA" DATE NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"CODCARTERA" VARCHAR(2) NULL ,
	"CODACTIVO" VARCHAR(2) NULL ,
	"NUMREFEREN" VARCHAR(24) NULL ,
	"CODCARTCAN" VARCHAR(2) NULL ,
	"CODACTICAN" VARCHAR(2) NULL ,
	"NUMREFECAN" VARCHAR(24) NULL ,
	"TOTPAGCAP" DECIMAL(9,2) NULL ,
	"TOTPAGINT" DECIMAL(9,2) NULL ,
	"SDOTOTINT" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;
