--- creacion de grupo de usuarios SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'SAT')
BEGIN
  CREATE USER SAT 
  FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

--- creacion de grupo de usuarios STG
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'STG')
BEGIN
  CREATE USER STG
  FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

DROP TABLE IF EXISTS  "SAT"."PTREFMAS";
CREATE TABLE IF NOT EXISTS "SAT"."PTREFMAS" (
	"MIS_DATE" DATE NULL ,
	"DW_ACCT_NBR" VARCHAR(24) NULL ,
	"DW_ORG" INTEGER NULL ,
	"DW_LOGO" INTEGER NULL ,
	"DW_REL_NBR" VARCHAR(24) NULL ,
	"DW_ACCT_TYPE" VARCHAR(1) NULL ,
	"DW_OPEN_DATE" DATE NULL ,
	"DW_CLOSE_DATE" DATE NULL ,
	"DW_ORG_ACCT_NBR" VARCHAR(24) NULL ,
	"DW_ORG_ACCT_DPD" INTEGER NULL ,
	"DW_ORG_ACCT_PRIN" DECIMAL(9,2) NULL ,
	"DW_ORG_ACCT_INT" DECIMAL(9,2) NULL ,
	"DW_CYCLE_DUE" INTEGER NULL ,
	"DW_DAYS_PAST_DUE" INTEGER NULL ,
	"DW_DELQ_HISTORY" VARCHAR(1) NULL ,
	"DW_NEW_ACCT_IND" VARCHAR(1) NULL ,
	"DW_LOAN_MOB" INTEGER NULL ,
	"MH_LOAN_AMT" DECIMAL(9,2) NULL ,
	"MH_LOAN_DATE" DATE NULL ,
	"MH_EFF_TENOR" INTEGER NULL ,
	"MH_OUTST_BAL" DECIMAL(9,2) NULL ,
	"MH_OUTST_TENOR" DECIMAL(9,2) NULL ,
	"MH_BILLED_INSTALL" INTEGER NULL ,
	"MH_BILLED_INT" DECIMAL(9,2) NULL ,
	"MH_BILLED_PRIN" DECIMAL(9,2) NULL ,
	"DW_INT_PAID_MTH" DECIMAL(9,2) NULL ,
	"DW_PRIN_PAID_MTH" DECIMAL(9,2) NULL ,
	"DW_TOT_INT_PAID" DECIMAL(9,2) NULL ,
	"DW_TOT_PRIN_PAID" DECIMAL(9,2) NULL ,
	"DT_NEW_INT_DEF" DECIMAL(9,2) NULL ,
	"DT_INT_DEF_AMT" DECIMAL(9,2) NULL ,
	"DT_INT_DEF_BAL" DECIMAL(9,2) NULL ,
	"DT_INT_DEF_BAL_PREV" DECIMAL(9,2) NULL ,
	"DT_OWN_DPD_FLAG" VARCHAR(1) NULL ,
	"DT_RISK_CALIFICATION" VARCHAR(10) NULL ,
	"DW_LEGAL_VEHICLE" VARCHAR(3) NULL ,
	"DW_PAYMENT_HISTORY" VARCHAR(1) NULL ,
	"DW_REFIN_FLAG" VARCHAR(2) NULL ,
	"DW_BS_USER_DATE_4" DATE NULL ,
	"HB_FH_AMT_PMTS_01" DECIMAL(9,2) NULL ,
	"HB_FH_TOT_AMT_DUE_02" DECIMAL(9,2) NULL ,
	"PT_MT_AMOUNT" DECIMAL(9,2) NULL ,
	"DW_BS_CURR_BAL" DECIMAL(9,2) NULL ,
	"DW_BS_LAST_PYMT_DUE" DATE NULL ,
	"DT_PAYOFF_FLAG" VARCHAR(1) NULL ,
	"DW_BS_AMT_OUTST_EPP" DECIMAL(9,2) NULL ,
	"DW_BS_ALOP_OUTST_BAL" DECIMAL(9,2) NULL ,
	"DW_SALDO_TOTAL" DECIMAL(9,2) NULL ,
	"DW_CUS_TYPE" VARCHAR(24) NULL ,
	"DW_CUS_SEGMENT" VARCHAR(1) NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS  "SAT"."PTCTRIRE";

CREATE TABLE IF NOT EXISTS "SAT"."PTCTRIRE" (
	"FECHA" DATE NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"CODCARTERA" VARCHAR(2) NULL ,
	"CODACTIVO" VARCHAR(2) NULL ,
	"NUMREFEREN" VARCHAR(24) NULL ,
	"CODCARTCAN" VARCHAR(2) NULL ,
	"CODACTICAN" VARCHAR(2) NULL ,
	"NUMREFECAN" VARCHAR(24) NULL ,
	"TOTPAGCAP" DECIMAL(9,2) NULL ,
	"TOTPAGINT" DECIMAL(9,2) NULL ,
	"SDOTOTINT" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "SAT"."PTREDEIN";

CREATE TABLE IF NOT EXISTS "SAT"."PTREDEIN" (
	"FEC_MOV" DATE NULL ,
	"SDO_ANT_DIF" DECIMAL(9,2) NULL ,
	"NUEVOS_INT_DIF" DECIMAL(9,2) NULL ,
	"PAGOS_INT_DIF" DECIMAL(9,2) NULL ,
	"SDO_ACT_INT_DIF" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "SAT"."PTMOINTR";

CREATE TABLE IF NOT EXISTS "SAT"."PTMOINTR" (
	"FECHA" DATE NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"NUMREFEREN" VARCHAR(24) NULL ,
	"INTNVOSRF" DECIMAL(9,2) NULL ,
	"PAGINTRF" DECIMAL(9,2) NULL ,
	"TOTAL_BALANCE" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "SAT"."PTDEDEIN";

CREATE TABLE IF NOT EXISTS "SAT"."PTDEDEIN" (
	"FECHA" DATE NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"NUMREFEREN" VARCHAR(24) NULL ,
	"FEC_REF" DATE NULL ,
	"SDO_ORG_DIF" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "SAT"."PTCHARGE";

CREATE TABLE IF NOT EXISTS "SAT"."PTCHARGE" (
	"CAPITAL" DECIMAL(9,2) NULL ,
	"CIF" VARCHAR(24) NULL ,
	"CUENTA" VARCHAR(24) NULL ,
	"FECOTOR" DATE NULL ,
	"FECVENT" DATE NULL ,
	"FVENCT" DATE NULL ,
	"INTERES" DECIMAL(9,2) NULL ,
	"MONTO" DECIMAL(9,2) NULL ,
	"NIT" VARCHAR(24) NULL ,
	"NOMBRE" VARCHAR(100) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "SAT"."PTCREBAL";

CREATE TABLE IF NOT EXISTS "SAT"."PTCREBAL" (
	"NITPERSONA" VARCHAR(24) NULL ,
	"PRIMAPELL" VARCHAR(20) NULL ,
	"SEGUAPELL" VARCHAR(20) NULL ,
	"APECASADA" VARCHAR(20) NULL ,
	"PRIMNOMB" VARCHAR(22) NULL ,
	"SEGUNOMB" VARCHAR(20) NULL ,
	"NOMSOCIE" VARCHAR(100) NULL ,
	"NUMREFEREN" VARCHAR(20) NULL ,
	"MONTOREFER" DECIMAL(9,2) NULL ,
	"SALDO" DECIMAL(9,2) NULL ,
	"FECOTOGAM" DATE NULL ,
	"FECVENCIMI" DATE NULL ,
	"TASAINTE" DECIMAL(7,4) NULL ,
	"ESTADO_OPER" VARCHAR(10) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "SAT"."PTOCOPS";

CREATE TABLE IF NOT EXISTS "SAT"."PTOCOPS" (
	"FECHA" DATE NULL ,
	"OP_TIPO_OPER_SSF" VARCHAR(10) NULL ,
	"OP_TIPO_OPER" VARCHAR(2) NULL ,
	"OP_CLABAS" VARCHAR(10) NULL ,
	"OP_COSTUMER_TYPE" VARCHAR(10) NULL ,
	"CAPITAL_VIGENTE" DECIMAL(9,2) NULL ,
	"CAPITAL_VENCIDO" DECIMAL(9,2) NULL ,
	"INTERES_VIGENTE" DECIMAL(9,2) NULL ,
	"INTERES_VENCIDO" DECIMAL(9,2) NULL ,
	"TOTAL" DECIMAL(9,2) NULL ,
	"BRAND" VARCHAR(1) NULL ,
	"LEGAL_VEHICLE" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "SAT"."PTOCONC";

CREATE TABLE IF NOT EXISTS "SAT"."PTOCONC" (
	"FECHA" DATE NULL ,
	"OP_TIPO_OPER_SSF" VARCHAR(10) NULL ,
	"OP_TIPO_OPER" VARCHAR(2) NULL ,
	"OP_CLABAS" VARCHAR(10) NULL ,
	"OP_COSTUMER_TYPE" VARCHAR(10) NULL ,
	"OP_CAPITAL_VIG" DECIMAL(9,2) NULL ,
	"OP_CAPITAL_VEN" DECIMAL(9,2) NULL ,
	"OP_INTERES_VIG" DECIMAL(9,2) NULL ,
	"OP_INTERES_VEN" DECIMAL(9,2) NULL ,
	"TOTAL" DECIMAL(9,2) NULL ,
	"LEGAL_VEHICLE" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "SAT"."PTPROINT";

CREATE TABLE IF NOT EXISTS "SAT"."PTPROINT" (
	"PV_FECHA_CORTE" DATE NULL ,
	"PV_NUM_OP_IFI" VARCHAR(24) NULL ,
	"PV_CLIENTE" VARCHAR(24) NULL ,
	"PV_TIPO_OPER" VARCHAR(2) NULL ,
	"PV_BALANCE_INT" DECIMAL(9,2) NULL ,
	"PV_ACUMU_INT" DECIMAL(9,2) NULL ,
	"PV_TOTAL_INT" DECIMAL(9,2) NULL ,
	"PV_OP_CLABAS" VARCHAR(10) NULL ,
	"PV_TASA_ORIG" DECIMAL(7,4) NULL ,
	"PV_BILLING_CYCLE" VARCHAR(2) NULL ,
	"PV_BALANCE_PRINC" DECIMAL(9,2) NULL ,
	"PV_BRAND" VARCHAR(1) NULL ,
	"PV_VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "SAT"."PTOPERAC";

CREATE TABLE IF NOT EXISTS "SAT"."PTOPERAC" (
	"OP_FECHA_CORTE" DATE NULL ,
	"OP_FILIAL" INTEGER NULL ,
	"OP_PRODUCTO" INTEGER NULL ,
	"OP_OPERACION" DECIMAL(10,0) NULL ,
	"OP_NUM_OP_IFI" VARCHAR(24) NULL ,
	"OP_OFICIAL" VARCHAR(10) NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"OP_CIUDAD" INTEGER NULL ,
	"OP_OFICINA" INTEGER NULL ,
	"OP_MONEDA" INTEGER NULL ,
	"OP_SECTOR_CONTABLE" VARCHAR(2) NULL ,
	"OP_SECTOR_REAL" VARCHAR(2) NULL ,
	"OP_DESTINO" VARCHAR(10) NULL ,
	"OP_TIPO_OPER" VARCHAR(2) NULL ,
	"OP_CATEG_CONT" VARCHAR(1) NULL ,
	"OP_CATEGORIA_OPER" VARCHAR(2) NULL ,
	"OP_CLASE_GTIA" VARCHAR(2) NULL ,
	"OP_TIPO_CARTERA" VARCHAR(2) NULL ,
	"OP_TIPO_TRAMITE" VARCHAR(1) NULL ,
	"OP_FECHA_INI" DATE NULL ,
	"OP_FECHA_FIN" DATE NULL ,
	"OP_FECHA_FIN_LEGAL" DATE NULL ,
	"OP_FECHA_CAS" DATE NULL ,
	"OP_FECHA_PAG" DATE NULL ,
	"OP_FECHA_CAN" DATE NULL ,
	"OP_PLAZO" INTEGER NULL ,
	"OP_TOTAL_CUOTAS" INTEGER NULL ,
	"OP_TIPO_AMORTIZ" VARCHAR(10) NULL ,
	"OP_GRACIA_CAP" INTEGER NULL ,
	"OP_GRACIA_INT" INTEGER NULL ,
	"OP_PERIODO_CAP" INTEGER NULL ,
	"OP_PERIODO_INT" INTEGER NULL ,
	"OP_MOROSIDAD_CAP" INTEGER NULL ,
	"OP_MOROSIDAD_INT" INTEGER NULL ,
	"OP_TASA_ORIGINAL" DECIMAL(7,4) NULL ,
	"OP_TASA_ACTUAL" DECIMAL(7,4) NULL ,
	"OP_TASA_REF" DECIMAL(7,4) NULL ,
	"OP_TASA_EFECTIVA" DECIMAL(7,4) NULL ,
	"OP_FORMA_REAJUSTE" VARCHAR(1) NULL ,
	"OP_ORIGEN_FONDOS" VARCHAR(5) NULL ,
	"OP_VALOR_ORIGINAL" DECIMAL(9,2) NULL ,
	"OP_SALDO_CAPITAL" DECIMAL(9,2) NULL ,
	"OP_DESEMBOLSOS" DECIMAL(9,2) NULL ,
	"OP_CAPITAL_VCDO" DECIMAL(9,2) NULL ,
	"OP_CAPITAL_MORA" DECIMAL(9,2) NULL ,
	"OP_SALDO_INTERES" DECIMAL(9,2) NULL ,
	"OP_INTERES_VCDO" DECIMAL(9,2) NULL ,
	"OP_INTERES_MORA" DECIMAL(9,2) NULL ,
	"OP_RIESGO" DECIMAL(9,2) NULL ,
	"OP_ABONO_PEND" DECIMAL(9,2) NULL ,
	"OP_VAL_ACTUAL_GTIA" DECIMAL(9,2) NULL ,
	"OP_VAL_REAL_GTIA" DECIMAL(9,2) NULL ,
	"OP_COB_ACTUAL_GTIA" DECIMAL(9,2) NULL ,
	"OP_COB_REAL_GTIA" DECIMAL(9,2) NULL ,
	"OP_GARANTIA_INSCRITA" VARCHAR(1) NULL ,
	"OP_GARANTE_CART_PIG" VARCHAR(2) NULL ,
	"OP_TIPO_CERTIFICADO" VARCHAR(2) NULL ,
	"OP_FACTOR_MLO" DECIMAL(7,4) NULL ,
	"OP_ESTADO_OPER" VARCHAR(10) NULL ,
	"OP_USUARIO_MODIF" VARCHAR(14) NULL ,
	"OP_FECHA_MODIF" DATE NULL ,
	"OP_MORA" DECIMAL(9,2) NULL ,
	"OP_TASA_MORA" DECIMAL(7,4) NULL ,
	"OP_CUOTAS_MORA" INTEGER NULL ,
	"OP_CALIFICACION" VARCHAR(10) NULL ,
	"OP_RANGO_PLAZO" INTEGER NULL ,
	"OP_RANGO_MORA_CAP" INTEGER NULL ,
	"OP_RANGO_MORA_INT" INTEGER NULL ,
	"OP_RESERVA_REQUERIDA" DECIMAL(9,2) NULL ,
	"OP_RESERVA_CONSTITUIDA" DECIMAL(9,2) NULL ,
	"OP_DEDUCCIONES" DECIMAL(9,2) NULL ,
	"OP_COBERTURA_GTIA" DECIMAL(9,2) NULL ,
	"OP_ETAPA_COBRO" VARCHAR(10) NULL ,
	"OP_CALIF_ANT" VARCHAR(10) NULL ,
	"OP_RES_REQUE_ANT" DECIMAL(9,2) NULL ,
	"OP_RES_CONST_ANT" DECIMAL(9,2) NULL ,
	"OP_RESULTADO_CALIF" INTEGER NULL ,
	"OP_TIPO_MOROSIDAD" INTEGER NULL ,
	"OP_RANGO_MOROSIDAD" INTEGER NULL ,
	"OP_RANGO_SALDO_TOTAL" INTEGER NULL ,
	"OP_TIPO_OPER_SSF" VARCHAR(10) NULL ,
	"OP_DESTINO_OPER_SSF" VARCHAR(10) NULL ,
	"OP_RANGO_PLAZO_FALTANTE" INTEGER NULL ,
	"OP_TIPO_LINEA_CR" VARCHAR(10) NULL ,
	"OP_CUENTA_CAP" VARCHAR(20) NULL ,
	"OP_CUENTA_INT" VARCHAR(20) NULL ,
	"OP_CUOTA" DECIMAL(9,2) NULL ,
	"OP_NUM_LINEA" INTEGER NULL ,
	"OP_OPERACION_CANCELO" VARCHAR(24) NULL ,
	"OP_CLASE_GASTO" VARCHAR(10) NULL ,
	"OP_UNIDAD_MEDIDA" VARCHAR(10) NULL ,
	"OP_CANTIDAD_FINANCIADAS" DECIMAL(9,2) NULL ,
	"OP_TRAMITE" INTEGER NULL ,
	"OP_CUPOS_TERCEROS" VARCHAR(10) NULL ,
	"OP_ULT_PAGCAP" DATE NULL ,
	"OP_ULT_PAGINT" DATE NULL ,
	"OP_FULT_REAJ" DATE NULL ,
	"OP_FECHA_ESCRITURACION" DATE NULL ,
	"OP_FECHA_DESDE_MORA_CAP" DATE NULL ,
	"OP_FECHA_DESDE_MORA_INTS" DATE NULL ,
	"OP_CUOT_MOCAP" INTEGER NULL ,
	"OP_CUOT_MOINT" INTEGER NULL ,
	"OP_PAGO_ADECAP" DECIMAL(9,2) NULL ,
	"OP_CUOTAS_PAG" INTEGER NULL ,
	"OP_DIAS_ANIO" INTEGER NULL ,
	"OP_FECPROXCUO" DATE NULL ,
	"OP_CLABAS" VARCHAR(10) NULL ,
	"OP_VAL_GTIA_HIPO" DECIMAL(9,2) NULL ,
	"OP_VAL_GTIA_OTRAS" DECIMAL(9,2) NULL ,
	"OP_RIESGOS_A_RVA" DECIMAL(9,2) NULL ,
	"OP_MONTO_SEGURO" DECIMAL(9,2) NULL ,
	"OP_TIPO_PLAZO" VARCHAR(10) NULL ,
	"OP_MODIFICADO" VARCHAR(1) NULL ,
	"OP_TIPO_DIVIDENDO" VARCHAR(10) NULL ,
	"OP_RIESGO_A_RVA_ANT" DECIMAL(9,2) NULL ,
	"OP_TASA_INI" DECIMAL(7,4) NULL ,
	"OP_DIAS_PRORROGA" INTEGER NULL ,
	"OP_FECHA_INI_PRORR" DATE NULL ,
	"OP_TIPO_TASA_REFERENCIA" VARCHAR(10) NULL ,
	"OP_FECHA_PROX_REAJUSTE" DATE NULL ,
	"OP_TIPOTC" VARCHAR(1) NULL ,
	"OP_CLASETC" VARCHAR(1) NULL ,
	"OP_PRODUCTOTC" VARCHAR(20) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"EPP_POST_ACCOUNT" VARCHAR(19) NULL ,
	"STATUS" VARCHAR(1) NULL ,
	"CODBLQ1" INTEGER NULL ,
	"CODBLQ2" INTEGER NULL ,
	"FECBLQ1" DATE NULL ,
	"FECBLQ2" DATE NULL ,
	"CONPROD" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;


--********************************************************************************

DROP TABLE IF EXISTS "STG"."PTREFMAS";

CREATE TABLE IF NOT EXISTS "STG"."PTREFMAS" (
	"MIS_DATE" DATE NULL ,
	"DW_ACCT_NBR" VARCHAR(24) NULL ,
	"DW_ORG" INTEGER NULL ,
	"DW_LOGO" INTEGER NULL ,
	"DW_REL_NBR" VARCHAR(24) NULL ,
	"DW_ACCT_TYPE" VARCHAR(1) NULL ,
	"DW_OPEN_DATE" DATE NULL ,
	"DW_CLOSE_DATE" DATE NULL ,
	"DW_ORG_ACCT_NBR" VARCHAR(24) NULL ,
	"DW_ORG_ACCT_DPD" INTEGER NULL ,
	"DW_ORG_ACCT_PRIN" DECIMAL(9,2) NULL ,
	"DW_ORG_ACCT_INT" DECIMAL(9,2) NULL ,
	"DW_CYCLE_DUE" INTEGER NULL ,
	"DW_DAYS_PAST_DUE" INTEGER NULL ,
	"DW_DELQ_HISTORY" VARCHAR(1) NULL ,
	"DW_NEW_ACCT_IND" VARCHAR(1) NULL ,
	"DW_LOAN_MOB" INTEGER NULL ,
	"MH_LOAN_AMT" DECIMAL(9,2) NULL ,
	"MH_LOAN_DATE" DATE NULL ,
	"MH_EFF_TENOR" INTEGER NULL ,
	"MH_OUTST_BAL" DECIMAL(9,2) NULL ,
	"MH_OUTST_TENOR" DECIMAL(9,2) NULL ,
	"MH_BILLED_INSTALL" INTEGER NULL ,
	"MH_BILLED_INT" DECIMAL(9,2) NULL ,
	"MH_BILLED_PRIN" DECIMAL(9,2) NULL ,
	"DW_INT_PAID_MTH" DECIMAL(9,2) NULL ,
	"DW_PRIN_PAID_MTH" DECIMAL(9,2) NULL ,
	"DW_TOT_INT_PAID" DECIMAL(9,2) NULL ,
	"DW_TOT_PRIN_PAID" DECIMAL(9,2) NULL ,
	"DT_NEW_INT_DEF" DECIMAL(9,2) NULL ,
	"DT_INT_DEF_AMT" DECIMAL(9,2) NULL ,
	"DT_INT_DEF_BAL" DECIMAL(9,2) NULL ,
	"DT_INT_DEF_BAL_PREV" DECIMAL(9,2) NULL ,
	"DT_OWN_DPD_FLAG" VARCHAR(1) NULL ,
	"DT_RISK_CALIFICATION" VARCHAR(10) NULL ,
	"DW_LEGAL_VEHICLE" VARCHAR(3) NULL ,
	"DW_PAYMENT_HISTORY" VARCHAR(1) NULL ,
	"DW_REFIN_FLAG" VARCHAR(2) NULL ,
	"DW_BS_USER_DATE_4" DATE NULL ,
	"HB_FH_AMT_PMTS_01" DECIMAL(9,2) NULL ,
	"HB_FH_TOT_AMT_DUE_02" DECIMAL(9,2) NULL ,
	"PT_MT_AMOUNT" DECIMAL(9,2) NULL ,
	"DW_BS_CURR_BAL" DECIMAL(9,2) NULL ,
	"DW_BS_LAST_PYMT_DUE" DATE NULL ,
	"DT_PAYOFF_FLAG" VARCHAR(1) NULL ,
	"DW_BS_AMT_OUTST_EPP" DECIMAL(9,2) NULL ,
	"DW_BS_ALOP_OUTST_BAL" DECIMAL(9,2) NULL ,
	"DW_SALDO_TOTAL" DECIMAL(9,2) NULL ,
	"DW_CUS_TYPE" VARCHAR(24) NULL ,
	"DW_CUS_SEGMENT" VARCHAR(1) NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTCTRIRE";

CREATE TABLE IF NOT EXISTS "STG"."PTCTRIRE" (
	"FECHA" DATE NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"CODCARTERA" VARCHAR(2) NULL ,
	"CODACTIVO" VARCHAR(2) NULL ,
	"NUMREFEREN" VARCHAR(24) NULL ,
	"CODCARTCAN" VARCHAR(2) NULL ,
	"CODACTICAN" VARCHAR(2) NULL ,
	"NUMREFECAN" VARCHAR(24) NULL ,
	"TOTPAGCAP" DECIMAL(9,2) NULL ,
	"TOTPAGINT" DECIMAL(9,2) NULL ,
	"SDOTOTINT" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTREDEIN";

CREATE TABLE IF NOT EXISTS "STG"."PTREDEIN" (
	"FEC_MOV" DATE NULL ,
	"SDO_ANT_DIF" DECIMAL(9,2) NULL ,
	"NUEVOS_INT_DIF" DECIMAL(9,2) NULL ,
	"PAGOS_INT_DIF" DECIMAL(9,2) NULL ,
	"SDO_ACT_INT_DIF" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTMOINTR";

CREATE TABLE IF NOT EXISTS "STG"."PTMOINTR" (
	"FECHA" DATE NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"NUMREFEREN" VARCHAR(24) NULL ,
	"INTNVOSRF" DECIMAL(9,2) NULL ,
	"PAGINTRF" DECIMAL(9,2) NULL ,
	"TOTAL_BALANCE" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTDEDEIN";

CREATE TABLE IF NOT EXISTS "STG"."PTDEDEIN" (
	"FECHA" DATE NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"NUMREFEREN" VARCHAR(24) NULL ,
	"FEC_REF" DATE NULL ,
	"SDO_ORG_DIF" DECIMAL(9,2) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTCHARGE";

CREATE TABLE IF NOT EXISTS "STG"."PTCHARGE" (
	"CAPITAL" DECIMAL(9,2) NULL ,
	"CIF" VARCHAR(24) NULL ,
	"CUENTA" VARCHAR(24) NULL ,
	"FECOTOR" DATE NULL ,
	"FECVENT" DATE NULL ,
	"FVENCT" DATE NULL ,
	"INTERES" DECIMAL(9,2) NULL ,
	"MONTO" DECIMAL(9,2) NULL ,
	"NIT" VARCHAR(24) NULL ,
	"NOMBRE" VARCHAR(100) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTCREBAL";

CREATE TABLE IF NOT EXISTS "STG"."PTCREBAL" (
	"NITPERSONA" VARCHAR(24) NULL ,
	"PRIMAPELL" VARCHAR(20) NULL ,
	"SEGUAPELL" VARCHAR(20) NULL ,
	"APECASADA" VARCHAR(20) NULL ,
	"PRIMNOMB" VARCHAR(22) NULL ,
	"SEGUNOMB" VARCHAR(20) NULL ,
	"NOMSOCIE" VARCHAR(100) NULL ,
	"NUMREFEREN" VARCHAR(20) NULL ,
	"MONTOREFER" DECIMAL(9,2) NULL ,
	"SALDO" DECIMAL(9,2) NULL ,
	"FECOTOGAM" DATE NULL ,
	"FECVENCIMI" DATE NULL ,
	"TASAINTE" DECIMAL(7,4) NULL ,
	"ESTADO_OPER" VARCHAR(10) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTOCOPS";

CREATE TABLE IF NOT EXISTS "STG"."PTOCOPS" (
	"FECHA" DATE NULL ,
	"OP_TIPO_OPER_SSF" VARCHAR(10) NULL ,
	"OP_TIPO_OPER" VARCHAR(2) NULL ,
	"OP_CLABAS" VARCHAR(10) NULL ,
	"OP_COSTUMER_TYPE" VARCHAR(10) NULL ,
	"CAPITAL_VIGENTE" DECIMAL(9,2) NULL ,
	"CAPITAL_VENCIDO" DECIMAL(9,2) NULL ,
	"INTERES_VIGENTE" DECIMAL(9,2) NULL ,
	"INTERES_VENCIDO" DECIMAL(9,2) NULL ,
	"TOTAL" DECIMAL(9,2) NULL ,
	"BRAND" VARCHAR(1) NULL ,
	"LEGAL_VEHICLE" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTOCONC";

CREATE TABLE IF NOT EXISTS "STG"."PTOCONC" (
	"FECHA" DATE NULL ,
	"OP_TIPO_OPER_SSF" VARCHAR(10) NULL ,
	"OP_TIPO_OPER" VARCHAR(2) NULL ,
	"OP_CLABAS" VARCHAR(10) NULL ,
	"OP_COSTUMER_TYPE" VARCHAR(10) NULL ,
	"OP_CAPITAL_VIG" DECIMAL(9,2) NULL ,
	"OP_CAPITAL_VEN" DECIMAL(9,2) NULL ,
	"OP_INTERES_VIG" DECIMAL(9,2) NULL ,
	"OP_INTERES_VEN" DECIMAL(9,2) NULL ,
	"TOTAL" DECIMAL(9,2) NULL ,
	"LEGAL_VEHICLE" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTPROINT";

CREATE TABLE IF NOT EXISTS "STG"."PTPROINT" (
	"PV_FECHA_CORTE" DATE NULL ,
	"PV_NUM_OP_IFI" VARCHAR(24) NULL ,
	"PV_CLIENTE" VARCHAR(24) NULL ,
	"PV_TIPO_OPER" VARCHAR(2) NULL ,
	"PV_BALANCE_INT" DECIMAL(9,2) NULL ,
	"PV_ACUMU_INT" DECIMAL(9,2) NULL ,
	"PV_TOTAL_INT" DECIMAL(9,2) NULL ,
	"PV_OP_CLABAS" VARCHAR(10) NULL ,
	"PV_TASA_ORIG" DECIMAL(7,4) NULL ,
	"PV_BILLING_CYCLE" VARCHAR(2) NULL ,
	"PV_BALANCE_PRINC" DECIMAL(9,2) NULL ,
	"PV_BRAND" VARCHAR(1) NULL ,
	"PV_VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;

DROP TABLE IF EXISTS "STG"."PTOPERAC";

CREATE TABLE IF NOT EXISTS "STG"."PTOPERAC" (
	"OP_FECHA_CORTE" DATE NULL ,
	"OP_FILIAL" INTEGER NULL ,
	"OP_PRODUCTO" INTEGER NULL ,
	"OP_OPERACION" DECIMAL(10,0) NULL ,
	"OP_NUM_OP_IFI" VARCHAR(24) NULL ,
	"OP_OFICIAL" VARCHAR(10) NULL ,
	"OP_CLIENTE" VARCHAR(24) NULL ,
	"OP_CIUDAD" INTEGER NULL ,
	"OP_OFICINA" INTEGER NULL ,
	"OP_MONEDA" INTEGER NULL ,
	"OP_SECTOR_CONTABLE" VARCHAR(2) NULL ,
	"OP_SECTOR_REAL" VARCHAR(2) NULL ,
	"OP_DESTINO" VARCHAR(10) NULL ,
	"OP_TIPO_OPER" VARCHAR(2) NULL ,
	"OP_CATEG_CONT" VARCHAR(1) NULL ,
	"OP_CATEGORIA_OPER" VARCHAR(2) NULL ,
	"OP_CLASE_GTIA" VARCHAR(2) NULL ,
	"OP_TIPO_CARTERA" VARCHAR(2) NULL ,
	"OP_TIPO_TRAMITE" VARCHAR(1) NULL ,
	"OP_FECHA_INI" DATE NULL ,
	"OP_FECHA_FIN" DATE NULL ,
	"OP_FECHA_FIN_LEGAL" DATE NULL ,
	"OP_FECHA_CAS" DATE NULL ,
	"OP_FECHA_PAG" DATE NULL ,
	"OP_FECHA_CAN" DATE NULL ,
	"OP_PLAZO" INTEGER NULL ,
	"OP_TOTAL_CUOTAS" INTEGER NULL ,
	"OP_TIPO_AMORTIZ" VARCHAR(10) NULL ,
	"OP_GRACIA_CAP" INTEGER NULL ,
	"OP_GRACIA_INT" INTEGER NULL ,
	"OP_PERIODO_CAP" INTEGER NULL ,
	"OP_PERIODO_INT" INTEGER NULL ,
	"OP_MOROSIDAD_CAP" INTEGER NULL ,
	"OP_MOROSIDAD_INT" INTEGER NULL ,
	"OP_TASA_ORIGINAL" DECIMAL(7,4) NULL ,
	"OP_TASA_ACTUAL" DECIMAL(7,4) NULL ,
	"OP_TASA_REF" DECIMAL(7,4) NULL ,
	"OP_TASA_EFECTIVA" DECIMAL(7,4) NULL ,
	"OP_FORMA_REAJUSTE" VARCHAR(1) NULL ,
	"OP_ORIGEN_FONDOS" VARCHAR(5) NULL ,
	"OP_VALOR_ORIGINAL" DECIMAL(9,2) NULL ,
	"OP_SALDO_CAPITAL" DECIMAL(9,2) NULL ,
	"OP_DESEMBOLSOS" DECIMAL(9,2) NULL ,
	"OP_CAPITAL_VCDO" DECIMAL(9,2) NULL ,
	"OP_CAPITAL_MORA" DECIMAL(9,2) NULL ,
	"OP_SALDO_INTERES" DECIMAL(9,2) NULL ,
	"OP_INTERES_VCDO" DECIMAL(9,2) NULL ,
	"OP_INTERES_MORA" DECIMAL(9,2) NULL ,
	"OP_RIESGO" DECIMAL(9,2) NULL ,
	"OP_ABONO_PEND" DECIMAL(9,2) NULL ,
	"OP_VAL_ACTUAL_GTIA" DECIMAL(9,2) NULL ,
	"OP_VAL_REAL_GTIA" DECIMAL(9,2) NULL ,
	"OP_COB_ACTUAL_GTIA" DECIMAL(9,2) NULL ,
	"OP_COB_REAL_GTIA" DECIMAL(9,2) NULL ,
	"OP_GARANTIA_INSCRITA" VARCHAR(1) NULL ,
	"OP_GARANTE_CART_PIG" VARCHAR(2) NULL ,
	"OP_TIPO_CERTIFICADO" VARCHAR(2) NULL ,
	"OP_FACTOR_MLO" DECIMAL(7,4) NULL ,
	"OP_ESTADO_OPER" VARCHAR(10) NULL ,
	"OP_USUARIO_MODIF" VARCHAR(14) NULL ,
	"OP_FECHA_MODIF" DATE NULL ,
	"OP_MORA" DECIMAL(9,2) NULL ,
	"OP_TASA_MORA" DECIMAL(7,4) NULL ,
	"OP_CUOTAS_MORA" INTEGER NULL ,
	"OP_CALIFICACION" VARCHAR(10) NULL ,
	"OP_RANGO_PLAZO" INTEGER NULL ,
	"OP_RANGO_MORA_CAP" INTEGER NULL ,
	"OP_RANGO_MORA_INT" INTEGER NULL ,
	"OP_RESERVA_REQUERIDA" DECIMAL(9,2) NULL ,
	"OP_RESERVA_CONSTITUIDA" DECIMAL(9,2) NULL ,
	"OP_DEDUCCIONES" DECIMAL(9,2) NULL ,
	"OP_COBERTURA_GTIA" DECIMAL(9,2) NULL ,
	"OP_ETAPA_COBRO" VARCHAR(10) NULL ,
	"OP_CALIF_ANT" VARCHAR(10) NULL ,
	"OP_RES_REQUE_ANT" DECIMAL(9,2) NULL ,
	"OP_RES_CONST_ANT" DECIMAL(9,2) NULL ,
	"OP_RESULTADO_CALIF" INTEGER NULL ,
	"OP_TIPO_MOROSIDAD" INTEGER NULL ,
	"OP_RANGO_MOROSIDAD" INTEGER NULL ,
	"OP_RANGO_SALDO_TOTAL" INTEGER NULL ,
	"OP_TIPO_OPER_SSF" VARCHAR(10) NULL ,
	"OP_DESTINO_OPER_SSF" VARCHAR(10) NULL ,
	"OP_RANGO_PLAZO_FALTANTE" INTEGER NULL ,
	"OP_TIPO_LINEA_CR" VARCHAR(10) NULL ,
	"OP_CUENTA_CAP" VARCHAR(20) NULL ,
	"OP_CUENTA_INT" VARCHAR(20) NULL ,
	"OP_CUOTA" DECIMAL(9,2) NULL ,
	"OP_NUM_LINEA" INTEGER NULL ,
	"OP_OPERACION_CANCELO" VARCHAR(24) NULL ,
	"OP_CLASE_GASTO" VARCHAR(10) NULL ,
	"OP_UNIDAD_MEDIDA" VARCHAR(10) NULL ,
	"OP_CANTIDAD_FINANCIADAS" DECIMAL(9,2) NULL ,
	"OP_TRAMITE" INTEGER NULL ,
	"OP_CUPOS_TERCEROS" VARCHAR(10) NULL ,
	"OP_ULT_PAGCAP" DATE NULL ,
	"OP_ULT_PAGINT" DATE NULL ,
	"OP_FULT_REAJ" DATE NULL ,
	"OP_FECHA_ESCRITURACION" DATE NULL ,
	"OP_FECHA_DESDE_MORA_CAP" DATE NULL ,
	"OP_FECHA_DESDE_MORA_INTS" DATE NULL ,
	"OP_CUOT_MOCAP" INTEGER NULL ,
	"OP_CUOT_MOINT" INTEGER NULL ,
	"OP_PAGO_ADECAP" DECIMAL(9,2) NULL ,
	"OP_CUOTAS_PAG" INTEGER NULL ,
	"OP_DIAS_ANIO" INTEGER NULL ,
	"OP_FECPROXCUO" DATE NULL ,
	"OP_CLABAS" VARCHAR(10) NULL ,
	"OP_VAL_GTIA_HIPO" DECIMAL(9,2) NULL ,
	"OP_VAL_GTIA_OTRAS" DECIMAL(9,2) NULL ,
	"OP_RIESGOS_A_RVA" DECIMAL(9,2) NULL ,
	"OP_MONTO_SEGURO" DECIMAL(9,2) NULL ,
	"OP_TIPO_PLAZO" VARCHAR(10) NULL ,
	"OP_MODIFICADO" VARCHAR(1) NULL ,
	"OP_TIPO_DIVIDENDO" VARCHAR(10) NULL ,
	"OP_RIESGO_A_RVA_ANT" DECIMAL(9,2) NULL ,
	"OP_TASA_INI" DECIMAL(7,4) NULL ,
	"OP_DIAS_PRORROGA" INTEGER NULL ,
	"OP_FECHA_INI_PRORR" DATE NULL ,
	"OP_TIPO_TASA_REFERENCIA" VARCHAR(10) NULL ,
	"OP_FECHA_PROX_REAJUSTE" DATE NULL ,
	"OP_TIPOTC" VARCHAR(1) NULL ,
	"OP_CLASETC" VARCHAR(1) NULL ,
	"OP_PRODUCTOTC" VARCHAR(20) NULL ,
	"VEHICULO_LEGAL" VARCHAR(3) NULL ,
	"EPP_POST_ACCOUNT" VARCHAR(19) NULL ,
	"STATUS" VARCHAR(1) NULL ,
	"CODBLQ1" INTEGER NULL ,
	"CODBLQ2" INTEGER NULL ,
	"FECBLQ1" DATE NULL ,
	"FECBLQ2" DATE NULL ,
	"CONPROD" VARCHAR(3) NULL ,
	"MIS_DATE" DATE NULL ,
	"I_FILE_ORD" INTEGER NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
)  COMMIT;
