drop table IF EXISTS SAT.ATCON001;  CREATE TABLE IF NOT EXISTS SAT.ATCON001  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
--INTERFAZ CONTABLE, CONCEPTOS CONTABLES	 	 		
--DATOS GENERALES OBLIGATORIOS	 	 		
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CODGRU	DECIMAL	(2,0)	--CODIGO DE GRUPO CONTABLE
---      01 = FRANQUICIAS. ENTRADA	 	 		
---      02 = INCOMING 	 	 		
---      03 = COMERCIOS 	 	 		
---      04 = INCIDENCIAS 	 	 		
---      05 = TITULARES 	 	 		
---      06 = OPERACIONES DIARIAS 	 	 		
---      07 = COMPRA EN CUOTAS 	 	 		
---      08 = IMPAGADOS 	 	 		
---      09 = LIQUIDACION 	 	 		
---      10 = MAESTRO DE RECIBOS 	 	 		
---      11 = OUTGOING 	 	 		
---      12 = FRANQUICIAS. SALIDA	 	 		
,	CODCCN	DECIMAL	(4,0)	--CONCEPTO CONTABLE
,	IMPORTE	DECIMAL	(17,2)	--IMPORTE 
,	CLAMON	DECIMAL	(3,0)	--CLAVE DE MONEDA
,	FECALTA	DATE		--FECHA GRABACION DEL REGISTRO
,	FECCONTA	DATE		--FECHA CONTABLE (AAAA-MM-DD)
,	FECOPER	DATE		--FECHA DE LA OPERACION (AAAA-MM-DD)
--DATOS GENERALES NO OBLIGATORIOS (INFORMAR SI EL PGM DISPONE DE ELLOS)	 	 		
,	IMPORI	DECIMAL	(17,2)	--IMPORTE ORIGINAL DE LA OPERACION
,	CLAMONORI	DECIMAL	(3,0)	--CLAVE MONEDA ORIGINAL
,	CMBAPLIORI	DECIMAL	(9,4)	--CAMBIO APLICADO PASO DE MONEDA
,	IMPEMI	DECIMAL	(17,2)	--IMPORTE RECEPCION DE LA OPERACION
,	CLAMONEMI	DECIMAL	(3,0)	--CLAVE MONEDA EMISOR
,	CMBAPLIEMI	DECIMAL	(9,4)	--CAMBIO APLICADO PASO DE MONEDA EMISOR
,	INDNORCOR	DECIMAL	(1,0)	--INDICADOR DE NORMAL O CORRECTORA:
---      NORMAL	 	 		
---      CORRECTORA	 	 		
,	TIPOFAC	DECIMAL	(4,0)	--TIPO DE FACTURA
,	INDAPLDEBCRE	DECIMAL	(1,0)	--INDICADOR DE OPERATIVIDAD DE LA TARJETA
---      1 – CrEdito	 	 		
---      2 – DEbito	 	 		
---      3 – Mixta	 	 		
---      4- Monedero 	 	 		
---      5- Prepago  banda	 	 		
,	CODACT	DECIMAL	(4,0)	--CODIGO ACTIVIDAD ISO
,	CODCONECO	DECIMAL	(4,0)	--CODIGO DE CONCEPTO ECONOMICO
,	SECOPE	DECIMAL	(12,0)	--SECUENCIA DE LA OPERACION
,	OFIOPE	VARCHAR	(4)	--OFICINA QUE GENERA LA OPERACION
,	IDTERM	VARCHAR	(16)	--IDENTIFICADOR DE TERMINAL
--IDENTIFICADOR DE LA OPERACION (INFORMAR SI EL PGM DISPONE DE ELLOS SEGUN SUBSISTEMA)	 	 		
,	SIAIDCD	VARCHAR	(19)	--CODIGO IDENTIFICACION DE SIA 
,	NUMCINTA	DECIMAL	(17,0)	--NUMERO DE CINTA
,	SECLOTE	DECIMAL	(6,0)	--LOTE DENTRO DE LA CINTA
,	CENTALTA	VARCHAR	(4)	--CENTRO ALTA CUENTA TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	PAN	VARCHAR	(22)	--NUMERO DE TARJETA
,	NUMEXTCTA	DECIMAL	(3,0)	--NUMERO DE EXTRACTO DE CREDITO
,	NUMMOV	DECIMAL	(9,0)	--NUMERO MOVIMIENTO CREDITO O DEBITO
,	NUMOPECUO	DECIMAL	(6,0)	--NUMERO OPERACION EN CUOTAS
,	FECINI	DATE		--FECHA INICIO
,	FECFIN	DATE		--FECHA FIN
,	CODCOM	VARCHAR	(15)	--CODIGO DE COMERCIO
,	CENTALTACOM	VARCHAR	(4)	--ALTA CONTRATO COMERCIO
,	CUENTACOM	VARCHAR	(12)	--CONTRATO COMERCIO
,	NUMEXTCOM	DECIMAL	(3,0)	--NUMERO EXTRACTO COMERCIO
,	NUMMOVEXTCO	DECIMAL	(7,0)	--NUMERO MOVIMIENTO EXTRACTO COMERCIO
,	NUMREFREM	DECIMAL	(10,0)	--NUMERO REFERENCIA REMESA
,	NUMREFFACREM	DECIMAL	(10,0)	--NUMERO REFERENCIA DE LA FACTURA
,	NUMINC	DECIMAL	(9,0)	--NUMERO INCIDENCIA
,	NUMSECREC	DECIMAL	(15,0)	--NUMERO SECUENCIA DE RECIBO
,	NUMSECIMP	DECIMAL	(15,0)	--NUMERO SECUENCIA DE RECIBO IMPAGADO
--DATOS DE TRAMA CONTABLE Y ESTADISTICOS (INFORMAR SI EL PGM DISPONE DE ELLOS. CONTABILIDAD INFORMARA LOS NECESARIOS PARA TRADUCCION CONTABLE)	 	 		
,	CODMAR	DECIMAL	(2,0)	--CODIGO MARCA DE TARJETA
,	INDTIPT	DECIMAL	(2,0)	--INDICADOR TIPO DE TARJETA
,	PRODUCTO	VARCHAR	(2)	--CODIGO DE PRODUCTO
,	SUBPRODU	VARCHAR	(4)	--CODIGO DE SUBPRODUCTO
,	VERTIENTE	VARCHAR	(1)	--INDICADOR DE VERTIENTE
,	CONPROD	VARCHAR	(3)	--CONDICION ECONOMICA
,	TIPFRAN	DECIMAL	(4,0)	--TIPO DE FRANQUICIA
,	CODRAZON	DECIMAL	(4,0)	--CODIGO DE RAZON
,	TIPOREM	VARCHAR	(1)	--TIPO DE REMESA
,	CODESTCTA	DECIMAL	(2,0)	--CODIGO ESTADO DE CUENTA DE TARJETA
,	CODPAIS	DECIMAL	(3,0)	--CODIGO DE PAIS
,	TIPOCLI	VARCHAR	(4)	--TIPO DE CLIENTE
,	IDENTCLI	VARCHAR	(8)	--IDENTIFICADOR DE CLIENTE
,	ORIGENOPE	VARCHAR	(4)	--ORIGEN DE OPERACION
,	PROGRAMA	VARCHAR	(8)	--NOMBRE DE PROGRAMA
--DATOS CONTABLES (SE INFORMARAN EN LOS PROCESOS CONTABLES)	 	 		
,	IMPCON	DECIMAL	(17,2)	--IMPORTE EN MONEDA CONTABLE
,	CLAMONCON	DECIMAL	(3,0)	--CLAVE MONEDA CONTABLE
,	CMBAPLI	DECIMAL	(9,4)	--CAMBIO APLICADO
,	CUENTADEBE	DECIMAL	(6,0)	--CUENTA SAT DEBE
,	CUENTAHABER	DECIMAL	(6,0)	--CUENTA SAT HABER
,	OFIIMPDEB	VARCHAR	(4)	--OFICINA IMPUTACION DEBE
,	OFIIMPHAB	VARCHAR	(4)	--OFICINA IMPUTACION HABER
,	INDNACINT	DECIMAL	(1,0)	--INDICADOR OPERADOR
--0-     NACIONAL	 	 		
--1-     INTERNACIONAL	 	 		
,	NUMOPER	DECIMAL	(10,0)	--NUMERO DE REGISTROS QUE COMPONEN LA TOTALIZACION DE CONCEPTOS
,	SIGNO	VARCHAR	(1)	--SIGNO DEL REGISTRO CONTABLE (SIGNO DEL TIPO DE FACTURA O INDICADOR DE NORMAL / CORRECTORA)
--DATOS DE LINEA	 	 		
,	LINREF	DECIMAL	(8,0)	--REFERENCIA DE TIPO DE LINEA
,	TIPOLIN	VARCHAR	(4)	--TIPO DE LINEA
,	FILLER	VARCHAR	(5)	--
); COMMIT;	 	 		