--- creacion de grupo de usuarios SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'SAT')
BEGIN
CREATE USER SAT 
FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

--- creacion de grupo de usuarios STG_SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'STG_SAT')
BEGIN
CREATE USER STG_SAT 
FORCE PASSWORD CHANGE OFF;
END;
COMMIT;


------------------------------
-- INTERFAZ  CONTABLE
--------------------------------
drop table IF EXISTS SAT.ATCON001;  CREATE TABLE IF NOT EXISTS SAT.ATCON001  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
--INTERFAZ CONTABLE, CONCEPTOS CONTABLES	 	 		
--DATOS GENERALES OBLIGATORIOS	 	 		
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CODGRU	DECIMAL	(2,0)	--CODIGO DE GRUPO CONTABLE
--- 01 = FRANQUICIAS. ENTRADA	 	 		
--- 02 = INCOMING 	 	 		
--- 03 = COMERCIOS 	 	 		
--- 04 = INCIDENCIAS 	 	 		
--- 05 = TITULARES 	 	 		
--- 06 = OPERACIONES DIARIAS 	 	 		
--- 07 = COMPRA EN CUOTAS 	 	 		
--- 08 = IMPAGADOS 	 	 		
--- 09 = LIQUIDACION 	 	 		
--- 10 = MAESTRO DE RECIBOS 	 	 		
--- 11 = OUTGOING 	 	 		
--- 12 = FRANQUICIAS. SALIDA	 	 		
,	CODCCN	DECIMAL	(4,0)	--CONCEPTO CONTABLE
,	IMPORTE	DECIMAL	(17,2)	--IMPORTE 
,	CLAMON	DECIMAL	(3,0)	--CLAVE DE MONEDA
,	FECALTA	DATE		--FECHA GRABACION DEL REGISTRO
,	FECCONTA	DATE		--FECHA CONTABLE (AAAA-MM-DD)
,	FECOPER	DATE		--FECHA DE LA OPERACION (AAAA-MM-DD)
--DATOS GENERALES NO OBLIGATORIOS (INFORMAR SI EL PGM DISPONE DE ELLOS)	 	 		
,	IMPORI	DECIMAL	(17,2)	--IMPORTE ORIGINAL DE LA OPERACION
,	CLAMONORI	DECIMAL	(3,0)	--CLAVE MONEDA ORIGINAL
,	CMBAPLIORI	DECIMAL	(9,4)	--CAMBIO APLICADO PASO DE MONEDA
,	IMPEMI	DECIMAL	(17,2)	--IMPORTE RECEPCION DE LA OPERACION
,	CLAMONEMI	DECIMAL	(3,0)	--CLAVE MONEDA EMISOR
,	CMBAPLIEMI	DECIMAL	(9,4)	--CAMBIO APLICADO PASO DE MONEDA EMISOR
,	INDNORCOR	DECIMAL	(1,0)	--INDICADOR DE NORMAL O CORRECTORA:
--- NORMAL	 	 		
--- CORRECTORA	 	 		
,	TIPOFAC	DECIMAL	(4,0)	--TIPO DE FACTURA
,	INDAPLDEBCRE	DECIMAL	(1,0)	--INDICADOR DE OPERATIVIDAD DE LA TARJETA
--- 1 � CrEdito	 	 		
--- 2 � DEbito	 	 		
--- 3 � Mixta	 	 		
--- 4- Monedero 	 	 		
--- 5- Prepago  banda	 	 		
,	CODACT	DECIMAL	(4,0)	--CODIGO ACTIVIDAD ISO
,	CODCONECO	DECIMAL	(4,0)	--CODIGO DE CONCEPTO ECONOMICO
,	SECOPE	DECIMAL	(12,0)	--SECUENCIA DE LA OPERACION
,	OFIOPE	VARCHAR	(4)	--OFICINA QUE GENERA LA OPERACION
,	IDTERM	VARCHAR	(16)	--IDENTIFICADOR DE TERMINAL
--IDENTIFICADOR DE LA OPERACION (INFORMAR SI EL PGM DISPONE DE ELLOS SEGUN SUBSISTEMA)	 	 		
,	SIAIDCD	VARCHAR	(19)	--CODIGO IDENTIFICACION DE SIA 
,	NUMCINTA	DECIMAL	(17,0)	--NUMERO DE CINTA
,	SECLOTE	DECIMAL	(6,0)	--LOTE DENTRO DE LA CINTA
,	CENTALTA	VARCHAR	(4)	--CENTRO ALTA CUENTA TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	PAN	VARCHAR	(22)	--NUMERO DE TARJETA
,	NUMEXTCTA	DECIMAL	(3,0)	--NUMERO DE EXTRACTO DE CREDITO
,	NUMMOV	DECIMAL	(9,0)	--NUMERO MOVIMIENTO CREDITO O DEBITO
,	NUMOPECUO	DECIMAL	(6,0)	--NUMERO OPERACION EN CUOTAS
,	FECINI	DATE		--FECHA INICIO
,	FECFIN	DATE		--FECHA FIN
,	CODCOM	VARCHAR	(15)	--CODIGO DE COMERCIO
,	CENTALTACOM	VARCHAR	(4)	--ALTA CONTRATO COMERCIO
,	CUENTACOM	VARCHAR	(12)	--CONTRATO COMERCIO
,	NUMEXTCOM	DECIMAL	(3,0)	--NUMERO EXTRACTO COMERCIO
,	NUMMOVEXTCO	DECIMAL	(7,0)	--NUMERO MOVIMIENTO EXTRACTO COMERCIO
,	NUMREFREM	DECIMAL	(10,0)	--NUMERO REFERENCIA REMESA
,	NUMREFFACREM	DECIMAL	(10,0)	--NUMERO REFERENCIA DE LA FACTURA
,	NUMINC	DECIMAL	(9,0)	--NUMERO INCIDENCIA
,	NUMSECREC	DECIMAL	(15,0)	--NUMERO SECUENCIA DE RECIBO
,	NUMSECIMP	DECIMAL	(15,0)	--NUMERO SECUENCIA DE RECIBO IMPAGADO
--DATOS DE TRAMA CONTABLE Y ESTADISTICOS (INFORMAR SI EL PGM DISPONE DE ELLOS. CONTABILIDAD INFORMARA LOS NECESARIOS PARA TRADUCCION CONTABLE)	 	 		
,	CODMAR	DECIMAL	(2,0)	--CODIGO MARCA DE TARJETA
,	INDTIPT	DECIMAL	(2,0)	--INDICADOR TIPO DE TARJETA
,	PRODUCTO	VARCHAR	(2)	--CODIGO DE PRODUCTO
,	SUBPRODU	VARCHAR	(4)	--CODIGO DE SUBPRODUCTO
,	VERTIENTE	VARCHAR	(1)	--INDICADOR DE VERTIENTE
,	CONPROD	VARCHAR	(3)	--CONDICION ECONOMICA
,	TIPFRAN	DECIMAL	(4,0)	--TIPO DE FRANQUICIA
,	CODRAZON	DECIMAL	(4,0)	--CODIGO DE RAZON
,	TIPOREM	VARCHAR	(1)	--TIPO DE REMESA
,	CODESTCTA	DECIMAL	(2,0)	--CODIGO ESTADO DE CUENTA DE TARJETA
,	CODPAIS	DECIMAL	(3,0)	--CODIGO DE PAIS
,	TIPOCLI	VARCHAR	(4)	--TIPO DE CLIENTE
,	IDENTCLI	VARCHAR	(8)	--IDENTIFICADOR DE CLIENTE
,	ORIGENOPE	VARCHAR	(4)	--ORIGEN DE OPERACION
,	PROGRAMA	VARCHAR	(8)	--NOMBRE DE PROGRAMA
--DATOS CONTABLES (SE INFORMARAN EN LOS PROCESOS CONTABLES)	 	 		
,	IMPCON	DECIMAL	(17,2)	--IMPORTE EN MONEDA CONTABLE
,	CLAMONCON	DECIMAL	(3,0)	--CLAVE MONEDA CONTABLE
,	CMBAPLI	DECIMAL	(9,4)	--CAMBIO APLICADO
,	CUENTADEBE	DECIMAL	(6,0)	--CUENTA SAT DEBE
,	CUENTAHABER	DECIMAL	(6,0)	--CUENTA SAT HABER
,	OFIIMPDEB	VARCHAR	(4)	--OFICINA IMPUTACION DEBE
,	OFIIMPHAB	VARCHAR	(4)	--OFICINA IMPUTACION HABER
,	INDNACINT	DECIMAL	(1,0)	--INDICADOR OPERADOR
--0-NACIONAL	 	 		
--1-INTERNACIONAL	 	 		
,	NUMOPER	DECIMAL	(10,0)	--NUMERO DE REGISTROS QUE COMPONEN LA TOTALIZACION DE CONCEPTOS
,	SIGNO	VARCHAR	(1)	--SIGNO DEL REGISTRO CONTABLE (SIGNO DEL TIPO DE FACTURA O INDICADOR DE NORMAL / CORRECTORA)
--DATOS DE LINEA	 	 		
,	LINREF	DECIMAL	(8,0)	--REFERENCIA DE TIPO DE LINEA
,	TIPOLIN	VARCHAR	(4)	--TIPO DE LINEA
,	FILLER	VARCHAR	(5)	--
); COMMIT;	 	 		
drop table IF EXISTS SAT.PCCON001;  CREATE TABLE IF NOT EXISTS SAT.PCCON001  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
--INTERFAZ CONTABLE, APUNTES CONTABLES	 	 		
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CODGRU	DECIMAL	(2,0)	--CODIGO DE GRUPO CONTABLE
--- 01 = FRANQUICIAS. ENTRADA	 	 		
--- 02 = INCOMING 	 	 		
--- 03 = COMERCIOS 	 	 		
--- 04 = INCIDENCIAS 	 	 		
--- 05 = TITULARES 	 	 		
--- 06 = OPERACIONES DIARIAS 	 	 		
--- 07 = COMPRA EN CUOTAS 	 	 		
--- 08 = IMPAGADOS 	 	 		
--- 09 = LIQUIDACION 	 	 		
--- 10 = MAESTRO DE RECIBOS 	 	 		
--- 11 = OUTGOING 	 	 		
--- 12 = FRANQUICIAS. SALIDA	 	 		
,	CODCCN	DECIMAL	(4,0)	--CONCEPTO CONTABLE
,	IMPORTE	DECIMAL	(17,2)	--IMPORTE 
,	CLAMON	DECIMAL	(3,0)	--CLAVE DE MONEDA
,	FECALTA	DATE		--FECHA GRABACION DEL REGISTRO
,	FECCONTA	DATE		--FECHA CONTABLE (AAAA-MM-DD)
,	FECOPER	DATE		--FECHA DE LA OPERACION (AAAA-MM-DD)
--	 	 		
,	IMPORI	DECIMAL	(17,2)	--IMPORTE ORIGINAL DE LA OPERACION
,	CLAMONORI	DECIMAL	(3,0)	--CLAVE MONEDA ORIGINAL
,	CMBAPLIORI	DECIMAL	(9,4)	--CAMBIO APLICADO PASO DE MONEDA
,	IMPEMI	DECIMAL	(17,2)	--IMPORTE RECEPCION DE LA OPERACION
,	CLAMONEMI	DECIMAL	(3,0)	--CLAVE MONEDA EMISOR
,	CMBAPLIEMI	DECIMAL	(9,4)	--CAMBIO APLICADO PASO DE MONEDA EMISOR
,	INDNORCOR	DECIMAL	(1,0)	--INDICADOR DE NORMAL O CORRECTORA:
--- NORMAL	 	 		
--- CORRECTORA	 	 		
,	TIPOFAC	DECIMAL	(4,0)	--TIPO DE FACTURA
,	INDAPLDEBCRE	DECIMAL	(1,0)	--INDICADOR DE OPERATIVIDAD DE LA TARJETA
--- 1- CREDITO	 	 		
--- 2- DEBITO	 	 		
--- 3- CHIP	 	 		
,	CODACT	DECIMAL	(4,0)	--CODIGO ACTIVIDAD ISO
,	CODCONECO	DECIMAL	(4,0)	--CODIGO DE CONCEPTO ECONOMICO
,	SECOPE	DECIMAL	(12,0)	--SECUENCIA DE LA OPERACION
,	OFIOPE	VARCHAR	(4)	--OFICINA QUE GENERA LA OPERACION
,	IDTERM	VARCHAR	(16)	--IDENTIFICADOR DE TERMINAL
--IDENTIFICADOR DE LA OPERACION (INFORMAR SI EL PGM DISPONE DE ELLOS SEGUN SUBSISTEMA)	 	 		
,	SIAIDCD	VARCHAR	(19)	--CODIGO IDENTIFICACION DE SIA 
,	NUMCINTA	DECIMAL	(17,0)	--NUMERO DE CINTA
,	SECLOTE	DECIMAL	(6,0)	--LOTE DENTRO DE LA CINTA
,	CENTALTA	VARCHAR	(4)	--CENTRO ALTA CUENTA TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	PAN	VARCHAR	(22)	--NUMERO DE TARJETA
,	NUMEXTCTA	DECIMAL	(3,0)	--NUMERO DE EXTRACTO DE CREDITO
,	NUMMOV	DECIMAL	(9,0)	--NUMERO MOVIMIENTO CREDITO O DEBITO
,	NUMOPECUO	DECIMAL	(6,0)	--NUMERO OPERACION EN CUOTAS
,	FECINI	DATE		--FECHA INICIO
,	FECFIN	DATE		--FECHA FIN
,	CODCOM	VARCHAR	(15)	--CODIGO DE COMERCIO
,	CENTALTACOM	VARCHAR	(4)	--ALTA CONTRATO COMERCIO
,	CUENTACOM	VARCHAR	(12)	--CONTRATO COMERCIO
,	NUMEXTCOM	DECIMAL	(3,0)	--NUMERO EXTRACTO COMERCIO
,	NUMMOVEXTCO	DECIMAL	(7,0)	--NUMERO MOVIMIENTO EXTRACTO COMERCIO
,	NUMREFREM	DECIMAL	(10,0)	--NUMERO REFERENCIA REMESA
,	NUMREFFACREM	DECIMAL	(10,0)	--NUMERO REFERENCIA DE LA FACTURA
,	NUMINC	DECIMAL	(9,0)	--NUMERO INCIDENCIA
,	NUMSECREC	DECIMAL	(15,0)	--NUMERO SECUENCIA DE RECIBO
,	NUMSECIMP	DECIMAL	(15,0)	--NUMERO SECUENCIA DE RECIBO IMPAGADO
--DATOS DE TRAMA CONTABLE Y ESTADISTICOS (INFORMAR SI EL PGM DISPONE DE ELLOS. CONTABILIDAD INFORMARA LOS NECESARIOS PARA TRADUCCION CONTABLE)	 	 		
,	CODMAR	DECIMAL	(2,0)	--CODIGO MARCA DE TARJETA
,	INDTIPT	DECIMAL	(2,0)	--INDICADOR TIPO DE TARJETA
,	PRODUCTO	VARCHAR	(2)	--CODIGO DE PRODUCTO
,	SUBPRODU	VARCHAR	(4)	--CODIGO DE SUBPRODUCTO
,	VERTIENTE	VARCHAR	(1)	--INDICADOR DE VERTIENTE
,	CONPROD	VARCHAR	(3)	--CONDICION ECONOMICA
,	TIPFRAN	DECIMAL	(4,0)	--TIPO DE FRANQUICIA
,	CODRAZON	DECIMAL	(4,0)	--CODIGO DE RAZON
,	TIPOREM	VARCHAR	(1)	--TIPO DE REMESA
,	CODESTCTA	DECIMAL	(2,0)	--CODIGO ESTADO DE CUENTA DE TARJETA
,	CODPAIS	DECIMAL	(3,0)	--CODIGO DE PAIS
,	TIPOCLI	VARCHAR	(4)	--TIPO DE CLIENTE
,	IDENTCLI	VARCHAR	(8)	--IDENTIFICADOR DE CLIENTE
,	ORIGENOPE	VARCHAR	(4)	--ORIGEN DE OPERACION
,	PROGRAMA	VARCHAR	(8)	--NOMBRE DE PROGRAMA
--DATOS CONTABLES (SE INFORMARAN EN LOS PROCESOS CONTABLES)	 	 		
,	IMPCON	DECIMAL	(17,2)	--IMPORTE EN MONEDA CONTABLE
,	CLAMONCON	DECIMAL	(3,0)	--CLAVE MONEDA CONTABLE
,	CMBAPLI	DECIMAL	(9,4)	--CAMBIO APLICADO
,	CUENTADEBE	DECIMAL	(6,0)	--CUENTA SAT DEBE
,	CUENTAHABER	DECIMAL	(6,0)	--CUENTA SAT HABER
,	OFIIMPDEB	VARCHAR	(4)	--OFICINA IMPUTACION DEBE
,	OFIIMPHAB	VARCHAR	(4)	--OFICINA IMPUTACION HABER
,	INDNACINT	DECIMAL	(1,0)	--INDICADOR OPERADOR
--0-NACIONAL	 	 		
--1-INTERNACIONAL	 	 		
,	NUMOPER	DECIMAL	(10,0)	--NUMERO DE REGISTROS QUE COMPONEN LA TOTALIZACION DE CONCEPTOS
,	SIGNO	VARCHAR	(1)	--SIGNO DEL REGISTRO CONTABLE (SIGNO DEL TIPO DE FACTURA O INDICADOR DE NORMAL / CORRECTORA)
--DATOS DE LINEA	 	 		
,	LINREF	DECIMAL	(8,0)	--REFERENCIA DE TIPO DE LINEA
,	TIPOLIN	VARCHAR	(4)	--TIPO DE LINEA
,	CODACTEMP	VARCHAR	(6)	--CODIGO DE ACTIVIDAD EMPRESARIAL
,	CTADEBETPMP	DECIMAL	(30,0)	--CUENTA DEBE TPMP
,	CTAHABERTPMP	DECIMAL	(30,0)	--CUENTA HABER TPMP
,	DESCAPUNTE	VARCHAR	(30)	--DESCRIPCION DEL APUNTE
,	CODCONVEN	VARCHAR	(4)	--CODIGO DE CONVENIO
,	FILLER1	VARCHAR	(102)	--ESPACIO DISPONIBLE DEL REGISTRO
); COMMIT;	 	 		

------------------------------
-- STAGE INTERFAZ  CONTABLE
--------------------------------

DROP TABLE IF EXISTS "DWH_ETLS"."ATCON001";
COMMIT;
DROP TABLE IF EXISTS "STG"."ATCON001";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."ATCON001";
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."ATCON001" (
CODENT varchar(4) NULL,
CODGRU decimal(2,0) NULL,
CODCCN decimal(4,0) NULL,
IMPORTE decimal(17,2) NULL,
CLAMON decimal(3,0) NULL,
FECALTA varchar(10) NULL,
FECCONTA varchar(10) NULL,
FECOPER varchar(10) NULL,
IMPORI decimal(17,2) NULL,
CLAMONORI decimal(3,0) NULL,
CMBAPLIORI decimal(9,4) NULL,
IMPEMI decimal(17,2) NULL,
CLAMONEMI decimal(3,0) NULL,
CMBAPLIEMI decimal(9,4) NULL,
INDNORCOR decimal(1,0) NULL,
TIPOFAC decimal(4,0) NULL,
INDAPLDEBCRE decimal(1,0) NULL,
CODACT decimal(4,0) NULL,
CODCONECO decimal(4,0) NULL,
SECOPE decimal(12,0) NULL,
OFIOPE varchar(4) NULL,
IDTERM varchar(16) NULL,
SIAIDCD varchar(19) NULL,
NUMCINTA decimal(17,0) NULL,
SECLOTE decimal(6,0) NULL,
CENTALTA varchar(4) NULL,
CUENTA varchar(12) NULL,
PAN varchar(22) NULL,
NUMEXTCTA decimal(3,0) NULL,
NUMMOV decimal(9,0) NULL,
NUMOPECUO decimal(6,0) NULL,
FECINI varchar(10) NULL,
FECFIN varchar(10) NULL,
CODCOM  varchar(15) NULL,
CENTALTACOM varchar(4) NULL,
CUENTACOM varchar(12) NULL,
NUMEXTCOM decimal(3,0) NULL,
NUMMOVEXTCO decimal(7,0) NULL,
NUMREFREM decimal(10,0) NULL,
NUMREFFACREM decimal(10,0) NULL,
NUMINC decimal(9,0) NULL,
NUMSECREC decimal(15,0) NULL,
NUMSECIMP decimal(15,0) NULL,
CODMAR decimal(2,0) NULL,
INDTIPT decimal(2,0) NULL,
PRODUCTO varchar(2) NULL,
SUBPRODU varchar(4) NULL,
VERTIENTE varchar(1) NULL,
CONPROD varchar(3) NULL,
TIPFRAN decimal(4,0) NULL,
CODRAZON decimal(4,0) NULL,
TIPOREM varchar(1) NULL,
CODESTCTA decimal(2,0) NULL,
CODPAIS decimal(3,0) NULL,
TIPOCLI varchar(4) NULL,
IDENTCLI varchar(8) NULL,
ORIGENOPE varchar(4) NULL,
PROGRAMA varchar(8) NULL,
IMPCON decimal(17,2) NULL,
CLAMONCON decimal(3,0) NULL,
CMBAPLI decimal(9,4) NULL,
CUENTADEBE decimal(6,0) NULL,
CUENTAHABER decimal(6,0) NULL,
OFIIMPDEB varchar(4) NULL,
OFIIMPHAB varchar(4) NULL,
INDNACINT decimal(1,0) NULL,
NUMOPER decimal(10,0) NULL,
SIGNO varchar(1) NULL,
LINREF decimal(8,0) NULL,
TIPOLIN varchar(4) NULL,
FILLER_0001 varchar(5) NULL
); COMMIT;

DROP TABLE IF EXISTS "DWH_ETLS"."PCCON001";
COMMIT;
DROP TABLE IF EXISTS "STG"."PCCON001";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PCCON001";
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."PCCON001" (
CODENT  varchar(4) NULL,
CODGRU  decimal(2,0) NULL,
CODCCN  decimal(4,0) NULL,
IMPORTE  decimal(17,2) NULL,
CLAMON  decimal(3,0) NULL,
FECALTA  varchar(10) NULL,
FECCONTA  varchar(10) NULL,
FECOPER  varchar(10) NULL,
IMPORI  decimal(17,2) NULL,
CLAMONORI  decimal(3,0) NULL,
CMBAPLIORI  decimal(9,4) NULL,
IMPEMI  decimal(17,2) NULL,
CLAMONEMI  decimal(3,0) NULL,
CMBAPLIEMI  decimal(9,4) NULL,
INDNORCOR  decimal(1,0) NULL,
TIPOFAC  decimal(4,0) NULL,
INDAPLDEBCRE  decimal(1,0) NULL,
CODACT  decimal(4,0) NULL,
CODCONECO  decimal(4,0) NULL,
SECOPE  decimal(12,0) NULL,
OFIOPE  varchar(4) NULL,
IDTERM  varchar(16) NULL,
SIAIDCD  varchar(19) NULL,
NUMCINTA  decimal(17,0) NULL,
SECLOTE  decimal(6,0) NULL,
CENTALTA  varchar(4) NULL,
CUENTA  varchar(12) NULL,
PAN  varchar(22) NULL,
NUMEXTCTA  decimal(3,0) NULL,
NUMMOV  decimal(9,0) NULL,
NUMOPECUO  decimal(6,0) NULL,
FECINI  varchar(10) NULL,
FECFIN  varchar(10) NULL,
CODCOM  varchar(15) NULL,
CENTALTACOM  varchar(4) NULL,
CUENTACOM  varchar(12) NULL,
NUMEXTCOM  decimal(3,0) NULL,
NUMMOVEXTCO  decimal(7,0) NULL,
NUMREFREM  decimal(10,0) NULL,
NUMREFFACREM  decimal(10,0) NULL,
NUMINC  decimal(9,0) NULL,
NUMSECREC  decimal(15,0) NULL,
NUMSECIMP  decimal(15,0) NULL,
CODMAR  decimal(2,0) NULL,
INDTIPT  decimal(2,0) NULL,
PRODUCTO  varchar(2) NULL,
SUBPRODU  varchar(4) NULL,
VERTIENTE  varchar(1) NULL,
CONPROD  varchar(3) NULL,
TIPFRAN  decimal(4,0) NULL,
CODRAZON  decimal(4,0) NULL,
TIPOREM  varchar(1) NULL,
CODESTCTA  decimal(2,0) NULL,
CODPAIS  decimal(3,0) NULL,
TIPOCLI  varchar(4) NULL,
IDENTCLI  varchar(8) NULL,
ORIGENOPE  varchar(4) NULL,
PROGRAMA  varchar(8) NULL,
IMPCON  decimal(17,2) NULL,
CLAMONCON  decimal(3,0) NULL,
CMBAPLI  decimal(9,4) NULL,
CUENTADEBE  decimal(6,0) NULL,
CUENTAHABER  decimal(6,0) NULL,
OFIIMPDEB  varchar(4) NULL,
OFIIMPHAB  varchar(4) NULL,
INDNACINT  decimal(1,0) NULL,
NUMOPER  decimal(10,0) NULL,
SIGNO  varchar(1) NULL,
LINREF  decimal(8,0) NULL,
TIPOLIN  varchar(4) NULL,
CODACTEMP  varchar(6) NULL,
CTADEBETPMP  decimal(30,0) NULL,
CTAHABERTPMP  decimal(30,0) NULL,
DESCAPUNTE  varchar(30) NULL,
CODCONVEN  varchar(4) NULL,
FILLER1  varchar(102) NULL
); commit;

------------------------------------------------
---- CONTROL DE VERSION ------------------------
------------------------------------------------
create table IF NOT EXISTS CNF.VERSION_OBJETOS (
 NOMBRE_MALLA varchar(100)
,OBJECT_NAME varchar(100)
,OBJECT_USER varchar(20)
,VERSION_COMMIT VARCHAR(100)
,VERSION_CODE VARCHAR(20)
,VERSION_DATE DATETIME
,CRDATE DATETIME null default getdate()
,CRUSER varchar(20) null default user_name()
)
;
COMMIT;

declare 
 @NOMBRE_MALLA varchar(100)
,@OBJECT_NAME varchar(100)
,@OBJECT_USER varchar(20)
,@VERSION_COMMIT VARCHAR(100)
,@VERSION_CODE VARCHAR(20)
,@VERSION_DATE DATETIME 
,@CRDATE DATETIME

select 
 @NOMBRE_MALLA = 'MPJ15005'
,@OBJECT_NAME = 'ATCON001'
,@OBJECT_USER = 'SAT'
,@VERSION_COMMIT = '24181be4a0e9b5069d6c3f3c9a6ffc1d74e5b246'
,@VERSION_CODE = '24181be'
,@VERSION_DATE = 'February 19, 2019 9:26:44 AM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @NOMBRE_MALLA = 'PCJ15015'
,@OBJECT_NAME = 'PCCON001'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @NOMBRE_MALLA = 'MPJ15005'
,@OBJECT_NAME = 'ATCON001'
,@OBJECT_USER = 'STG_SAT'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @NOMBRE_MALLA = 'PCJ15015'
,@OBJECT_NAME = 'PCCON001'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

COMMIT;