drop table IF EXISTS SAT.PTOPEDI1;  CREATE TABLE IF NOT EXISTS SAT.PTOPEDI1  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	INDDEBCRE	DECIMAL	(1,0)	--INDICADOR DE DEBITO O CREDITO:
--1 – CREDITO.	 	 		
--2 – DEBITO.	 	 		
--6 - PREPAGO.	 	 		
,	TIPMOV	VARCHAR	(1)	--1: TIPO MOVIMIENTO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	CLAMON	DECIMAL	(3,0)	--CLAVE DE MONEDA
,	INDNORCOR	DECIMAL	(1,0)	--INDICADOR DE NORMAL O CORRECTORA
---        0 – NORMAL	 	 		
---        1 – CORRECTORA	 	 		
,	TIPOFAC	DECIMAL	(4,0)	--TIPO DE FACTURA
,	DESTIPFAC	VARCHAR	(30)	--DESCRIPCION TIPO DE FACTURA
,	SIGNOFAC	VARCHAR	(1)	--SIGNO DE LA FACTURA
,	TIPOFACSIST	DECIMAL	(4,0)	--TIPO DE FACTURA DE SISTEMA
,	INFACINF	VARCHAR	(1)	--INDICADOR DE FACTURA INFORMATIVA (S/N)
,	FECFAC	DATE		--FECHA DE LA FACTURA
,	NUMREFFAC	VARCHAR	(23)	--NUMERO REFERENCIA FACTURA
,	PAN	VARCHAR	(22)	--PAN DE LA TARJETA QUE REALIZO LA OPERACION
,	CLAMONDIV	DECIMAL	(3,0)	--CODIGO DE MONEDA DE LA OPERACION ORIGINAL O DIVISA
,	IMPDIV	DECIMAL	(17,2)	--IMPORTE EN DIVISA ORIGINAL
,	IMPFAC	DECIMAL	(17,2)	--IMPORTE DE LA FACTURA
,	CMBAPLI	DECIMAL	(9,4)	--FACTOR DE CAMBIO APLICADO (SOLO TIENE SENTIDO PARA OPERACIONES EN EXTRANJERO)
,	NUMAUT	VARCHAR	(6)	--NUMERO DE AUTORIZACION
,	CODCOM	VARCHAR	(15)	--CODIGO DE COMERCIO 
,	NOMCOMRED	VARCHAR	(27)	--NOMBRE COMERCIO REDUCIDO
,	CODACT	DECIMAL	(4,0)	--CODIGO DE ACTIVIDAD
,	IMPLIQ	DECIMAL	(17,2)	--IMPORTE DE LIQUIDACION DE LA OPERACION CON EL INTERCAMBIO
,	CLAMONLIQ	DECIMAL	(3,0)	--CODIGO DE MONEDA DE LIQUIDACION CON EL INTERCAMBIO
,	IMPIMPTO	DECIMAL	(17,2)	--IMPORTE DE IMPUESTO
,	FECPROCES	DATE		--FECHA DE PROCESO O ENTRADA DE LA OPERACION AL SISTEMA
,	CODPAIS	DECIMAL	(3,0)	--CODIGO DEL PAIS 
,	NOMPOB	VARCHAR	(26)	--POBLACION DONDE SE REALIZO LA OPERACION
,	FECCONTA	DATE		--FECHA CONTABLE OPERACION
,	ORIGENOPE	VARCHAR	(4)	--ORIGEN OPERACION (VER VALORES DEL CAMPO ORIGEN)
,	TIPFRAN	DECIMAL	(4,0)	--TIPO DE FRANQUICIA
,	SECOPE	DECIMAL	(12,0)	--SECUENCIA DE OPERACION DENTRO DE LA FRANQUICIA O RED
,	NUMSECREC	DECIMAL	(15,0)	--NUMERO DE SECUENCIA EN EL MAESTRO DE RECIBOS (SOLO PARA MOVIMIENTOS DE PAGO)
,	SESIONRED	VARCHAR	(12)	--SESION DE LA RED
,	SIAIDCD	VARCHAR	(19)	--CODIGO DE IDENTIFICACION SIA. ESTA COMPUESTO DE LA SESION DE SIA Y DEL IDENTIFICADOR DEL MENSAJE.
,	CALFRAUDE	VARCHAR	(3)	--CALIFICACION DE FRAUDE POR LYNX
,	IDENTCLI	VARCHAR	(8)	--NUMERO UNICO DE PERSONA
,	INDINCEST	VARCHAR	(1)	--INDICADOR DE INCIDENCIA EN ESTUDIO
---        ‘S’ – SI 	 	 		
---        ‘N’ – NO 	 	 		
--LOS DATOS SIGUIENTES SON SOLO PARA CREDITO	 	 		
,	TIPDOCPAG	DECIMAL	(2,0)	--TIPO DE DOCUMENTO PARA MOVIMIENTOS DE PAGO (PARA MOVIMIENTOS DE DEBITO IRA A CEROS)
,	REFDOCPAG	VARCHAR	(20)	--REFERENCIA DEL DOCUMENTO PARA MOVIMIENTOS DE PAGO (PARA MOVIMIENTOS DE DEBITO IRA A BLANCOS)
,	IMPAMORT	DECIMAL	(17,2)	--IMPORTE AMORTIZADO (SOLO VENDRA INFORMADO PARA MOVIMIENTOS DE CREDITO, PARA DEBITO VENDRA A BLANCOS)
,	NUMMOVEXT	DECIMAL	(7,0)	--NUMERO DE MOVIMIENTO EN EL EXTRACTO
,	NUMEXTCTA	DECIMAL	(3,0)	--NUMERO DE EXTRACTO
,	FECLIQ	DATE		--FECHA DE LIQUIDACION
,	INDMOVANU	DECIMAL	(1,0)	--INDICADOR DE MOVIMIENTO ANULADO
---        0 – NORMAL 	 	 		
---        1 – ANULADO 	 	 		
,	INDRET	DECIMAL	(1,0)	--INDICADOR DE MOVIMIENTO RETENIDO
---        0 – NORMAL 	 	 		
---        1 – RETENIDO 	 	 		
,	INDMOVEXT	DECIMAL	(1,0)	--INDICADOR DE MOVIMIENTO EXTRACTADO
---        0 – PENDIENTE	 	 		
---        1 – EXTRACTADO	 	 		
,	CODTIPC	VARCHAR	(4)	--CODIGO DE TIPO DE COMPRA EN CUOTAS
,	TOTCUOTAS	DECIMAL	(9,0)	--NUMERO TOTAL DE CUOTAS
,	PORINT	DECIMAL	(7,4)	--PORCENTAJE DE INTERES APLICADO
,	NUMOPECUO	DECIMAL	(6,0)	--NUMERO DE OPERACION EN COMPRA EN CUOTAS
,	IMPCUOTA	DECIMAL	(17,2)	--IMPORTE DE LA CUOTA
,	LINREF	DECIMAL	(8,0)	--LINEA DE REFERENCIA DEL MOVIMIENTO
,	FORPAGO	DECIMAL	(2,0)	--FORMA DE PAGO DE LA OPERACION
--LOS DATOS SIGUIENTES SON SOLO PARA DEBITO	 	 		
,	NUMMOVDEB	DECIMAL	(9,0)	--NUMERO DE MOVIMIENTO DE DEBITO
,	FILLER1	VARCHAR	(373)	--
); COMMIT;	 	 		