drop table IF EXISTS SAT.PTCEDIA1;  CREATE TABLE IF NOT EXISTS SAT.PTCEDIA1  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	INDDEBCRE	DECIMAL	(1,0)	--INDICADOR DE DEBITO O CREDITO:
--1 – CREDITO.	 	 		
--2 – DEBITO.	 	 		
--6 - PREPAGO.	 	 		
,	TIPMOV	VARCHAR	(1)	--2: TIPO CONCEPTO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	CLAMON	DECIMAL	(3,0)	--CLAVE DE MONEDA
,	CODCONECO	DECIMAL	(4,0)	--CODIGO DE CONCEPTO ECONOMICO
,	DESCONECO	VARCHAR	(30)	--DESCRIPCION DEL CONCEPTO ECONOMICO
,	SIGNOCE	VARCHAR	(1)	--SIGNO FINAL ENTRE EL SIGNO DE LA FACTURA Y EL SIGNO DEL CONCEPTO.
,	TIPIMP	DECIMAL	(2,0)	--TIPO DE IMPORTE
,	IMPAPLECO	DECIMAL	(17,2)	--IMPORTE SOBRE EL QUE SE APLICA EL CONCEPTO ECONOMICO
,	IMPBRUECO	DECIMAL	(17,2)	--IMPORTE BRUTO CALCULADO POR EL CONCEPTO ECONOMICO
,	IMPBONECO	DECIMAL	(17,2)	--IMPORTE BONIFICADO SOBRE EL  CALCULO DEL CONCEPTO ECONOMICO
,	IMPIMPTO	DECIMAL	(17,2)	--IMPORTE DE IMPUESTO
--LOS DATOS SIGUIENTES SON SOLO PARA CREDITO	 	 		
,	NUMEXTCTA	DECIMAL	(3,0)	--NUMERO DE EXTRACTO
,	NUMMOVEXT	DECIMAL	(7,0)	--NUMERO DE MOVIMIENTO EN EL EXTRACTO
,	PORINT	DECIMAL	(7,4)	--PORCENTAJE DE INTERES APLCIADO
--DATO DE DEBITO	 	 		
,	NUMMOVDEB	DECIMAL	(9,0)	--NUMERO DE MOVIMIENTO DE DEBITO
,	FILLER1	VARCHAR	(724)	--NUMERO DE MOVIMIENTO DE DEBITO
); COMMIT;	 	 		