DROP TABLE IF EXISTS "DWH_ETLS"."PTCEDIA1";
COMMIT;
DROP TABLE IF EXISTS "STG"."PTCEDIA1";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PTCEDIA1";
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."PTCEDIA1" (	
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"INDDEBCRE" DECIMAL(1,0) NULL ,
	"TIPMOV" VARCHAR(1) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"CLAMON" DECIMAL(3,0) NULL ,
	"CODCONECO" DECIMAL(4,0) NULL ,
	"DESCONECO" VARCHAR(30) NULL ,
	"SIGNOCE" VARCHAR(1) NULL ,
	"TIPIMP" DECIMAL(2,0) NULL ,
	"IMPAPLECO" DECIMAL(17,2) NULL ,
	"IMPBRUECO" DECIMAL(17,2) NULL ,
	"IMPBONECO" DECIMAL(17,2) NULL ,
	"IMPIMPTO" DECIMAL(17,2) NULL ,
	"NUMEXTCTA" DECIMAL(3,0) NULL ,
	"NUMMOVEXT" DECIMAL(7,0) NULL ,
	"PORINT" DECIMAL(7,4) NULL ,
	"NUMMOVDEB" DECIMAL(9,0) NULL ,
	"FILLER1" VARCHAR(724) NULL 
)  COMMIT;
