IF NOT EXISTS(SELECT 1 FROM "CNF"."CAT_JOBS" WHERE "NOMBRE_JOB" = 'JOB_SENTINEL' AND "NOMBRE_TABLA" = 'SSS_CASO')
BEGIN
  INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") VALUES('JOB_SENTINEL','SSS_CASO',NULL,0);
END
IF NOT EXISTS(SELECT 1 FROM "CNF"."CAT_JOBS" WHERE "NOMBRE_JOB" = 'JOB_SENTINEL' AND "NOMBRE_TABLA" = 'SSS_ESTADO')
BEGIN
  INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") VALUES('JOB_SENTINEL','SSS_ESTADO',NULL,0);
END
COMMIT;

