DECLARE 
 @USUARIO VARCHAR(100)
,@PASSWORD VARCHAR(100)
,@PATH VARCHAR(100)
,@SERVER VARCHAR(100)
,@PUERTO VARCHAR(100)

SELECT 
 @USUARIO   = 'usr_sentinelcr'
,@PASSWORD  = 'Sen12IQ18'
,@PATH      = '/data/SAT/sentinel/'
,@SERVER    = 'SVBCWSQL01DA'
,@PUERTO    = '3341'

IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'U_SEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'U_SEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('U_SEN',@USUARIO);


IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'P_SEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'P_SEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('P_SEN',@PASSWORD);


IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'PATH_SEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'PATH_SEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('PATH_SEN',@PATH);


IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'SERVER_SEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'SERVER_SEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('SERVER_SEN',@SERVER);


IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'PORT_SEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'PORT_SEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('PORT_SEN',@PUERTO);

COMMIT;
