if exists (select 1 from CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_TARJETAS_ADICIONALES')
BEGIN
  DELETE CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_TARJETAS_ADICIONALES'
END
INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") 
VALUES('JOB_CASE_CENTER_TJA','CC_TARJETAS_ADICIONALES',NULL,0);
COMMIT;
