DROP TABLE IF EXISTS "SAT"."PRIORITY_PASS";
COMMIT;
CREATE TABLE IF NOT EXISTS "SAT"."PRIORITY_PASS" (
	"CORRELATIVO" DECIMAL(14,0) NULL ,
	"CONTRATO" DECIMAL(25,0) NULL ,
	"TARJETA" DECIMAL(20,0) NULL ,
	"PRODUCTO" VARCHAR(14) NULL ,
	"SUBPRODUCTO" DECIMAL(14,0) NULL ,
	"FECHABATCH" VARCHAR(13) NULL ,
	"TIPOEMISION" VARCHAR(14) NULL ,
	"CALIDADDEPARTICIPACION" VARCHAR(23) NULL ,
	"MEMBER_ID" DECIMAL(22,0) NULL ,
	"NOMBRE" VARCHAR(30) NULL ,
	"CREACION" VARCHAR(13) NULL ,
	"VENCIMIENTO" VARCHAR(13) NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
); COMMIT;

DROP TABLE IF EXISTS "STG_SAT"."PRIORITY_PASS";
COMMIT;
CREATE TABLE IF NOT EXISTS "STG_SAT"."PRIORITY_PASS" (
	"CORRELATIVO" DECIMAL(14,0) NULL ,
	"CONTRATO" DECIMAL(25,0) NULL ,
	"TARJETA" DECIMAL(20,0) NULL ,
	"PRODUCTO" VARCHAR(14) NULL ,
	"SUBPRODUCTO" DECIMAL(14,0) NULL ,
	"FECHABATCH" VARCHAR(13) NULL ,
	"TIPOEMISION" VARCHAR(14) NULL ,
	"CALIDADDEPARTICIPACION" VARCHAR(23) NULL ,
	"MEMBER_ID" DECIMAL(22,0) NULL ,
	"NOMBRE" VARCHAR(30) NULL ,
	"CREACION" VARCHAR(13) NULL ,
	"VENCIMIENTO" VARCHAR(13) NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
); COMMIT;

------------------------------------------------
---- CONTROL DE VERSION ------------------------
------------------------------------------------
create table IF NOT EXISTS CNF.VERSION_OBJETOS (
 NOMBRE_MALLA varchar(100)
,OBJECT_NAME varchar(100)
,OBJECT_USER varchar(20)
,VERSION_COMMIT VARCHAR(100)
,VERSION_CODE VARCHAR(20)
,VERSION_DATE DATETIME
,CRDATE DATETIME null default getdate()
,CRUSER varchar(20) null default user_name()
)
;
COMMIT;

declare 
 @NOMBRE_MALLA varchar(100)
,@OBJECT_NAME varchar(100)
,@OBJECT_USER varchar(20)
,@VERSION_COMMIT VARCHAR(100)
,@VERSION_CODE VARCHAR(20)
,@VERSION_DATE DATETIME 
,@CRDATE DATETIME

select 
 @NOMBRE_MALLA = 'N/A.DATAPREP'
,@OBJECT_NAME = 'PRIORITY_PASS'
,@OBJECT_USER = 'SAT'
,@VERSION_COMMIT = '836b8d4c4cb4b7ae254a733063c067067ebb2ab8'
,@VERSION_CODE = '836b8d4'
,@VERSION_DATE = 'February 18, 2019 2:27:32 PM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @OBJECT_USER = 'STG_SAT'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

COMMIT;

