DROP TABLE IF EXISTS "dbo"."PRIORITY_PASS";
COMMIT;
CREATE TABLE IF NOT EXISTS "dbo"."PRIORITY_PASS" (
	"CORRELATIVO" DECIMAL(14,0) NULL ,
	"CONTRATO" DECIMAL(25,0) NULL ,
	"TARJETA" DECIMAL(20,0) NULL ,
	"PRODUCTO" VARCHAR(14) NULL ,
	"SUBPRODUCTO" DECIMAL(14,0) NULL ,
	"FECHABATCH" VARCHAR(13) NULL ,
	"TIPOEMISION" VARCHAR(14) NULL ,
	"CALIDADDEPARTICIPACION" VARCHAR(23) NULL ,
	"MEMBER_ID" DECIMAL(22,0) NULL ,
	"NOMBRE" VARCHAR(30) NULL ,
	"CREACION" VARCHAR(13) NULL ,
	"VENCIMIENTO" VARCHAR(13) NULL ,
	"LOAD_DATE" "datetime" NULL  DEFAULT "getdate"()
); COMMIT;
