drop table IF EXISTS "STG_SAT"."TBDETCUO";  

CREATE TABLE IF NOT EXISTS "STG_SAT"."TBDETCUO" (
	"CODENT_D" VARCHAR(4) NULL,
	"NSECFIC_D" DECIMAL(10,0) NULL,
	"TIPOCINTA_D" DECIMAL(2,0) NULL,
	"TIPOREG_D" VARCHAR(1) NULL,
	"FILLER_D" VARCHAR(91) NULL,
	"NUMREGPROC" DECIMAL(12,0) NULL,
	"CODENT" VARCHAR(4) NULL,
	"CENTALTA" VARCHAR(4) NULL,
	"CUENTA" VARCHAR(12) NULL,
	"CLAMON" DECIMAL(3,0) NULL,
	"NUMOPECUO" DECIMAL(6,0) NULL,
	"NUMFINAN" DECIMAL(3,0) NULL,
	"NUMCUOTA" DECIMAL(9,0) NULL,
	"FECPROCUO" VARCHAR(10) NULL,
	"IMPCUOTA" DECIMAL(17,2) NULL,
	"IMPCAPITAL" DECIMAL(17,2) NULL,
	"IMPINTERESES" DECIMAL(17,2) NULL,
	"IMPIMPTO" DECIMAL(17,2) NULL,
	"ESTCUO" DECIMAL(2,0) NULL,
	"FECLIQ" VARCHAR(10) NULL,
	"FECCONTA" VARCHAR(10) NULL,
	"ESTCONT" DECIMAL(1,0) NULL,
	"FILLER_0001" VARCHAR(738) NULL 
) COMMIT;


