DROP TABLE IF EXISTS "DWH_ETLS"."TBDOCPER";
COMMIT;
DROP TABLE IF EXISTS "STG"."TBDOCPER";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."TBDOCPER";
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."TBDOCPER" (
	"CODENT" VARCHAR(4) NULL ,
	"IDENTCLI" VARCHAR(8) NULL ,
	"TIPDOC" VARCHAR(3) NULL ,
	"NUMDOC" VARCHAR(22) NULL ,
	"FECDOC" VARCHAR(10) NULL ,
	"DOCPRIN" VARCHAR(1) NULL ,
	"DOCDUPL" VARCHAR(1) NULL ,
	"FECALTA" VARCHAR(10) NULL ,
	"FECBAJA" VARCHAR(10) NULL ,
	"CODENTUMO" VARCHAR(4) NULL ,
	"CODOFIUMO" VARCHAR(4) NULL ,
	"USUARIOUMO" VARCHAR(8) NULL ,
	"CODTERMUMO" VARCHAR(8) NULL ,
	"CONTCUR" VARCHAR(26) NULL 
)  COMMIT;

