--- creacion de grupo de usuarios SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'SAT')
BEGIN
  CREATE USER SAT 
  FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

--- creacion de grupo de usuarios STG_SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'STG_SAT')
BEGIN
  CREATE USER STG_SAT
  FORCE PASSWORD CHANGE OFF;
END;
COMMIT;
------------------------------
-- INTERFAZ  TITULARES
--------------------------------

drop table IF EXISTS SAT.TBDOCPER;  
CREATE TABLE IF NOT EXISTS SAT.TBDOCPER  (
 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT	VARCHAR	(4)	--Código de entidad
,	IDENTCLI	VARCHAR	(8)	--Número único de persona
,	TIPDOC 	VARCHAR	(3)	--Tipo de documento
,	NUMDOC	VARCHAR	(22)	--Número de documento
,	FECDOC	DATE		--Fecha de vigencia de documento
,	DOCPRIN	VARCHAR	(1)	--Indicador de documento principal
,	DOCDUPL	VARCHAR	(1)	--Indicador de documento duplicado
,	FECALTA	DATE		--Fecha de alta
,	FECBAJA	DATE		--Fecha de baja
,	CODENTUMO	VARCHAR	(4)	--Entidad última modificació
,	CODOFIUMO	VARCHAR	(4)	--Oficina última modificación
,	USUARIOUMO	VARCHAR	(8)	--Usuario última modificación
,	CODTERMUMO	VARCHAR	(8)	--Terminal última modificación
,	CONTCUR	TIMESTAMP		--Control de concurrencia
); COMMIT;	 	 		

DROP TABLE IF EXISTS "DWH_ETLS"."TBDOCPER";
COMMIT;
DROP TABLE IF EXISTS "STG"."TBDOCPER";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."TBDOCPER";
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."TBDOCPER" (
	"CODENT" VARCHAR(4) NULL ,
	"IDENTCLI" VARCHAR(8) NULL ,
	"TIPDOC" VARCHAR(3) NULL ,
	"NUMDOC" VARCHAR(22) NULL ,
	"FECDOC" VARCHAR(10) NULL ,
	"DOCPRIN" VARCHAR(1) NULL ,
	"DOCDUPL" VARCHAR(1) NULL ,
	"FECALTA" VARCHAR(10) NULL ,
	"FECBAJA" VARCHAR(10) NULL ,
	"CODENTUMO" VARCHAR(4) NULL ,
	"CODOFIUMO" VARCHAR(4) NULL ,
	"USUARIOUMO" VARCHAR(8) NULL ,
	"CODTERMUMO" VARCHAR(8) NULL ,
	"CONTCUR" VARCHAR(26) NULL 
)  COMMIT;

------------------------------------------------
---- CONTROL DE VERSION ------------------------
------------------------------------------------
create table IF NOT EXISTS CNF.VERSION_OBJETOS (
 NOMBRE_MALLA varchar(100)
,OBJECT_NAME varchar(100)
,OBJECT_USER varchar(20)
,VERSION_COMMIT VARCHAR(100)
,VERSION_CODE VARCHAR(20)
,VERSION_DATE DATETIME
,CRDATE DATETIME null default getdate()
,CRUSER varchar(20) null default user_name()
)
;
COMMIT;

declare 
 @NOMBRE_MALLA varchar(100)
,@OBJECT_NAME varchar(100)
,@OBJECT_USER varchar(20)
,@VERSION_COMMIT VARCHAR(100)
,@VERSION_CODE VARCHAR(20)
,@VERSION_DATE DATETIME 
,@CRDATE DATETIME

select 
 @NOMBRE_MALLA = 'MPJC8010'
,@OBJECT_NAME = 'TBDOCPER'
,@OBJECT_USER = 'SAT'
,@VERSION_COMMIT = 'd309cc5ada2cafeee01b6e7ac3b49abac029a4c0'
,@VERSION_CODE = 'd309cc5'
,@VERSION_DATE = 'February 19, 2019 9:02:51 AM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @OBJECT_USER = 'STG_SAT'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

COMMIT;