if exists (select 1 from CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_SOLICITUDES_BALCON')
BEGIN
  DELETE CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_SOLICITUDES_BALCON'
END
INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") 
VALUES('JOB_CASE_CENTER_BAL','CC_SOLICITUDES_BALCON',NULL,0);
COMMIT;
