-- SE DEBE CREAR EL SIGUIENTE PARAMETRO
IF NOT EXISTS (SELECT 1 FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH')
insert CNF.PARAMETROS (PARAMETRO, VALOR) SELECT 'FECINISATDWH', '20190301'
-- LA FECHA DEBE SER EL VALOR CON EL QUE SE INICIA A CARGAR EL DWH DE SAT
