-- SE DEBE CREAR EL SIGUIENTE PARAMETRO
IF NOT EXISTS (SELECT 1 FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH')
insert CNF.PARAMETROS (PARAMETRO, VALOR) SELECT 'FECINISATDWH', '20190301'
-- LA FECHA DEBE SER EL VALOR CON EL QUE SE INICIA A CARGAR EL DWH DE SAT
commit;
IF EXISTS (SELECT 1 FROM CNF.PARAMETROS WHERE PARAMETRO = 'INTERIN_ULTFEC_BALANCE_SALDOS_DIARIOS')
BEGIN
  DELETE CNF.PARAMETROS WHERE PARAMETRO = 'INTERIN_ULTFEC_BALANCE_SALDOS_DIARIOS'
END
INSERT CNF.PARAMETROS
(PARAMETRO, VALOR)
SELECT 'INTERIN_ULTFEC_BALANCE_SALDOS_DIARIOS','2019/05/01'
COMMIT;
