drop proc IF EXISTS SAT.SP_BALANCE_SALDOS_DIARIOS;
commit;
create proc SAT.SP_BALANCE_SALDOS_DIARIOS
 @OPERACION CHAR(1) DEFAULT 'V'
,@FECENVIO DATE DEFAULT NULL
,@FECENVIOFIN DATE DEFAULT NULL
as
BEGIN
DECLARE 
 @FECHA_INI DATE
,@FECHA_FIN DATE

SELECT @OPERACION = UPPER(@OPERACION)
IF @OPERACION NOT IN ('V','C','L','G','B') SELECT @OPERACION = 'V'
-- TIPOS DE OPERACION:
-- V: LEER LOS RESULTADOS DE LAS TABLAS BASE. LOS RESULTADOS NO SE ALMACENAN
--     SE LEE DE LAS TABLAS DIRECTAMENTE Y EL RESULTADO SE DESPLIEGA. 
--     DEPENDE DE LOS PARAMETROS DE FECHAS, SI NO SE ENVIAN LEE TODAS LAS FECHAS
-- C: CREAR LA ESTRUCTURA DE LA TABLA. 
--     NO TIENE OUTPUT DE RESULTADO. LA TABLA SE LLAMA TB_BALANCE_SALDOS_DIARIOS
-- L: LEER LOS RESULTADOS DE LA TABLA FIJA TB_BALANCE_SALDOS_DIARIOS. 
--     DEPENDE DE LOS PARAMETROS DE FECHAS, SI NO SE ENVIAN LEE TODAS LAS FECHAS
-- G: BORRA Y GRABA NUEVAMENTE EL LA TABLA TB_BALANCE_SALDOS_DIARIOS. SI NO EXISTE LA CREA
-- B: BORRA DE LA TABLA TB_BALANCE_SALDOS_DIARIOS. SI LA TABLA NO EXISTE NO DA ERROR
---------------------------------------------------------
-- SE DEBE CREAR EL SIGUIENTE PARAMETRO
--IF NOT EXISTS (SELECT 1 FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH')
--insert CNF.PARAMETROS (PARAMETRO, VALOR) SELECT 'FECINISATDWH', '20190301'
-- LA FECHA DEBE SER EL VALOR CON EL QUE SE INICIA A CARGAR EL DWH DE SAT
---------------------------------------------------------
-- CONDICIONES DE FECHAS:
-- SI NO SE ENVIAN FECHAS SE TOMA INICIAL Y FINAL = 1 ENE 0001
-- SI NO SE ENVIA LA FECHA FINAL, LA FECHA FINAL SE IGUALA A LA FECHA INICIAL
-- SI LA FECHA INICIAL ES MAYOR A LA FINAL, LA FECHA FINAL SE IGUALA A LA FECHA INICIAL
-- SI LA FECHA INICIAL Y FINAL SON NULL (NO SE ENVIAN) SE TOMAN LOS RANGOS DEL 01 ENE 0001 AL 31 DIC 9999
---------------------------------------------------------
/****************
INDICES ASOCIADOS A LA VISTA:
-----------------------------
create HG index if not exists idx_HG_ATINTCAB_FECENVIO on SAT.ATINTCAB(FECENVIO)
CREATE HG index IF NOT EXISTS idx_HG_PARAMETROS_PARAMETRO on CNF.PARAMETROS(PARAMETRO)
CREATE HG index if not exists idx_HG_PCENVPO1_CU_CUENTA on SAT.PCENVPO1_CU(CUENTA)
CREATE HG index if not exists idx_HG_PCENVPO1_CU_SALDISCRE on SAT.PCENVPO1_CU(SALDISCRE)
CREATE HG index if not exists idx_HG_PCENVPO1_CU_IDENTIFICADOR_EJECUCION on SAT.PCENVPO1_CU(IDENTIFICADOR_EJECUCION)
CREATE HG index if not exists idx_HG_PCENVPO1_IC_CUENTA on SAT.PCENVPO1_IC(CUENTA)
CREATE HG index if not exists idx_HG_PCENVPO1_IC_IDENTIFICADOR_EJECUCION on SAT.PCENVPO1_IC(IDENTIFICADOR_EJECUCION)
CREATE HG index if not exists idx_HG_PCENVPO1_MP_CUENTA on SAT.PCENVPO1_MP(CUENTA)
CREATE HG index if not exists idx_HG_PCENVPO1_MP_IDENTIFICADOR_EJECUCION on SAT.PCENVPO1_MP(IDENTIFICADOR_EJECUCION)
CREATE HG index if not exists idx_HG_PCENVPO1_MP_CALPART on SAT.PCENVPO1_MP(CALPART)
CREATE HG index if not exists idx_HG_TBDOCPER_IDENTCLI on SAT.TBDOCPER(IDENTCLI)
CREATE HG index if not exists idx_HG_TBDOCPER_TIPDOC on SAT.TBDOCPER(TIPDOC)
CREATE HG index if not exists idx_HG_TBDOCPER_IDENTIFICADOR_EJECUCION on SAT.TBDOCPER(IDENTIFICADOR_EJECUCION)
*******************/
IF @FECENVIO IS NULL
BEGIN
  SELECT @FECHA_INI = '00010101'
END
ELSE
BEGIN
  SELECT @FECHA_INI = @FECENVIO
END

IF @FECENVIOFIN IS NULL
BEGIN
  IF @FECENVIO IS NULL
    SELECT @FECHA_FIN = '99991231'
  ELSE  
    SELECT @FECHA_FIN = @FECHA_INI
END
ELSE
BEGIN
  SELECT @FECHA_FIN = @FECENVIOFIN
END
IF @FECHA_INI > @FECHA_FIN
  SELECT @FECHA_FIN = @FECHA_INI

if @OPERACION = 'V' --- LEE DATOS DE TABLAS BASE SIN GRABARLOS
BEGIN
SELECT    AT.FECENVIO, 
          A.CODENT_D, 
          A.CUENTA, 
         (
          SELECT DISTINCT B.PAN
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS PAN_TI, 
          (
          SELECT DISTINCT B.CODBLQ 
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS CODBLQ_PAN, 
          (
          SELECT MAX(C.NUMDOC )
            FROM SAT.TBDOCPER C
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = C.IDENTIFICADOR_EJECUCION
             AND A.IDENTCLI = C.IDENTCLI
             AND C.TIPDOC = 'UNI' 
             AND AC.FECENVIO = AT.FECENVIO
          ) 
          AS UNICO, 
          (
          SELECT DISTINCT B.FECCADTAR
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS FECCADTAR,
          (
          SELECT DISTINCT B.MOTBLQ 
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          ) 
          AS MOTBLQ_PAN, 
          A.NUMORDEN, 
          A.FECULTCAR, 
          A.PRODUCTO, 
          A.SUBPRODU, 
          A.LIMCRECTA, 
          A.LIMCRECTATEM, 
          A.FECINITEM, 
          A.FECFINTEM, 
          A.SALAUTCRE, 
          A.SALDISCRE, 
          A.LIMCRECTAC, 
          A.SALAUTCREC, 
          A.SALDISCREC, 
          (CASE  
               WHEN A.LIMCRECTA - A.SALDISCRE  = 0
               THEN 0
               WHEN A.LIMCRECTA - A.SALDISCRE  < 0
               THEN 0
               ELSE  A.LIMCRECTA - A.SALDISCRE
            END) 
                AS SALDISP_C,
          ((SELECT DISTINCT CASE WHEN MAX(AA.SALDISCRE) IS NULL
              THEN 0
              ELSE MAX(AA.SALDISCRE)
              END
             FROM SAT.PCENVPO1_CU AA, SAT.ATINTCAB AAT
            WHERE AA.IDENTIFICADOR_EJECUCION = AAT.IDENTIFICADOR_EJECUCION
              AND AAT.FECENVIO = CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,AT.FECENVIO)) + '/' + CONVERT(VARCHAR,DATEPART(MM,AT.FECENVIO)) + '/1')
              AND AA.CUENTA = A.CUENTA) 
                         +
          (SELECT DISTINCT MAX(ISNULL(AB.SALDISCRE,0))
             FROM SAT.PCENVPO1_CU AB
            WHERE AB.IDENTIFICADOR_EJECUCION = A.IDENTIFICADOR_EJECUCION
              AND AB.CUENTA = A.CUENTA)
           ) / 2 
                AS ANR_BALANCE_MTH, 
          A.FECPROVEN, 
          A.FECULTVEN, 
          A.FECRESOL, 
          A.IDENTCLI, 
          A.CODESTCTA, 
          A.FECULTESTCTA, 
          A.CODCONVEN, 
          A.INDCTAEMP, 
          A.INDDOMCARCRE, 
          A.CTACARGO, 
          A.FORPAGO, 
          A.INDSITCTA, 
          A.COMISIONES, 
          A.INTERESES, 
          A.CAPITAL, 
          A.GRUPOLIQ, 
          A.CODBLQULT, 
          A.IMPMINORIGINAL, 
          A.IMPMINPENDIENTE, 
          (A.IMPMINORIGINAL - A.IMPMINPENDIENTE)  AS IMP_PAGADO, 
          A.MOTBLQ, 
          A.CODVIAJFRE, 
          A.FECALTAVIAJ, 
          A.INDCLICUMM, 
          A.INDCLICUMC, 
          A.FECCLICUM, 
          A.CLASIFRISAT, 
          A.CLASIFRIREG, 
          A.CLASIFRIMDE, 
          A.TASAEFECMAX, 
          (
          SELECT DISTINCT D.TIPOREG
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          ) 
          AS TIPOREG, 
          (
          SELECT DISTINCT D.SITUACION
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS SITUACION, 
          (
          SELECT DISTINCT D.IMPCONT
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMPCONT, 
          (
          SELECT DISTINCT D.IMPAGO
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMPAGO, 
          (
          SELECT DISTINCT D.IMPAPL
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMPAPL, 
          (
          SELECT DISTINCT (D.IMPAGO - D.IMPAPL)
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMP_PENDIENTE, 
          (
          SELECT DISTINCT D.FECULTAPL
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS FECULTAPL, 
          (
          SELECT DISTINCT D.FECENVCOB
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS FECENVCOB, 
          (SELECT MAX(BAL.SALDISCRE) 
             FROM SAT.PCENVPO1_CU BAL
                , SAT.ATINTCAB ATBAL
            where BAL.IDENTIFICADOR_EJECUCION = ATBAL.IDENTIFICADOR_EJECUCION
              AND ATBAL.FECENVIO 
                  BETWEEN (SELECT CONVERT(DATE,VALOR) FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH') 
                      AND AT.FECENVIO 
              AND BAL.CUENTA = A.CUENTA)
          AS BALMASALTO, 
          ( SELECT MAX(ATFEC.FECENVIO) 
              FROM SAT.PCENVPO1_CU FEC
                 , SAT.ATINTCAB ATFEC
             WHERE ATFEC.IDENTIFICADOR_EJECUCION = FEC.IDENTIFICADOR_EJECUCION
               AND FEC.SALDISCRE = (SELECT MAX(BAL.SALDISCRE) 
                                      FROM SAT.PCENVPO1_CU BAL
                                         , SAT.ATINTCAB ATBAL
                                     where BAL.IDENTIFICADOR_EJECUCION = ATBAL.IDENTIFICADOR_EJECUCION
                                       AND ATBAL.FECENVIO 
                                                  BETWEEN (SELECT CONVERT(DATE,VALOR) FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH') 
                                                      AND AT.FECENVIO 
                                       AND BAL.CUENTA = A.CUENTA)
               AND ATFEC.FECENVIO 
                   BETWEEN (SELECT CONVERT(DATE,VALOR) FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH')
                       AND AT.FECENVIO
               AND FEC.CUENTA = A.CUENTA
          )
          AS FECHA_BALMASALTO
--SELECT COUNT(1)
  FROM SAT.ATINTCAB AT
     , SAT.PCENVPO1_CU A
 WHERE A.IDENTIFICADOR_EJECUCION = AT.IDENTIFICADOR_EJECUCION
   AND AT.FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
 RETURN 0
END -- OPERACION = 'V'

if @OPERACION IN ('C','G','L') --  C = CREA ESTRUCTURA DE TABLA FIJA 
--- G = GRABA DATOS EN ESTRUCTURA DE TABLA FIJA.. SI LA TABLA NO EXISTE LA CREA..
--- L = LEE DATOS DE TABLA FIJA.. SI LA TABLA NO EXISTE LA CREA..
BEGIN
  IF EXISTS(SELECT 1 from sysobjects where name = 'TB_BALANCE_SALDOS_DIARIOS' AND user_name(uid) = 'SAT') AND @OPERACION = 'C'
  BEGIN
    return 0
  END
  IF NOT EXISTS(SELECT 1 from sysobjects where name = 'TB_BALANCE_SALDOS_DIARIOS' AND user_name(uid) = 'SAT')
  BEGIN
SELECT    AT.FECENVIO, 
          A.CODENT_D, 
          A.CUENTA, 
         (
          SELECT DISTINCT B.PAN
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS PAN_TI, 
          (
          SELECT DISTINCT B.CODBLQ 
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS CODBLQ_PAN, 
          (
          SELECT MAX(C.NUMDOC )
            FROM SAT.TBDOCPER C
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = C.IDENTIFICADOR_EJECUCION
             AND A.IDENTCLI = C.IDENTCLI
             AND C.TIPDOC = 'UNI' 
             AND AC.FECENVIO = AT.FECENVIO
          ) 
          AS UNICO, 
          (
          SELECT DISTINCT B.FECCADTAR
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS FECCADTAR,
          (
          SELECT DISTINCT B.MOTBLQ 
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          ) 
          AS MOTBLQ_PAN, 
          A.NUMORDEN, 
          A.FECULTCAR, 
          A.PRODUCTO, 
          A.SUBPRODU, 
          A.LIMCRECTA, 
          A.LIMCRECTATEM, 
          A.FECINITEM, 
          A.FECFINTEM, 
          A.SALAUTCRE, 
          A.SALDISCRE, 
          A.LIMCRECTAC, 
          A.SALAUTCREC, 
          A.SALDISCREC, 
          (CASE  
               WHEN A.LIMCRECTA - A.SALDISCRE  = 0
               THEN 0
               WHEN A.LIMCRECTA - A.SALDISCRE  < 0
               THEN 0
               ELSE  A.LIMCRECTA - A.SALDISCRE
            END) 
                AS SALDISP_C,
          ((SELECT DISTINCT CASE WHEN MAX(AA.SALDISCRE) IS NULL
              THEN 0
              ELSE MAX(AA.SALDISCRE)
              END
             FROM SAT.PCENVPO1_CU AA, SAT.ATINTCAB AAT
            WHERE AA.IDENTIFICADOR_EJECUCION = AAT.IDENTIFICADOR_EJECUCION
              AND AAT.FECENVIO = CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,AT.FECENVIO)) + '/' + CONVERT(VARCHAR,DATEPART(MM,AT.FECENVIO)) + '/1')
              AND AA.CUENTA = A.CUENTA) 
                         +
          (SELECT DISTINCT MAX(ISNULL(AB.SALDISCRE,0))
             FROM SAT.PCENVPO1_CU AB
            WHERE AB.IDENTIFICADOR_EJECUCION = A.IDENTIFICADOR_EJECUCION
              AND AB.CUENTA = A.CUENTA)
           ) / 2 
                AS ANR_BALANCE_MTH, 
          A.FECPROVEN, 
          A.FECULTVEN, 
          A.FECRESOL, 
          A.IDENTCLI, 
          A.CODESTCTA, 
          A.FECULTESTCTA, 
          A.CODCONVEN, 
          A.INDCTAEMP, 
          A.INDDOMCARCRE, 
          A.CTACARGO, 
          A.FORPAGO, 
          A.INDSITCTA, 
          A.COMISIONES, 
          A.INTERESES, 
          A.CAPITAL, 
          A.GRUPOLIQ, 
          A.CODBLQULT, 
          A.IMPMINORIGINAL, 
          A.IMPMINPENDIENTE, 
          (A.IMPMINORIGINAL - A.IMPMINPENDIENTE)  AS IMP_PAGADO, 
          A.MOTBLQ, 
          A.CODVIAJFRE, 
          A.FECALTAVIAJ, 
          A.INDCLICUMM, 
          A.INDCLICUMC, 
          A.FECCLICUM, 
          A.CLASIFRISAT, 
          A.CLASIFRIREG, 
          A.CLASIFRIMDE, 
          A.TASAEFECMAX, 
          (
          SELECT DISTINCT D.TIPOREG
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          ) 
          AS TIPOREG, 
          (
          SELECT DISTINCT D.SITUACION
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS SITUACION, 
          (
          SELECT DISTINCT D.IMPCONT
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMPCONT, 
          (
          SELECT DISTINCT D.IMPAGO
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMPAGO, 
          (
          SELECT DISTINCT D.IMPAPL
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMPAPL, 
          (
          SELECT DISTINCT (D.IMPAGO - D.IMPAPL)
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMP_PENDIENTE, 
          (
          SELECT DISTINCT D.FECULTAPL
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS FECULTAPL, 
          (
          SELECT DISTINCT D.FECENVCOB
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS FECENVCOB, 
          (SELECT MAX(BAL.SALDISCRE) 
             FROM SAT.PCENVPO1_CU BAL
                , SAT.ATINTCAB ATBAL
            where BAL.IDENTIFICADOR_EJECUCION = ATBAL.IDENTIFICADOR_EJECUCION
              AND ATBAL.FECENVIO 
                  BETWEEN (SELECT CONVERT(DATE,VALOR) FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH') 
                      AND AT.FECENVIO 
              AND BAL.CUENTA = A.CUENTA)
          AS BALMASALTO, 
          ( SELECT MAX(ATFEC.FECENVIO) 
              FROM SAT.PCENVPO1_CU FEC
                 , SAT.ATINTCAB ATFEC
             WHERE ATFEC.IDENTIFICADOR_EJECUCION = FEC.IDENTIFICADOR_EJECUCION
               AND FEC.SALDISCRE = (SELECT MAX(BAL.SALDISCRE) 
                                      FROM SAT.PCENVPO1_CU BAL
                                         , SAT.ATINTCAB ATBAL
                                     where BAL.IDENTIFICADOR_EJECUCION = ATBAL.IDENTIFICADOR_EJECUCION
                                       AND ATBAL.FECENVIO 
                                                  BETWEEN (SELECT CONVERT(DATE,VALOR) FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH') 
                                                      AND AT.FECENVIO 
                                       AND BAL.CUENTA = A.CUENTA)
               AND ATFEC.FECENVIO 
                   BETWEEN (SELECT CONVERT(DATE,VALOR) FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH')
                       AND AT.FECENVIO
               AND FEC.CUENTA = A.CUENTA
          )
          AS FECHA_BALMASALTO
--SELECT COUNT(1)
  INTO SAT.TB_BALANCE_SALDOS_DIARIOS
  FROM SAT.ATINTCAB AT
     , SAT.PCENVPO1_CU A
 WHERE A.IDENTIFICADOR_EJECUCION = AT.IDENTIFICADOR_EJECUCION
   AND AT.FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
   AND 1 = 2
  END -- SI NO EXISTE
  IF @OPERACION = 'C'
     RETURN 0
END -- OPERACION = 'C'

IF @OPERACION = 'L' -- LEE DATOS DE LA TABLA FIJA
BEGIN
  SELECT * FROM SAT.TB_BALANCE_SALDOS_DIARIOS
   WHERE FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
   RETURN 0
END -- OPERACION = 'L'

if @OPERACION = 'G' --- GRABA DATOS EN ESTRUCTURA DE TABLA FIJA.. SI EXISTEN PRIMERO LOS BORRA.. SI LA TABLA NO EXISTE LA CREA..
BEGIN
DELETE SAT.TB_BALANCE_SALDOS_DIARIOS
 WHERE FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
INSERT SAT.TB_BALANCE_SALDOS_DIARIOS
SELECT    AT.FECENVIO, 
          A.CODENT_D, 
          A.CUENTA, 
         (
          SELECT DISTINCT B.PAN
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS PAN_TI, 
          (
          SELECT DISTINCT B.CODBLQ 
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS CODBLQ_PAN, 
          (
          SELECT MAX(C.NUMDOC )
            FROM SAT.TBDOCPER C
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = C.IDENTIFICADOR_EJECUCION
             AND A.IDENTCLI = C.IDENTCLI
             AND C.TIPDOC = 'UNI' 
             AND AC.FECENVIO = AT.FECENVIO
          ) 
          AS UNICO, 
          (
          SELECT DISTINCT B.FECCADTAR
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS FECCADTAR,
          (
          SELECT DISTINCT B.MOTBLQ 
            FROM SAT.PCENVPO1_MP B
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = B.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = B.CUENTA
             AND B.CALPART = 'TI'
             AND AC.FECENVIO = AT.FECENVIO
          ) 
          AS MOTBLQ_PAN, 
          A.NUMORDEN, 
          A.FECULTCAR, 
          A.PRODUCTO, 
          A.SUBPRODU, 
          A.LIMCRECTA, 
          A.LIMCRECTATEM, 
          A.FECINITEM, 
          A.FECFINTEM, 
          A.SALAUTCRE, 
          A.SALDISCRE, 
          A.LIMCRECTAC, 
          A.SALAUTCREC, 
          A.SALDISCREC, 
          (CASE  
               WHEN A.LIMCRECTA - A.SALDISCRE  = 0
               THEN 0
               WHEN A.LIMCRECTA - A.SALDISCRE  < 0
               THEN 0
               ELSE  A.LIMCRECTA - A.SALDISCRE
            END) 
                AS SALDISP_C,
          ((SELECT DISTINCT CASE WHEN MAX(AA.SALDISCRE) IS NULL
              THEN 0
              ELSE MAX(AA.SALDISCRE)
              END
             FROM SAT.PCENVPO1_CU AA, SAT.ATINTCAB AAT
            WHERE AA.IDENTIFICADOR_EJECUCION = AAT.IDENTIFICADOR_EJECUCION
              AND AAT.FECENVIO = CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,AT.FECENVIO)) + '/' + CONVERT(VARCHAR,DATEPART(MM,AT.FECENVIO)) + '/1')
              AND AA.CUENTA = A.CUENTA) 
                         +
          (SELECT DISTINCT MAX(ISNULL(AB.SALDISCRE,0))
             FROM SAT.PCENVPO1_CU AB
            WHERE AB.IDENTIFICADOR_EJECUCION = A.IDENTIFICADOR_EJECUCION
              AND AB.CUENTA = A.CUENTA)
           ) / 2 
                AS ANR_BALANCE_MTH, 
          A.FECPROVEN, 
          A.FECULTVEN, 
          A.FECRESOL, 
          A.IDENTCLI, 
          A.CODESTCTA, 
          A.FECULTESTCTA, 
          A.CODCONVEN, 
          A.INDCTAEMP, 
          A.INDDOMCARCRE, 
          A.CTACARGO, 
          A.FORPAGO, 
          A.INDSITCTA, 
          A.COMISIONES, 
          A.INTERESES, 
          A.CAPITAL, 
          A.GRUPOLIQ, 
          A.CODBLQULT, 
          A.IMPMINORIGINAL, 
          A.IMPMINPENDIENTE, 
          (A.IMPMINORIGINAL - A.IMPMINPENDIENTE)  AS IMP_PAGADO, 
          A.MOTBLQ, 
          A.CODVIAJFRE, 
          A.FECALTAVIAJ, 
          A.INDCLICUMM, 
          A.INDCLICUMC, 
          A.FECCLICUM, 
          A.CLASIFRISAT, 
          A.CLASIFRIREG, 
          A.CLASIFRIMDE, 
          A.TASAEFECMAX, 
          (
          SELECT DISTINCT D.TIPOREG
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          ) 
          AS TIPOREG, 
          (
          SELECT DISTINCT D.SITUACION
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS SITUACION, 
          (
          SELECT DISTINCT D.IMPCONT
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMPCONT, 
          (
          SELECT DISTINCT D.IMPAGO
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMPAGO, 
          (
          SELECT DISTINCT D.IMPAPL
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMPAPL, 
          (
          SELECT DISTINCT (D.IMPAGO - D.IMPAPL)
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS IMP_PENDIENTE, 
          (
          SELECT DISTINCT D.FECULTAPL
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS FECULTAPL, 
          (
          SELECT DISTINCT D.FECENVCOB
            FROM SAT.PCENVPO1_IC D
               , SAT.ATINTCAB AC
           WHERE AC.IDENTIFICADOR_EJECUCION = D.IDENTIFICADOR_EJECUCION
             AND A.CUENTA = D.CUENTA
             AND AC.FECENVIO = AT.FECENVIO
          )
          AS FECENVCOB, 
          (SELECT MAX(BAL.SALDISCRE) 
             FROM SAT.PCENVPO1_CU BAL
                , SAT.ATINTCAB ATBAL
            where BAL.IDENTIFICADOR_EJECUCION = ATBAL.IDENTIFICADOR_EJECUCION
              AND ATBAL.FECENVIO 
                  BETWEEN (SELECT CONVERT(DATE,VALOR) FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH') 
                      AND AT.FECENVIO 
              AND BAL.CUENTA = A.CUENTA)
          AS BALMASALTO, 
          ( SELECT MAX(ATFEC.FECENVIO) 
              FROM SAT.PCENVPO1_CU FEC
                 , SAT.ATINTCAB ATFEC
             WHERE ATFEC.IDENTIFICADOR_EJECUCION = FEC.IDENTIFICADOR_EJECUCION
               AND FEC.SALDISCRE = (SELECT MAX(BAL.SALDISCRE) 
                                      FROM SAT.PCENVPO1_CU BAL
                                         , SAT.ATINTCAB ATBAL
                                     where BAL.IDENTIFICADOR_EJECUCION = ATBAL.IDENTIFICADOR_EJECUCION
                                       AND ATBAL.FECENVIO 
                                                  BETWEEN (SELECT CONVERT(DATE,VALOR) FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH') 
                                                      AND AT.FECENVIO 
                                       AND BAL.CUENTA = A.CUENTA)
               AND ATFEC.FECENVIO 
                   BETWEEN (SELECT CONVERT(DATE,VALOR) FROM CNF.PARAMETROS WHERE PARAMETRO = 'FECINISATDWH')
                       AND AT.FECENVIO
               AND FEC.CUENTA = A.CUENTA
          )
          AS FECHA_BALMASALTO
--SELECT COUNT(1)
  FROM SAT.ATINTCAB AT
     , SAT.PCENVPO1_CU A
 WHERE A.IDENTIFICADOR_EJECUCION = AT.IDENTIFICADOR_EJECUCION
   AND AT.FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
  RETURN 0
END -- OPERACION = 'G'

IF @OPERACION = 'B'  --- BORRA DATOS DE LA TABLA FIJA
BEGIN
  IF NOT EXISTS(SELECT 1 from sysobjects where name = 'TB_BALANCE_SALDOS_DIARIOS' AND user_name(uid) = 'SAT')
  BEGIN
    return 0
  END
  DELETE SAT.TB_BALANCE_SALDOS_DIARIOS
   WHERE FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
  RETURN 0
END -- OPERACION = 'B'

END  -- FIN PROCEDIMIENTO;
COMMIT;