COMMIT
drop view IF EXISTS SAT.VW_BALANCE_SALDOS_DIARIOS;
commit;
create VIEW SAT.VW_BALANCE_SALDOS_DIARIOS 
AS
-- SI SE DESEA QUE LA VISTA LEA DE TABLAS BASES EJECUTAR: SELECT * FROM SAT.SP_BALANCE_SALDOS_DIARIOS('V')
-- SI SE DESEA QUE LA VISTA LEA DE TABLA FIJA EJECUTAR..: SELECT * FROM SAT.SP_BALANCE_SALDOS_DIARIOS('L')
SELECT * FROM SAT.SP_BALANCE_SALDOS_DIARIOS('V')
