
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('SH_ROUTE','/datos/dataofuscadasincomprimir/');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('EMAIL_NOTIFICACION','soporte@bancocuscatlan.com.sv');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('UBICACION ARCHIVO','/datos/dataofuscadasincomprimir/');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('REPROCESO','1');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('RUTA_ARCHIVO','/data/SAT/mallas/');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('SH_ROUTE_TEC','/data/SAT/mallas/');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('U_SEN','usr_sentinelcr');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('P_SEN','Sen12IQ18');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('PATH_SEN','/data/SAT/sentinel/');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('SERVER_SEN','SVBCWSQL01DA');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('PORT_SEN','3341');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES(NULL,NULL);
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('U_SEN_','usr_sentinelcr');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('P_SEN_','Sen12IQ18');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('PATH_SEN_','/data/SAT/sentinel/');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('SERVER_SEN_','SVBCWSQL01DA');
INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('PORT_SEN_','3341');
COMMIT;