
drop table IF EXISTS "CNF"."PARAMETROS";  

CREATE TABLE IF NOT EXISTS "CNF"."PARAMETROS" (
	"FECHA_CREACION" "datetime" NOT NULL DEFAULT "getdate"(),
	"PARAMETRO" VARCHAR(100) NULL  ,
	"VALOR" VARCHAR(255) NULL  
)COMMIT;



