DROP TABLE IF EXISTS "DWH_ETLS"."PCIMPEXT_ML";
COMMIT;
DROP TABLE IF EXISTS "STG"."PCIMPEXT_ML";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PCIMPEXT_ML";
COMMIT;
CREATE TABLE IF NOT EXISTS "STG_SAT"."PCIMPEXT_ML" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"TIPOREG" VARCHAR(2) NULL ,
	"NUMORDEN" DECIMAL(12,0) NULL ,
	"LINEA1" VARCHAR(50) NULL ,
	"FILLER1" VARCHAR(894) NULL 
)  COMMIT;
