drop table IF EXISTS SAT.PCIMPEXT_CI;  CREATE TABLE IF NOT EXISTS SAT.PCIMPEXT_CI  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	PAN	VARCHAR	(22)	--NUMERO DE TARJETA (PRIMERA TARJETA DEL CONTRATO)
,	TIPOREG	VARCHAR	(2)	--TIPO DE REGISTRO 
--'CL' - DATOS DE CLIENTE 	 	 		
--'CU' - CUENTA O CONTRATO DE TARJETA 	 	 		
--'LI' - LINEAS DE CREDITO PARALELAS	 	 		
--'EX' - EXTRACTO 	 	 		
--'TX' - EXTRACTO - TIPO DE LINEA - TIPO IMPORTE	 	 		
--'MX' - MOVIMIENTO EXTRACTO	 	 		
--'MC' - MOVIMIENTO CONCEPTO ECONOMICO	 	 		
--'IC' - CONTRATO IMPAGADO	 	 		
--'IL' - DESGLOSE CONTRATO IMPAGADO	 	 		
--'RI' - RECIBO IMPAGADO	 	 		
--'RL' - DESGLOSE RECIBO IMPAGADO	 	 		
--'MI' - MOVIMIENTO RECIBO IMPAGADO	 	 		
--'CI' - CONCEPTO ECONOMICO DE MOVIMIENTO RECIBO       IMPAGADO	 	 		
--'PU'    - PUNTOS DE FIDELIZACION SFC O B.LEON'	 	 		
--?ML'    - LINEAS DE MENSAJERIA PARA EXTRACTOS	 	 		
--'MS'    - MANEJO DE MENSAJES PROMOCIONALES	 	 		
--'MZ'    - BONIFICACION ONLINE DE CAMPANAS	 	 		
,	NUMORDEN	DECIMAL	(12,0)	--NUMERO DE ORDEN 
,	NUMSECIMP	DECIMAL	(15,0)	--NUMERO SECUENCIA RECIBO IMPAGADO
,	NUMMOVIMP	DECIMAL	(7,0)	--NUMERO DE MOVIMIENTO DEL RECIBO IMPAGADO
,	CODCONECO	DECIMAL	(4,0)	--CODIGO DE CONCEPTO ECONOMICO
,	TIPIMP	DECIMAL	(2,0)	--TIPO DE IMPORTE
---        02 - COMISIONES	 	 		
---        03 - INTERESES	 	 		
---        04 - IMPUESTOS	 	 		
---        05 - COMISIONES MOROSIDAD	 	 		
---        06 - INTERESES MOROSIDAD	 	 		
---        07 - IMPUESTOS MOROSIDAD	 	 		
---        08 - SEGURO	 	 		
,	IMPAPLECO	DECIMAL	(17,2)	--IMPORTE SOBRE EL QUE SE APLICA EL CONCEPTO ECONOMICO
,	IMPBRUECO	DECIMAL	(17,2)	--IMPORTE BRUTO CALCULADO POR EL CONCEPTO ECONOMICO
,	IMPBONECO	DECIMAL	(17,2)	--IMPORTE DE BONIFICACION CALCULADO POR EL CONCEPTO ECONOMICO
,	IMPIMPTO	DECIMAL	(17,2)	--IMPORTE DEL IMPUESTO
,	IMPCONSOL	DECIMAL	(17,2)	--IMPORTE CONSOLIDADO
,	PORINT	DECIMAL	(7,4)	--PORCENTAJE DE INTERES APLICADO
,	INDPERCON	VARCHAR	(1)	--INDICADOR DE CONCEPTO PERDONADO
,	FILLER1	VARCHAR	(823)	--FILLER
); COMMIT;	 	 		