DROP TABLE IF EXISTS "DWH_ETLS"."PCIMPEXT_TX";
COMMIT;
DROP TABLE IF EXISTS "STG"."PCIMPEXT_TX";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PCIMPEXT_TX";
COMMIT;
CREATE TABLE IF NOT EXISTS "STG_SAT"."PCIMPEXT_TX" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"TIPOREG" VARCHAR(2) NULL ,
	"NUMORDEN" DECIMAL(12,0) NULL ,
	"NUMEXTCTA" DECIMAL(3,0) NULL ,
	"CLAMON" DECIMAL(3,0) NULL ,
	"TIPOLIN" VARCHAR(4) NULL ,
	"TIPIMP" DECIMAL(2,0) NULL ,
	"IMPINI" DECIMAL(17,2) NULL ,
	"IMPFIN" DECIMAL(17,2) NULL ,
	"IMPBON" DECIMAL(17,2) NULL ,
	"IMPAPL" DECIMAL(17,2) NULL ,
	"IMPREC" DECIMAL(17,2) NULL ,
	"IMPMIN" DECIMAL(17,2) NULL ,
	"FILLER1" VARCHAR(830) NULL 
)  COMMIT;
