drop table IF EXISTS SAT.PCIMPEXT_MX;  CREATE TABLE IF NOT EXISTS SAT.PCIMPEXT_MX  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	PAN	VARCHAR	(22)	--NUMERO DE TARJETA (PRIMERA TARJETA DEL CONTRATO)
,	TIPOREG	VARCHAR	(2)	--TIPO DE REGISTRO 
--'CL' - DATOS DE CLIENTE 	 	 		
--'CU' - CUENTA O CONTRATO DE TARJETA 	 	 		
--'LI' - LINEAS DE CREDITO PARALELAS	 	 		
--'EX' - EXTRACTO 	 	 		
--'TX' - EXTRACTO - TIPO DE LINEA - TIPO IMPORTE	 	 		
--'MX' - MOVIMIENTO EXTRACTO	 	 		
--'MC' - MOVIMIENTO CONCEPTO ECONOMICO	 	 		
--'IC' - CONTRATO IMPAGADO	 	 		
--'IL' - DESGLOSE CONTRATO IMPAGADO	 	 		
--'RI' - RECIBO IMPAGADO	 	 		
--'RL' - DESGLOSE RECIBO IMPAGADO	 	 		
--'MI' - MOVIMIENTO RECIBO IMPAGADO	 	 		
--'CI' - CONCEPTO ECONOMICO DE MOVIMIENTO RECIBO       IMPAGADO	 	 		
--'PU'    - PUNTOS DE FIDELIZACION SFC O B.LEON'	 	 		
--?ML'    - LINEAS DE MENSAJERIA PARA EXTRACTOS	 	 		
--'MS'    - MANEJO DE MENSAJES PROMOCIONALES	 	 		
--'MZ'    - BONIFICACION ONLINE DE CAMPANAS	 	 		
,	NUMORDEN	DECIMAL	(12,0)	--NUMERO DE ORDEN 
,	NUMEXTCTA	DECIMAL	(3,0)	--NUMERO DE EXTRACTO
,	CLAMON	DECIMAL	(3,0)	--CLAVE DE MONEDA
,	NUMMOVEXT	DECIMAL	(7,0)	--NUMERO DE MOVIMIENTO EN EL EXTRACTO
,	INDNORCOR	DECIMAL	(1,0)	--INDICADOR DE TI PO DE FACTURA NORMAL O CORRECTORA
---         0 - NORMAL	 	 		
---         1 - CORRECTORA	 	 		
,	TIPOFAC	DECIMAL	(4,0)	--TIPO DE FACTURA
,	SIGNO	VARCHAR	(1)	--SIGNO DEL IMPORTE
,	DESTIPFAC	VARCHAR	(30)	--DESCRIPCION DEL TIPO DE FACTURA
,	INDFACINF	VARCHAR	(1)	--INDICADOR FACTURA INFORMATIVA (S/N)
,	FECFAC	DATE		--FECHA DE LA FACTURA
,	NUMREFFAC	VARCHAR	(23)	--NUMERO REFERENCIA FACTURA
,	PAN_OPE	VARCHAR	(22)	--PAN DE LA TARJETA QUE REALIZO LA OPERACION
,	CLAMONDIV	DECIMAL	(3,0)	--CODIGO DE MONEDA DE LA OPERACION ORIGINAL O DIVISA
,	IMPDIV	DECIMAL	(17,2)	--IMPORTE EN DIVISA ORIGINAL
,	IMPFAC	DECIMAL	(17,2)	--IMPORTE DE LA FACTURA
,	CMBAPLI	DECIMAL	(9,4)	--FACTOR DE CAMBIO APLICADO (SOLO TIENE SENTIDO PARA OPERACIONES EN EXTRANJERO)
,	CODCOM	VARCHAR	(15)	--CODIGO DE COMERCIO 
,	NOMCOMRED	VARCHAR	(27)	--NOMBRE COMERCIO REDUCIDO
,	NOMPOB	VARCHAR	(26)	--POBLACION DONDE SE REALIZO LA OPERACION
,	DESACT	VARCHAR	(30)	--DESCRIPCION DE ACTIVIDAD
,	FECPROCES	DATE		--FECHA DE PROCESO O ENTRADA DE LA OPERACION AL SISTEMA
,	CODPAIS	DECIMAL	(3,0)	--CODIGO DEL PAIS 
,	FECCONTA	DATE		--FECHA CONTABLE OPERACION
,	IMPIMPTO	DECIMAL	(17,2)	--IMPORTE DEL IMPUESTO
,	CODACT	DECIMAL	(4,0)	--CODIGO DE ACTIVIDAD
,	LINREF	DECIMAL	(8,0)	--REFERENCIA DE LINEA ASOCIADA A LA CUENTA
,	FORPAGO	DECIMAL	(2,0)	--FORMA DE PAGO
,	NUMAUT	VARCHAR	(6)	--NUMERO DE AUTORIZACION
,	TIPOFACSIST	DECIMAL	(4,0)	--TIPO DE FACTURA DEL SISTEMA
,	CODPAISO	VARCHAR	(3)	--DESCRPCION DE PAIS CON 3 POSICIONES
,	NOMBENRED	VARCHAR	(35)	--NOMBRE DE ESTAMPACION
,	TIPOLIN	VARCHAR	(4)	--TIPO DE LINEA
,	IMPAMPAG_DIF	DECIMAL	(17,2)	--IMPORTE DE PAGOS AMORTIZADOS PARA COMPRAS EN CUOTAS
,	IMPAMPAG_REV	DECIMAL	(17,2)	--IMPORTE DE PAGOS AMORTIZADOS PARA REVOLVING
,	FILLER1	VARCHAR	(555)	--FILLER
); COMMIT;	 	 		