DROP TABLE IF EXISTS "DWH_ETLS"."PCIMPEXT_PU";
COMMIT;
DROP TABLE IF EXISTS "STG"."PCIMPEXT_PU";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PCIMPEXT_PU";
COMMIT;
CREATE TABLE IF NOT EXISTS "STG_SAT"."PCIMPEXT_PU" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"TIPOREG" VARCHAR(2) NULL ,
	"NUMORDEN" DECIMAL(12,0) NULL ,
	"PTOSGANAMESANT" DECIMAL(8,0) NULL ,
	"PTOSCANJMESANT" DECIMAL(8,0) NULL ,
	"PTOSVENCMES" DECIMAL(8,0) NULL ,
	"PTOSPERDMES" DECIMAL(8,0) NULL ,
	"PTOSCANJMES" DECIMAL(8,0) NULL ,
	"PTOSGANAMES" DECIMAL(8,0) NULL ,
	"PTOSDISP" DECIMAL(8,0) NULL ,
	"PTOSPROXCAD" DECIMAL(8,0) NULL ,
	"TRATARPTOS" VARCHAR(1) NULL ,
	"PTOSALINI" DECIMAL(8,0) NULL ,
	"FILLER1" VARCHAR(871) NULL 
)  COMMIT;
