drop table IF EXISTS SAT.PCIMPEXT_CU;  CREATE TABLE IF NOT EXISTS SAT.PCIMPEXT_CU  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	PAN	VARCHAR	(22)	--NUMERO DE TARJETA (PRIMERA TARJETA DEL CONTRATO)
,	TIPOREG	VARCHAR	(2)	--TIPO DE REGISTRO 
--'CL' - DATOS DE CLIENTE 	 	 		
--'CU' - CUENTA O CONTRATO DE TARJETA 	 	 		
--'LI' - LINEAS DE CREDITO PARALELAS	 	 		
--'EX' - EXTRACTO 	 	 		
--'TX' - EXTRACTO - TIPO DE LINEA - TIPO IMPORTE	 	 		
--'MX' - MOVIMIENTO EXTRACTO	 	 		
--'MC' - MOVIMIENTO CONCEPTO ECONOMICO	 	 		
--'IC' - CONTRATO IMPAGADO	 	 		
--'IL' - DESGLOSE CONTRATO IMPAGADO	 	 		
--'RI' - RECIBO IMPAGADO	 	 		
--'RL' - DESGLOSE RECIBO IMPAGADO	 	 		
--'MI' - MOVIMIENTO RECIBO IMPAGADO	 	 		
--'CI' - CONCEPTO ECONOMICO DE MOVIMIENTO RECIBO       IMPAGADO	 	 		
--'PU'    - PUNTOS DE FIDELIZACION SFC O B.LEON'	 	 		
--?ML'    - LINEAS DE MENSAJERIA PARA EXTRACTOS	 	 		
--'MS'    - MANEJO DE MENSAJES PROMOCIONALES	 	 		
--'MZ'    - BONIFICACION ONLINE DE CAMPANAS	 	 		
,	NUMORDEN	DECIMAL	(12,0)	--NUMERO DE ORDEN 
,	PRODUCTO	VARCHAR	(2)	--CODIGO DE PRODUCTO
,	SUBPRODU	VARCHAR	(4)	--CODIGO DE SUBPRODUCTO
,	CONPROD	VARCHAR	(3)	--CODIGO DE CONDICION ECONOMICA
,	CALPART	VARCHAR	(2)	--CALIDAD DE PARTICIPACION, IDENTIFICADOR DE CLIENTE
,	NUMBEN	DECIMAL	(5,0)	--NUMERO DE BENEFICIARIOS DE LA CUENTA
,	CODREGIMEN	DECIMAL	(4,0)	--CODIGO DE REGIMEN FISCAL
,	CLAMON	DECIMAL	(3,0)	--CLAVE DE MONEDA 
,	LIMCRECTA	DECIMAL	(17,2)	--LIMITE DE CREDITO DE LA CUENTA O CONTRATO DE TARJETA
,	SALDISCRE	DECIMAL	(17,2)	--SALDO DISPUESTO A CREDITO
,	LIMCRECTAC	DECIMAL	(17,2)	--LIMITE DE CREDITO DE LA CUENTA O CONTRATO DE TARJETA DE CUOTAS
,	SALDISCREC	DECIMAL	(17,2)	--SALDO DISPUESTO A CREDITO DE CUOTAS
,	INDMONPRIN	VARCHAR	(1)	--INDICADOR DE MONEDA PRINCIPAL (S/N)
,	CODFORMATO	VARCHAR	(10)	--CODIGO DE FORMATO
,	IDENTCLI	VARCHAR	(8)	--IDENTIFICADOR DE CLIENTE
,	INDDOMCARCRE	VARCHAR	(1)	--INDICADOR DOMICILIACION
,	INDCTAEMP	DECIMAL	(1,0)	--INDICADOR CUENTA EMPRESA
,	CLASEG	VARCHAR	(3)	--CLASE DE SEGMENTO DEL CLIENTE(TIPO DE CLIENTE)
--01 - CLIENTE	 	 		
--02 - EMPLEADO	 	 		
,	IBAN	VARCHAR	(4)	--IBAN DE LA CUENTA DE CARGO
,	CTACARGO	VARCHAR	(30)	--CUENTA DE CARGO O DOMICILIACION
,	CODIDIOMA 	VARCHAR	(2)	--CODIGO DE IDIOMA
,	CODBLQ	DECIMAL	(2,0)	--CODIGO DE BLOQUEO
,	DISBLECRECTA	DECIMAL	(17,2)	--DISPONIBLE CREDITO CUENTA
,	DISBLECRECTAC	DECIMAL	(17,2)	--DISPONIBLE CREDITO CUENTA
,	GRUPOLIQ	DECIMAL	(2,0)	--GRUPO DE LIQUIDACION
,	DESPROD	VARCHAR	(30)	--DESCRIPCION DEL PRODUCTO
,	INTERESANUAL1	DECIMAL	(9,4)	--INTERES ANUAL MONEDA 1
,	INTERESANUAL2	DECIMAL	(9,4)	--INTERES ANUAL MONEDA 2
,	BALANPAGO	DECIMAL	(19,2)	--BALANCE DE PAGO (FACTURA INFORMATIVA INTERES BONIFICABLE 9205)
,	NOMBREMP	VARCHAR	(30)	--NOMBRE DE EMPRESA
,	GRUPOEMP	DECIMAL	(4,0)	--GRUPO EMPRESA
,	PORMOPPAL	DECIMAL	(9,4)	--PORCENTAJE MORA MONEDA PRINCIPAL
,	TRAMOPPAL	DECIMAL	(17,2)	--IMPORTE FIJO MORA MONEDA PRINCIPAL
,	PORMOSEC	DECIMAL	(9,4)	--PORCENTAJE MORA MONEDA SECUNDARIA
,	TRAMOSEC	DECIMAL	(17,2)	--IMPORTE FIJO MORA MONEDA SECUNDARIA
,	INTANUALPPAL	DECIMAL	(9,4)	--INTERES ANUAL MONEDA PRINCIPAL
,	INTANUALSEC	DECIMAL	(9,4)	--INTERES ANUAL MONEDA SECUNDARIA
,	LIMCRECTAPPAL	DECIMAL	(17,2)	--LIMITE DE CREDITO MONEDA PRINCIPAL
,	LIMCRECTASEC	DECIMAL	(17,2)	--LIMITE DE CREDITO MONEDA SECUNDARIA
,	MOTBLQ	DECIMAL	(2,0)	--MOTIVO DE BLOQUEO
,	FILLER1	VARCHAR	(539)	--FILLER
,	FILLER2	VARCHAR	(9)	--FILLER
); COMMIT;	 	 		