drop table IF EXISTS SAT.PCIMPEXT_PU;  CREATE TABLE IF NOT EXISTS SAT.PCIMPEXT_PU  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	PAN	VARCHAR	(22)	--NUMERO DE TARJETA (PRIMERA TARJETA DEL CONTRATO)
,	TIPOREG	VARCHAR	(2)	--TIPO DE REGISTRO 
--'CL' - DATOS DE CLIENTE 	 	 		
--'CU' - CUENTA O CONTRATO DE TARJETA 	 	 		
--'LI' - LINEAS DE CREDITO PARALELAS	 	 		
--'EX' - EXTRACTO 	 	 		
--'TX' - EXTRACTO - TIPO DE LINEA - TIPO IMPORTE	 	 		
--'MX' - MOVIMIENTO EXTRACTO	 	 		
--'MC' - MOVIMIENTO CONCEPTO ECONOMICO	 	 		
--'IC' - CONTRATO IMPAGADO	 	 		
--'IL' - DESGLOSE CONTRATO IMPAGADO	 	 		
--'RI' - RECIBO IMPAGADO	 	 		
--'RL' - DESGLOSE RECIBO IMPAGADO	 	 		
--'MI' - MOVIMIENTO RECIBO IMPAGADO	 	 		
--'CI' - CONCEPTO ECONOMICO DE MOVIMIENTO RECIBO       IMPAGADO	 	 		
--'PU'    - PUNTOS DE FIDELIZACION SFC O B.LEON'	 	 		
--?ML'    - LINEAS DE MENSAJERIA PARA EXTRACTOS	 	 		
--'MS'    - MANEJO DE MENSAJES PROMOCIONALES	 	 		
--'MZ'    - BONIFICACION ONLINE DE CAMPANAS	 	 		
,	NUMORDEN	DECIMAL	(12,0)	--NUMERO DE ORDEN 
,	PTOSGANAMESANT	DECIMAL	(8,0)	--PUNTOS GANADOS MES ANTERIOR
,	PTOSCANJMESANT	DECIMAL	(8,0)	--PUNTOS CANJEADOS MES ANTERIOR
,	PTOSVENCMES	DECIMAL	(8,0)	--PUNTOS VENCIDOS EN EL MES
,	PTOSPERDMES	DECIMAL	(8,0)	--PUNTOS PERDIDOS EN EL MES
,	PTOSCANJMES	DECIMAL	(8,0)	--PUNTOS CANJEADOS EN EL MES
,	PTOSGANAMES	DECIMAL	(8,0)	--PUNTOS GANADOS EN EL MES
,	PTOSDISP	DECIMAL	(8,0)	--PUNTOS DISPONIBLES
,	PTOSPROXCAD	DECIMAL	(8,0)	--PUNTOS PROXIMOS A CADUCAR
,	TRATARPTOS	VARCHAR	(1)	--TRATAR PUNTOS. SI TIENE "S" INDICA QUE LOS PUNTOS DEL MES YA PASAN AL MES ANTERIOR.
,	PTOSALINI	DECIMAL	(8,0)	--SALDO INICIAL DE PUNTOS
,	FILLER1	VARCHAR	(871)	--FILLER
); COMMIT;	 	 		