DROP TABLE IF EXISTS "DWH_ETLS"."PCIMPEXT_CI";
COMMIT;
DROP TABLE IF EXISTS "STG"."PCIMPEXT_CI";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PCIMPEXT_CI";
COMMIT;
CREATE TABLE IF NOT EXISTS "STG_SAT"."PCIMPEXT_CI" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"TIPOREG" VARCHAR(2) NULL ,
	"NUMORDEN" DECIMAL(12,0) NULL ,
	"NUMSECIMP" DECIMAL(15,0) NULL ,
	"NUMMOVIMP" DECIMAL(7,0) NULL ,
	"CODCONECO" DECIMAL(4,0) NULL ,
	"TIPIMP" DECIMAL(2,0) NULL ,
	"IMPAPLECO" DECIMAL(17,2) NULL ,
	"IMPBRUECO" DECIMAL(17,2) NULL ,
	"IMPBONECO" DECIMAL(17,2) NULL ,
	"IMPIMPTO" DECIMAL(17,2) NULL ,
	"IMPCONSOL" DECIMAL(17,2) NULL ,
	"PORINT" DECIMAL(7,4) NULL ,
	"INDPERCON" VARCHAR(1) NULL ,
	"FILLER1" VARCHAR(823) NULL 
)  COMMIT;
