drop table IF EXISTS SAT.PCIMPEXT_EX;  CREATE TABLE IF NOT EXISTS SAT.PCIMPEXT_EX  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	PAN	VARCHAR	(22)	--NUMERO DE TARJETA (PRIMERA TARJETA DEL CONTRATO)
,	TIPOREG	VARCHAR	(2)	--TIPO DE REGISTRO 
--'CL' - DATOS DE CLIENTE 	 	 		
--'CU' - CUENTA O CONTRATO DE TARJETA 	 	 		
--'LI' - LINEAS DE CREDITO PARALELAS	 	 		
--'EX' - EXTRACTO 	 	 		
--'TX' - EXTRACTO - TIPO DE LINEA - TIPO IMPORTE	 	 		
--'MX' - MOVIMIENTO EXTRACTO	 	 		
--'MC' - MOVIMIENTO CONCEPTO ECONOMICO	 	 		
--'IC' - CONTRATO IMPAGADO	 	 		
--'IL' - DESGLOSE CONTRATO IMPAGADO	 	 		
--'RI' - RECIBO IMPAGADO	 	 		
--'RL' - DESGLOSE RECIBO IMPAGADO	 	 		
--'MI' - MOVIMIENTO RECIBO IMPAGADO	 	 		
--'CI' - CONCEPTO ECONOMICO DE MOVIMIENTO RECIBO       IMPAGADO	 	 		
--'PU'    - PUNTOS DE FIDELIZACION SFC O B.LEON'	 	 		
--?ML'    - LINEAS DE MENSAJERIA PARA EXTRACTOS	 	 		
--'MS'    - MANEJO DE MENSAJES PROMOCIONALES	 	 		
--'MZ'    - BONIFICACION ONLINE DE CAMPANAS	 	 		
,	NUMORDEN	DECIMAL	(12,0)	--NUMERO DE ORDEN 
,	NUMEXTCTA	DECIMAL	(3,0)	--NUMERO DE EXTRACTO
,	CLAMON	DECIMAL	(3,0)	--CLAVE DE MONEDA 
,	INDREP	DECIMAL	(1,0)	--INDICADOR DE RELIQUIDACION DE EXTRACTO
---         0 - NORMAL	 	 		
---         2 - RELIQUIDADO	 	 		
,	FORPAGO	DECIMAL	(2,0)	--FORMA DE PAGO 
,	IMPTOTPAG	DECIMAL	(17,2)	--IMPORTE TOTAL A PAGAR
,	IMPMIN	DECIMAL	(17,2)	--IMPORTE MINIMO DE PAGO
,	IMPCARGO	DECIMAL	(17,2)	--IMPORTE DE CARGO MENSUAL CALCULADO SEGUN FORMA DE PAGO
,	FECEXT	DATE		--FECHA DE EXTRACTO
,	FECLIQ	DATE		--FECHA DE LIQUIDACION
,	FECLIQANT	DATE		--FECHA DE LIQUIDACION ANTERIOR
,	FECCAR	DATE		--FECHA DE CARGO EXTRACTO
,	FECVALCAR	DATE		--FECHA VALOR DEL CARGO EXTRACTO
,	PORINT	DECIMAL	(7,4)	--PORCENTAJE DE INTERES
,	PORPAGOA 	DECIMAL	(7,4)	--PORCENTAJE PAGO APLAZADO
,	IMPEXCLIM	DECIMAL	(17,2)	--IMPORTE EXCESO DEL LIMITE DE CREDITO
,	IMSALAPLPRX	DECIMAL	(17,2)	--IMPORTE APLAZADO
,	IMPCARGOANT	DECIMAL	(17,2)	--IMPORTE DEL CARGO MENSUAL CALCULADO SEGUN FORMA DE PAGO
,	NUMSECREC	DECIMAL	(15,0)	--NUMERO SECUENCIAL DEL RECIBO
,	IMPDISBLEEXC	DECIMAL	(17,2)	--IMPORTE DE EXCESO DE LIMITE - IMPORTE SALDO APLAZADO
,	FECVENMOV	VARCHAR	(10)	--FECHA DE VENCIMIENTO DE MOVIMIENTO
,	MX_POS	DECIMAL	(17,2)	--TOTAL PAGOS CREDITO POSITIVOS
,	MX_NEG	DECIMAL	(17,2)	--TOTAL PAGOS CREDITO NEGATIVOS
,	MC_POS	DECIMAL	(17,2)	--TOTAL PAGOS CUOTAS POSITIVOS
,	MC_NEG	DECIMAL	(17,2)	--TOTAL PAGOS CUOTAS NEGATIVOS
,	BALMESANT	DECIMAL	(17,2)	--BALANCE MES ANTERIOR (IMPORTE FINAL EXTRACTO)
,	BALMESACT	DECIMAL	(17,2)	--BALANCE MES ACTUAL (IMPORTE INICIAL EXTRACTO)
,	INTBONIF	DECIMAL	(17,2)	--INTERES BONIFICABLE (FACTURA INFORMATIVA 9205)
,	BALMESACTBON	DECIMAL	(17,2)	--BALANCE MES ACTUAL + INTERES BONIFICABLE
,	CUOTAMIN	DECIMAL	(17,2)	--PAGO MENSUAL (APLICANDO PAGO MINIMO) DE LA FINANCIACION DE LA DEUDA
,	PLAZOMIN	DECIMAL	(3,0)	--NUMERO DE MESES (APLICANDO PAGO MINIMO) DE LA FINANCIACION DE LA DEUDA
,	IMPTOTMIN	DECIMAL	(17,2)	--IMPORTE TOTAL DE LA FINANCIACION DE LA DEUDA (APLICANDO PAGO MINIMO) 
,	CUOTA12	DECIMAL	(17,2)	--PAGO MENSUAL (APLICANDO FINANCIACION ANUAL 12 MESES) DE LA FINANCIACION DE LA DEUDA
,	PLAZO12	DECIMAL	(3,0)	--NUMERO DE MESES (ANUAL = 12) DE LA FINANCIACION DE LA DEUDA
,	IMPTOTAL12	DECIMAL	(17,2)	--IMPORTE TOTAL DE LA FINANCIACION DE LA DEUDA (APLICANDO FIANCIACION ANUAL 12 MESES)
,	TOT_POS	DECIMAL	(17,2)	--TOTAL DEBITOS (CONSUMOS + COMISIONES + INTERESES)
,	TOT_NEG	DECIMAL	(17,2)	--TOTAL CREDITOS (ABONOS + COMISIONES + INTERESES)
,	BALPROVANT	DECIMAL	(17,2)	--BALANCE PROMEDIO OPERACIONES VIVAS EXTRACTO ANTERIOR (FACTURA 200 DEL EXTRACTO ANTERIOR)
,	BALPROVACT	DECIMAL	(17,2)	--BALANCE PROMEDIO OPERACIONES VIVAS EXTRACTO ACTUAL (FACTURA 200 DEL EXTRACTO ACTUAL)
,	IMPMINREV	DECIMAL	(17,2)	--IMPORTE MINIMO DE REVOLVING
,	IMPMINCC	DECIMAL	(17,2)	--IMPORTE MINIMO DE COMPRAS EN CUOTAS
,	IMPRECREV	DECIMAL	(17,2)	--IMPORTE RECIBO DE REVOLVING
,	IMPRECCC	DECIMAL	(17,2)	--IMPORTE RECIBO DE COMPRAS EN CUOTAS
,	IMPFINREV	DECIMAL	(17,2)	--IMPORTE FINAL DE REVOLVING
,	IMPFINCC	DECIMAL	(17,2)	--IMPORTE FINAL DE COMPRAS EN CUOTAS
,	IMPUESTO	DECIMAL	(17,2)	--TOTAL DE IMPUESTO SOBRE COMISIONES
,	TASAEFEXT	DECIMAL	(7,4)	--TASA EFECTIVA MAXIMA DE INTERES DEL EXTRACTO
,	BONCAMPAN	DECIMAL	(17,2)	--BONIFICACIONES ONLINE DE CAMPANAS
,	BALMESTOTANT	DECIMAL	(17,2)	--BALANCE ANTERIOR TOTAL (INCLUYE DIFERIDO)
,	BALMESTOTAC	DECIMAL	(17,2)	--BALANCE ACTUAL TOTAL (INCLUYE DIFERIDO)
,	BALMESANTREV	DECIMAL	(14,2)	--BALANCE MES ANTERIOR LINEAS REVOLVENTES
,	BALMESACTREV	DECIMAL	(14,2)	--BALANCE MES ACTUAL LINEAS REVOLVENTES
,	BALMESANTDIF	DECIMAL	(14,2)	--BALANCE MES ANTERIOR LINEAS DIFERIDAS
,	BALMESACTDIF	DECIMAL	(14,2)	--BALANCE MES ACTUAL LINEAS DIFERIDAS
,	MX_POS_REV	DECIMAL	(14,2)	--CONSUMOS DEL REVOLVENTES
,	MX_NEG_REV	DECIMAL	(14,2)	--CREDITOS Y PAGOS DEL REVOLVENTE
,	MX_POS_DIF	DECIMAL	(14,2)	--CONSUMOS DEL DIFERIDO
,	MX_NEG_DIF	DECIMAL	(14,2)	--CREDITOS Y PAGOS DEL DIFERIDO
,	MC_POS_REV	DECIMAL	(14,2)	--CONCEPTOS ECONOMICOS DEBITO DEL REVOLVENTE
,	MC_NEG_REV	DECIMAL	(14,2)	--CONCEPTOS ECONOMICOS CREDITO DEL REVOLVENTE
,	MC_POS_DIF	DECIMAL	(14,2)	--CONCEPTOS ECONOMICOS DEBITO DEL DIFERIDO
,	MC_NEG_DIF	DECIMAL	(14,2)	--CONCEPTOS ECONOMICOS CREDITO DEL DIFERIDO
,	TOT_POS_REV	DECIMAL	(14,2)	--TOTAL CONSUMOS DEL REVOLVENTE
,	TOT_NEG_REV	DECIMAL	(14,2)	--TOTAL CREDITOS Y PAGOS DEL REVOLVENTE
,	TOT_POS_DIF	DECIMAL	(14,2)	--TOTAL CONSUMOS DEL DIFERIDO
,	TOT_NEG_DIF	DECIMAL	(14,2)	--TOTAL CREDITOS Y PAGOS DEL DIFERIDO
,	IMP_COM	DECIMAL	(14,2)	--TOTAL DE COMISIONES SIN GRAVAMEN
,	FILLER1	VARCHAR	(34)	--FILLER
); COMMIT;	 	 		