drop table IF EXISTS SAT.PCIMPEXT_CL;  CREATE TABLE IF NOT EXISTS SAT.PCIMPEXT_CL  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	PAN	VARCHAR	(22)	--NUMERO DE TARJETA (PRIMERA TARJETA DEL CONTRATO)
,	TIPOREG	VARCHAR	(2)	--TIPO DE REGISTRO 
--'CL' - DATOS DE CLIENTE 	 	 		
--'CU' - CUENTA O CONTRATO DE TARJETA 	 	 		
--'LI' - LINEAS DE CREDITO PARALELAS	 	 		
--'EX' - EXTRACTO 	 	 		
--'TX' - EXTRACTO - TIPO DE LINEA - TIPO IMPORTE	 	 		
--'MX' - MOVIMIENTO EXTRACTO	 	 		
--'MC' - MOVIMIENTO CONCEPTO ECONOMICO	 	 		
--'IC' - CONTRATO IMPAGADO	 	 		
--'IL' - DESGLOSE CONTRATO IMPAGADO	 	 		
--'RI' - RECIBO IMPAGADO	 	 		
--'RL' - DESGLOSE RECIBO IMPAGADO	 	 		
--'MI' - MOVIMIENTO RECIBO IMPAGADO	 	 		
--'CI' - CONCEPTO ECONOMICO DE MOVIMIENTO RECIBO       IMPAGADO	 	 		
--'PU'    - PUNTOS DE FIDELIZACION SFC O B.LEON'	 	 		
--?ML'    - LINEAS DE MENSAJERIA PARA EXTRACTOS	 	 		
--'MS'    - MANEJO DE MENSAJES PROMOCIONALES	 	 		
--'MZ'    - BONIFICACION ONLINE DE CAMPANAS	 	 		
,	NUMORDEN	DECIMAL	(12,0)	--NUMERO DE ORDEN 
,	NOMBRE	VARCHAR	(40)	--NOMBRE DE CLIENTE
,	APELLIDO1	VARCHAR	(36)	--APELLIDO 1 DEL CLIENTE 
,	APELLIDO2	VARCHAR	(36)	--APELLIDO 2 DEL CLIENTE 
,	FORMAENVIO	VARCHAR	(2)	--FORMA DE ENVIO DEL EXTRACTO
--EM-EMAIL	 	 		
--CO-CORREO	 	 		
--AM-AMBOS,CORREO E EMAIL	 	 		
--NO-NO ENVIO DE EXTRACTO	 	 		
,	EMAIL	VARCHAR	(100)	--E-MAIL DEL CLIENTE
,	CODPAIS	DECIMAL	(3,0)	--CODIGO PAIS
,	NOMPAIS	VARCHAR	(20)	--NOMBRE PAIS
,	CODREGION	VARCHAR	(3)	--CODIGO REGION
,	DESREGION	VARCHAR	(20)	--NOMBRE REGION
,	CODPROV	VARCHAR	(2)	--CODIGO PROVINCIA
,	DESPROV	VARCHAR	(20)	--NOMBRE PROVINCIA
,	CIUDAD	VARCHAR	(5)	--CODIGO CIUDAD
,	DESCIUDAD	VARCHAR	(35)	--NOMBRE CIUDAD
,	CODMUNICIP	VARCHAR	(5)	--CODIGO MUNICIPIO
,	MUNICIPIO	VARCHAR	(40)	--MUNICIPIO
,	CODSECTOR	VARCHAR	(5)	--CODIGO SECTOR
,	SECTOR	VARCHAR	(40)	--SECTOR
,	CODBARRIO	VARCHAR	(5)	--CODIGO BARRIO
,	BARRIO	VARCHAR	(40)	--BARRIO
,	TIPVIA	VARCHAR	(2)	--TIPO DE VIA
,	NOMVIA	VARCHAR	(5)	--CODIGO VIA
,	DESCNOMVIA	VARCHAR	(100)	--NOMBRE DE LA VIA 
,	NUMVIA	VARCHAR	(6)	--NUMERO DEL DOMICILIO
,	ESCALERA	VARCHAR	(4)	--ESCALERA
,	PISO	VARCHAR	(4)	--PISO
,	PUERTA	VARCHAR	(4)	--PUERTA
,	MANZANA	VARCHAR	(10)	--MANZANA
,	EDIFICIO	VARCHAR	(4)	--EDIFICIO
,	KILOMETRO	VARCHAR	(7)	--KILOMETRO
,	CODPOSTAL	VARCHAR	(10)	--ZONA POSTAL
,	APTDOCORREOS	VARCHAR	(10)	--APARTADO DE CORREOS
,	ENTRECALLES1	VARCHAR	(5)	--
,	DESENTRECALLES1	VARCHAR	(100)	--ENTRE QUE CALLES VIVE 1
,	ENTRECALLES2	VARCHAR	(5)	--
,	DESENTRECALLES2	VARCHAR	(100)	--ENTRE QUE CALLES VIVE 2
,	RESTODIR	VARCHAR	(40)	--RESTO DE DIRECCION
,	NUMDOC	VARCHAR	(22)	--NUMERO DE DOCUMETO
,	APELARGO	VARCHAR	(40)	--APELLIDO DE CASADA
,	FILLER1	VARCHAR	(9)	--filler
); COMMIT;	 	 		