DROP TABLE IF EXISTS "DWH_ETLS"."PCIMPEXT_LI";
COMMIT;
DROP TABLE IF EXISTS "STG"."PCIMPEXT_LI";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PCIMPEXT_LI";
COMMIT;
CREATE TABLE IF NOT EXISTS "STG_SAT"."PCIMPEXT_LI" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"TIPOREG" VARCHAR(2) NULL ,
	"NUMORDEN" DECIMAL(12,0) NULL ,
	"LINREF" DECIMAL(8,0) NULL ,
	"TIPOLIN" VARCHAR(4) NULL ,
	"CODCAMCOM" VARCHAR(4) NULL ,
	"CLAMON" DECIMAL(3,0) NULL ,
	"LIMCRELIN" DECIMAL(17,2) NULL ,
	"SALAUTLIN" DECIMAL(17,2) NULL ,
	"SALDISLIN" DECIMAL(17,2) NULL ,
	"FILLER1" VARCHAR(874) NULL 
)  COMMIT;
