DROP TABLE IF EXISTS "DWH_ETLS"."PCIMPEXT_RZ";
COMMIT;
DROP TABLE IF EXISTS "STG"."PCIMPEXT_RZ";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PCIMPEXT_RZ";
COMMIT;
CREATE TABLE IF NOT EXISTS "STG_SAT"."PCIMPEXT_RZ" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"TIPOREG" VARCHAR(2) NULL ,
	"NUMORDEN" DECIMAL(12,0) NULL ,
	"NUMEXTCTA" DECIMAL(3,0) NULL ,
	"CLAMON" DECIMAL(3,0) NULL ,
	"TIPLINEA" VARCHAR(3) NULL ,
	"CAPACT" DECIMAL(17,2) NULL ,
	"INTACT" DECIMAL(17,2) NULL ,
	"RECACT" DECIMAL(17,2) NULL ,
	"COMACT" DECIMAL(17,2) NULL ,
	"PAGACT" DECIMAL(17,2) NULL ,
	"CORACT" DECIMAL(17,2) NULL ,
	"CREACT" DECIMAL(17,2) NULL ,
	"DEBACT" DECIMAL(17,2) NULL ,
	"FILLER1" VARCHAR(799) NULL 
)  COMMIT;
