drop table IF EXISTS SAT.PCEXTCU1_CL;  CREATE TABLE IF NOT EXISTS SAT.PCEXTCU1_CL  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	TIPOREG	VARCHAR	(2)	--TIPO DE REGISTRO 
--CU CUENTA O CONTRATO DE TARJETA 	 	 		
--LI LINEAS DE CREDITO PARALELAS	 	 		
--FI DATOS COMPRA EN CUOTAS	 	 		
--CE MOVIMIENTO CUOTA 	 	 		
--CC MOVIMIENTO CONCEPTO ECONOMICO	 	 		
--CL DATOS DE CLIENTE 	 	 		
--	 	 		
,	NOMBRE	VARCHAR	(40)	--NOMBRE DE CLIENTE
,	APELLIDO1	VARCHAR	(36)	--APELLIDO 1 DEL CLIENTE 
,	APELLIDO2	VARCHAR	(36)	--APELLIDO 2 DEL CLIENTE 
,	FORMAENVIO	VARCHAR	(2)	--FORMA DE ENVIO DEL EXTRACTO
--EM  E-MAIL      CO CORREO	 	 		
,	E_MAIL	VARCHAR	(100)	--E-MAIL DEL CLIENTE
,	CODPAIS	DECIMAL	(3,0)	--CODIGO DE PAIS
,	PAIS	VARCHAR	(20)	--PAIS
,	CODREGION   	VARCHAR	(3)	--CODIGO DE REGION
,	DESCREGION  	VARCHAR	(20)	--REGION
,	CODPROV     	VARCHAR	(2)	--CODIGO DE PROVINCIA
,	DESCPROV    	VARCHAR	(20)	--PROVINCIA
,	CIUDAD      	VARCHAR	(5)	--CODIGO DE CIUDAD
,	DESCCIUDAD  	VARCHAR	(35)	--CIUDAD
,	CODMUNICIP  	VARCHAR	(5)	--CODIGO DE MUNICIPIO
,	MUNICIPIO   	VARCHAR	(40)	--MUNICIPIO
,	CODSECTOR   	VARCHAR	(5)	--CODIGO DE SECTOR
,	SECTOR      	VARCHAR	(40)	--SECTOR
,	CODBARRIO   	VARCHAR	(5)	--CODIGO DE BARRIO
,	BARRIO      	VARCHAR	(40)	--BARRIO
,	TIPVIA      	VARCHAR	(2)	--TIPO DE VIA 
,	NOMVIA      	VARCHAR	(5)	--CODIGO DE VIA
,	DESCNOMVIA  	VARCHAR	(100)	--NOMBRE DE LA VIA
,	NUMVIA      	VARCHAR	(6)	--NUMERO 
,	ESCALERA    	VARCHAR	(4)	--ESCALERA
,	PISO        	VARCHAR	(4)	--PISO
,	PUERTA      	VARCHAR	(4)	--PUERTA
,	MANZANA     	VARCHAR	(10)	--MANZANA
,	EDIFICIO    	VARCHAR	(4)	--EDIFICIO
,	KILOMETRO   	VARCHAR	(7)	--KILOMETRO
,	CODPOSTAL   	VARCHAR	(10)	--ZONA POSTAL
,	CODAPTCOR   	VARCHAR	(10)	--APARTADO DE CORREOS
,	ENTRCALLES1 	VARCHAR	(5)	--CODIGO DE VIA ENTRE QUE CALLES VIVE 1
,	DESENTRCALL1	VARCHAR	(100)	--ENTRE QUE CALLES VIVE 2
,	ENTRCALLES2 	VARCHAR	(5)	--CODIGO DE VIA ENTRE QUE CALLES VIVE 2
,	DESENTRCALL2	VARCHAR	(100)	--ENTRE QUE CALLES VIVE 2
,	RESTODIR	VARCHAR	(40)	--RESTO DE DIRECCION
,	NUMDOC	VARCHAR	(22)	--NUMERO DE DOCUMENTO
,	APELARGO	VARCHAR	(50)	--APELLIDO LARGO
,	FILLER1	VARCHAR	(33)	--
); COMMIT;	 	 		