drop table IF EXISTS SAT.PCEXTCU1_CU;  CREATE TABLE IF NOT EXISTS SAT.PCEXTCU1_CU  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	TIPOREG	VARCHAR	(2)	--TIPO DE REGISTRO 
--'CU' - CUENTA O CONTRATO DE TARJETA 	 	 		
--'LI' - LINEAS DE CREDITO PARALELAS	 	 		
--'FI ' - DATOS COMPRA EN CUOTAS	 	 		
--'CE' - MOVIMIENTO CUOTA 	 	 		
--'CC' - MOVIMIENTO CONCEPTO ECONOMICO	 	 		
--'CL'   - DATOS DE CLIENTE 	 	 		
--	 	 		
,	PRODUCTO	VARCHAR	(2)	--CODIGO DE PRODUCTO
,	SUBPRODU	VARCHAR	(4)	--CODIGO DE SUBPRODUCTO
,	CONPROD	VARCHAR	(3)	--CODIGO DE CONDICION ECONOMICA
,	CALPART	VARCHAR	(2)	--CALIDAD DE PARTICIPACION
,	NUMBEN	DECIMAL	(5,0)	--NUMERO DE BENEFICIARIOS DE LA CUENTA
,	CODREGIMEN	DECIMAL	(4,0)	--CODIGO DE REGIMEN FISCAL
,	CLAMON	DECIMAL	(3,0)	--CLAVE DE MONEDA 
,	LIMCRECTA	DECIMAL	(17,2)	--LIMITE DE CREDITO DE LA CUENTA O CONTRATO DE TARJETA
,	LIMCRECTAC	DECIMAL	(17,2)	--LIMITE DE CREDITO COMPRA EN CUOTAS DE LA CUENTA O CONTRATO DE TARJETA
,	SALDISCRE	DECIMAL	(17,2)	--SALDO DISPUESTO A CREDITO
,	SALDISCREC	DECIMAL	(17,2)	--SALDO DISPUESTO A CREDITO EN COMPRA EN CUOTAS
,	INDMONPRIN	VARCHAR	(1)	--INDICADOR DE MONEDA PRINCIPAL (S/N)
,	CODFORMATO	VARCHAR	(10)	--CODIGO DE FORMATO
,	DISBLECRECTA	VARCHAR	(17)	--DISPONIBLE CREDITO CUENTA
,	DISBLECRECTAC	VARCHAR	(17)	--DISPONIBLE CREDITO CUENTA EN CUOTAS
,	GRUPOLIQ	DECIMAL	(2,0)	--GRUPO DE LIQUIDACION
,	DESPROD	VARCHAR	(30)	--DESCRIPCION DEL PRODUCTO
,	INTERESANUAL	DECIMAL	(9,4)	--INTERES ANUAL
,	NOMBREMP	VARCHAR	(30)	--NOMBRE DE EMPRESA
,	GRUPOEMP	DECIMAL	(4,0)	--GRUPO EMPRESA
,	BALMESACT	DECIMAL	(17,2)	--BALANCE MES ACTUAL
,	BALMESANT	DECIMAL	(17,2)	--BALANCE MES ANTERIOR
,	FILLER1	VARCHAR	(733)	--
); COMMIT;	 	 		