drop table IF EXISTS SAT.PCEXTCU1_CE;  CREATE TABLE IF NOT EXISTS SAT.PCEXTCU1_CE  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	TIPOREG	VARCHAR	(2)	--TIPO DE REGISTRO 
--'CU' - CUENTA O CONTRATO DE TARJETA 	 	 		
--'LI' - LINEAS DE CREDITO PARALELAS	 	 		
--'FI ' - DATOS COMPRA EN CUOTAS	 	 		
--'CE' - MOVIMIENTO CUOTA 	 	 		
--'CC' - MOVIMIENTO CONCEPTO ECONOMICO	 	 		
--'CL'   - DATOS DE CLIENTE 	 	 		
--	 	 		
,	NUMOPECUO	DECIMAL	(6,0)	--NUMERO DE MOVIMIENTO
,	NUMFINAN	DECIMAL	(3,0)	--NUMERO DE FINANCIACION
,	NUMCUOTA	DECIMAL	(9,0)	--NUMERO DE CUOTA
,	IMPCUOTA	DECIMAL	(17,2)	--IMPORTE DE LA CUOTA
,	IMPCAPITAL	DECIMAL	(17,2)	--IMPORTE CAPITAL
,	IMPINTERESES	DECIMAL	(17,2)	--IMPORTE INTERES
,	IMPIMPTO	DECIMAL	(17,2)	--IMPORTE DE IMPUESTO
,	FECLIQ	DATE		--FECHA DE LIQUIDACION
,	FILLER1	VARCHAR	(882)	--
); COMMIT;	 	 		