DROP TABLE IF EXISTS "DWH_ETLS"."PCEXTCU1_LI";
COMMIT;
DROP TABLE IF EXISTS "STG"."PCEXTCU1_LI";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PCEXTCU1_LI";
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."PCEXTCU1_LI" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"TIPOREG" VARCHAR(2) NULL ,
	"LINEA" VARCHAR(4) NULL ,
	"CODCAMCOM" VARCHAR(4) NULL ,
	"CLAMON" DECIMAL(3,0) NULL ,
	"LIMCRELIN" DECIMAL(17,2) NULL ,
	"SALAUTLIN" DECIMAL(17,2) NULL ,
	"SALDISLIN" DECIMAL(17,2) NULL ,
	"FECINILIN" VARCHAR(10) NULL ,
	"FECFINLIN" VARCHAR(10) NULL ,
	"INDTIPLIN" VARCHAR(1) NULL ,
	"INDTIPOPE" VARCHAR(1) NULL ,
	"IMPCUOTATOT" DECIMAL(17,2) NULL ,
	"IMPCOMPTOT" DECIMAL(17,2) NULL ,
	"BALCUOACT" DECIMAL(17,2) NULL ,
	"BALCUOANT" DECIMAL(17,2) NULL ,
	"CREDDISP" DECIMAL(17,2) NULL ,
	"FILLER1" VARCHAR(809) NULL 
)  COMMIT;
