DROP TABLE IF EXISTS "DWH_ETLS"."PCEXTCU1_CC";
COMMIT;
DROP TABLE IF EXISTS "STG"."PCEXTCU1_CC";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."PCEXTCU1_CC";
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."PCEXTCU1_CC" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"TIPOREG" VARCHAR(2) NULL ,
	"NUMOPECUO" DECIMAL(6,0) NULL ,
	"NUMFINAN" DECIMAL(3,0) NULL ,
	"NUMCUOTA" DECIMAL(9,0) NULL ,
	"CODCONECO" DECIMAL(4,0) NULL ,
	"TIPIMP" DECIMAL(2,0) NULL ,
	"IMPAPLECO" DECIMAL(17,2) NULL ,
	"IMPBRUECO" DECIMAL(17,2) NULL ,
	"IMPBONECO" DECIMAL(17,2) NULL ,
	"SIGNO" VARCHAR(1) NULL ,
	"FILLER1" VARCHAR(902) NULL 
)  COMMIT;
