if exists (select 1 from CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_CASOS_ATC')
BEGIN
  DELETE CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_CASOS_ATC'
END
INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") 
VALUES('JOB_CASE_CENTER_ATC','CC_CASOS_ATC',NULL,0);
COMMIT;
