--- creacion de grupo de usuarios SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'SAT')
BEGIN
  CREATE USER SAT 
  FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

--- creacion de grupo de usuarios STG_SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'STG_SAT')
BEGIN
  CREATE USER STG_SAT
  FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

drop table IF EXISTS SAT.TBINCINT;  CREATE TABLE IF NOT EXISTS SAT.TBINCINT  ( 	IDENTIFICADOR_EJECUCION	INTEGER	
--MPDT096-Incidencias	 	 	
,	CODENT_D	VARCHAR	(4)
,	NSECFIC_D	DECIMAL	(10,0)
,	TIPOCINTA_D	DECIMAL	(2,0)
,	TIPOREG_D	VARCHAR	(1)
,	FILLER_D	VARCHAR	(91)
,	NUMREGPROC	DECIMAL	(12,0)
,	CODENT 	VARCHAR	(4)
,	NUMINC 	DECIMAL	(9,0)
,	NUMEXP 	DECIMAL	(9,0)
,	CODREG 	DECIMAL	(2,0)
--1        - Incidencia de incoming e incidencias en estudio (extracto) 	 	 	
--2        - Error de incoming e incidencias de comercio 	 	 	
-- 	 	 	
,	NUMREFREM 	DECIMAL	(10,0)
,	NUMREFFACREM 	DECIMAL	(5,0)
,	INDAJENA 	VARCHAR	(1)
,	INDNORCOR 	DECIMAL	(1,0)
--0 - Normal    1 - Correctora 	 	 	
,	TIPOFAC 	DECIMAL	(4,0)
,	PAN 	VARCHAR	(22)
,	TIPFRAN 	DECIMAL	(4,0)
,	SECOPE 	DECIMAL	(12,0)
,	NUMREF 	VARCHAR	(23)
,	FECFAC 	DATE	
,	NUMAUT 	VARCHAR	(6)
,	NOMCOMRED 	VARCHAR	(27)
,	CODCOM 	VARCHAR	(15)
,	CODACT 	DECIMAL	(4,0)
,	INDDEBCRE 	DECIMAL	(1,0)
,	CLAMONDIV 	DECIMAL	(3,0)
,	FECCMB 	DATE	
,	CMBAPLI 	DECIMAL	(9,4)
,	IMPDIV 	DECIMAL	(17,2)
,	IMPLIQ 	DECIMAL	(17,2)
,	CLAMONLIQ 	DECIMAL	(3,0)
,	POBCOM 	VARCHAR	(24)
--	 	 	
,	FECALTAINC 	DATE	
,	TIPOINC 	DECIMAL	(3,0)
,	MOTINC 	DECIMAL	(2,0)
,	INDERROR 	VARCHAR	(16)
,	CODRAZ 	DECIMAL	(4,0)
,	CODSOLINC 	DECIMAL	(2,0)
,	TIPOSOL 	DECIMAL	(2,0)
,	FECSOLINC 	DATE	
,	FECLIQ 	DATE	
,	CODFUNFRAN 	DECIMAL	(3,0)
,	INDCHAPAR 	VARCHAR	(1)
,	CODACTESP 	DECIMAL	(4,0)
,	MODOOBTAUT 	VARCHAR	(2)
,	TEXTOINICIO 	VARCHAR	(60)
,	NUMCINTA 	DECIMAL	(17,0)
,	INDAPLCOM 	VARCHAR	(1)
,	INDAPLEXT 	VARCHAR	(1)
,	INDORIINC 	VARCHAR	(1)
--1  - EXTRACTO         	 	 	
--2  - INCIDENCIAS      	 	 	
--3  - MIGRACION        	 	 	
--4  - COMPRA EN CUOTAS 	 	 	
--5  - COMERCIOS	 	 	
,	INDANUL 	VARCHAR	(1)
,	INDRET 	DECIMAL	(1,0)
,	FECCONTA 	DATE	
,	FECCONTASOL 	DATE	
,	INDINCPEN 	VARCHAR	(1)
,	CLAMON 	DECIMAL	(3,0)
,	IMPFAC 	DECIMAL	(17,2)
,	FECPROCIN 	DATE	
,	CODSUBFRA 	VARCHAR	(1)
,	CODPAIS 	DECIMAL	(3,0)
,	CODRAZCHA 	DECIMAL	(4,0)
,	INDCOMINC 	VARCHAR	(1)
,	INDCOMPCUO 	VARCHAR	(1)
,	CODTIPC 	VARCHAR	(4)
,	TOTCUOTAS 	DECIMAL	(9,0)
,	MESCARCUO 	DECIMAL	(2,0)
,	PORINT 	DECIMAL	(7,4)
,	SIAIDCD 	VARCHAR	(19)
,	NUMOPECUO 	DECIMAL	(6,0)
,	CODTERM 	VARCHAR	(16)
,	LINREF 	DECIMAL	(8,0)
,	FORPAGO 	DECIMAL	(2,0)
,	FILLER1	VARCHAR	(343)
); COMMIT;	 	 	

drop table IF EXISTS STG_SAT.TBINCINT;  CREATE TABLE IF NOT EXISTS STG_SAT.TBINCINT  (
--MPDT096-Incidencias	 	 	
 	CODENT_D	VARCHAR	(4)
,	NSECFIC_D	DECIMAL	(10,0)
,	TIPOCINTA_D	DECIMAL	(2,0)
,	TIPOREG_D	VARCHAR	(1)
,	FILLER_D	VARCHAR	(91)
,	NUMREGPROC	DECIMAL	(12,0)
,	CODENT 	VARCHAR	(4)
,	NUMINC 	DECIMAL	(9,0)
,	NUMEXP 	DECIMAL	(9,0)
,	CODREG 	DECIMAL	(2,0)
--1        - Incidencia de incoming e incidencias en estudio (extracto) 	 	 	
--2        - Error de incoming e incidencias de comercio 	 	 	
-- 	 	 	
,	NUMREFREM 	DECIMAL	(10,0)
,	NUMREFFACREM 	DECIMAL	(5,0)
,	INDAJENA 	VARCHAR	(1)
,	INDNORCOR 	DECIMAL	(1,0)
--0 - Normal    1 - Correctora 	 	 	
,	TIPOFAC 	DECIMAL	(4,0)
,	PAN 	VARCHAR	(22)
,	TIPFRAN 	DECIMAL	(4,0)
,	SECOPE 	DECIMAL	(12,0)
,	NUMREF 	VARCHAR	(23)
,	FECFAC 	DATE	
,	NUMAUT 	VARCHAR	(6)
,	NOMCOMRED 	VARCHAR	(27)
,	CODCOM 	VARCHAR	(15)
,	CODACT 	DECIMAL	(4,0)
,	INDDEBCRE 	DECIMAL	(1,0)
,	CLAMONDIV 	DECIMAL	(3,0)
,	FECCMB 	DATE	
,	CMBAPLI 	DECIMAL	(9,4)
,	IMPDIV 	DECIMAL	(17,2)
,	IMPLIQ 	DECIMAL	(17,2)
,	CLAMONLIQ 	DECIMAL	(3,0)
,	POBCOM 	VARCHAR	(24)
--	 	 	
,	FECALTAINC 	DATE	
,	TIPOINC 	DECIMAL	(3,0)
,	MOTINC 	DECIMAL	(2,0)
,	INDERROR 	VARCHAR	(16)
,	CODRAZ 	DECIMAL	(4,0)
,	CODSOLINC 	DECIMAL	(2,0)
,	TIPOSOL 	DECIMAL	(2,0)
,	FECSOLINC 	DATE	
,	FECLIQ 	DATE	
,	CODFUNFRAN 	DECIMAL	(3,0)
,	INDCHAPAR 	VARCHAR	(1)
,	CODACTESP 	DECIMAL	(4,0)
,	MODOOBTAUT 	VARCHAR	(2)
,	TEXTOINICIO 	VARCHAR	(60)
,	NUMCINTA 	DECIMAL	(17,0)
,	INDAPLCOM 	VARCHAR	(1)
,	INDAPLEXT 	VARCHAR	(1)
,	INDORIINC 	VARCHAR	(1)
--1  - EXTRACTO         	 	 	
--2  - INCIDENCIAS      	 	 	
--3  - MIGRACION        	 	 	
--4  - COMPRA EN CUOTAS 	 	 	
--5  - COMERCIOS	 	 	
,	INDANUL 	VARCHAR	(1)
,	INDRET 	DECIMAL	(1,0)
,	FECCONTA 	DATE	
,	FECCONTASOL 	DATE	
,	INDINCPEN 	VARCHAR	(1)
,	CLAMON 	DECIMAL	(3,0)
,	IMPFAC 	DECIMAL	(17,2)
,	FECPROCIN 	DATE	
,	CODSUBFRA 	VARCHAR	(1)
,	CODPAIS 	DECIMAL	(3,0)
,	CODRAZCHA 	DECIMAL	(4,0)
,	INDCOMINC 	VARCHAR	(1)
,	INDCOMPCUO 	VARCHAR	(1)
,	CODTIPC 	VARCHAR	(4)
,	TOTCUOTAS 	DECIMAL	(9,0)
,	MESCARCUO 	DECIMAL	(2,0)
,	PORINT 	DECIMAL	(7,4)
,	SIAIDCD 	VARCHAR	(19)
,	NUMOPECUO 	DECIMAL	(6,0)
,	CODTERM 	VARCHAR	(16)
,	LINREF 	DECIMAL	(8,0)
,	FORPAGO 	DECIMAL	(2,0)
,	FILLER1	VARCHAR	(343)
); COMMIT;	 	 	

------------------------------------------------
---- CONTROL DE VERSION ------------------------
------------------------------------------------
create table IF NOT EXISTS CNF.VERSION_OBJETOS (
 NOMBRE_MALLA varchar(100)
,OBJECT_NAME varchar(100)
,OBJECT_USER varchar(20)
,VERSION_COMMIT VARCHAR(100)
,VERSION_CODE VARCHAR(20)
,VERSION_DATE DATETIME
,CRDATE DATETIME null default getdate()
,CRUSER varchar(20) null default user_name()
)
;
COMMIT;

declare 
 @NOMBRE_MALLA varchar(100)
,@OBJECT_NAME varchar(100)
,@OBJECT_USER varchar(20)
,@VERSION_COMMIT VARCHAR(100)
,@VERSION_CODE VARCHAR(20)
,@VERSION_DATE DATETIME 
,@CRDATE DATETIME

select 
 @NOMBRE_MALLA = 'PPJDW08N'
,@OBJECT_NAME = 'TBINCINT'
,@OBJECT_USER = 'SAT'
,@VERSION_COMMIT = 'ae072868d6df45750dc8484029094fc50b7f0d6c'
,@VERSION_CODE = 'ae07286'
,@VERSION_DATE = 'March 18, 2019 6:54:38 PM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @OBJECT_USER = 'STG_SAT'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

COMMIT;

-- Inserts NUEVAS MALLAS
IF NOT EXISTS(SELECT 1 FROM "CNF"."MALLAS" WHERE "NOMBRE_MALLA" = 'PPJDW08N' )
BEGIN
  INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('PPJDW08N','Incidencias',1,0);
END
COMMIT;