--- creacion de grupo de usuarios SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'SAT')
BEGIN
  CREATE USER SAT 
  FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

--- creacion de grupo de usuarios STG_SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'STG_SAT')
BEGIN
  CREATE USER STG_SAT
  FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

drop table IF EXISTS SAT.TBINCINT;  CREATE TABLE IF NOT EXISTS SAT.TBINCINT  ( 	IDENTIFICADOR_EJECUCION	INTEGER	
--MPDT096-Incidencias	 	 	
,	CODENT_D	VARCHAR	(4)
,	NSECFIC_D	DECIMAL	(10,0)
,	TIPOCINTA_D	DECIMAL	(2,0)
,	TIPOREG_D	VARCHAR	(1)
,	FILLER_D	VARCHAR	(91)
,	NUMREGPROC	DECIMAL	(12,0)
,	CODENT 	VARCHAR	(4)
,	NUMINC 	DECIMAL	(9,0)
,	NUMEXP 	DECIMAL	(9,0)
,	CODREG 	DECIMAL	(2,0)
--1        - Incidencia de incoming e incidencias en estudio (extracto) 	 	 	
--2        - Error de incoming e incidencias de comercio 	 	 	
-- 	 	 	
,	NUMREFREM 	DECIMAL	(10,0)
,	NUMREFFACREM 	DECIMAL	(5,0)
,	INDAJENA 	VARCHAR	(1)
,	INDNORCOR 	DECIMAL	(1,0)
--0 - Normal    1 - Correctora 	 	 	
,	TIPOFAC 	DECIMAL	(4,0)
,	PAN 	VARCHAR	(22)
,	TIPFRAN 	DECIMAL	(4,0)
,	SECOPE 	DECIMAL	(12,0)
,	NUMREF 	VARCHAR	(23)
,	FECFAC 	DATE	
,	NUMAUT 	VARCHAR	(6)
,	NOMCOMRED 	VARCHAR	(27)
,	CODCOM 	VARCHAR	(15)
,	CODACT 	DECIMAL	(4,0)
,	INDDEBCRE 	DECIMAL	(1,0)
,	CLAMONDIV 	DECIMAL	(3,0)
,	FECCMB 	DATE	
,	CMBAPLI 	DECIMAL	(9,4)
,	IMPDIV 	DECIMAL	(17,2)
,	IMPLIQ 	DECIMAL	(17,2)
,	CLAMONLIQ 	DECIMAL	(3,0)
,	POBCOM 	VARCHAR	(24)
--	 	 	
,	FECALTAINC 	DATE	
,	TIPOINC 	DECIMAL	(3,0)
,	MOTINC 	DECIMAL	(2,0)
,	INDERROR 	VARCHAR	(16)
,	CODRAZ 	DECIMAL	(4,0)
,	CODSOLINC 	DECIMAL	(2,0)
,	TIPOSOL 	DECIMAL	(2,0)
,	FECSOLINC 	DATE	
,	FECLIQ 	DATE	
,	CODFUNFRAN 	DECIMAL	(3,0)
,	INDCHAPAR 	VARCHAR	(1)
,	CODACTESP 	DECIMAL	(4,0)
,	MODOOBTAUT 	VARCHAR	(2)
,	TEXTOINICIO 	VARCHAR	(60)
,	NUMCINTA 	DECIMAL	(17,0)
,	INDAPLCOM 	VARCHAR	(1)
,	INDAPLEXT 	VARCHAR	(1)
,	INDORIINC 	VARCHAR	(1)
--1  - EXTRACTO         	 	 	
--2  - INCIDENCIAS      	 	 	
--3  - MIGRACION        	 	 	
--4  - COMPRA EN CUOTAS 	 	 	
--5  - COMERCIOS	 	 	
,	INDANUL 	VARCHAR	(1)
,	INDRET 	DECIMAL	(1,0)
,	FECCONTA 	DATE	
,	FECCONTASOL 	DATE	
,	INDINCPEN 	VARCHAR	(1)
,	CLAMON 	DECIMAL	(3,0)
,	IMPFAC 	DECIMAL	(17,2)
,	FECPROCIN 	DATE	
,	CODSUBFRA 	VARCHAR	(1)
,	CODPAIS 	DECIMAL	(3,0)
,	CODRAZCHA 	DECIMAL	(4,0)
,	INDCOMINC 	VARCHAR	(1)
,	INDCOMPCUO 	VARCHAR	(1)
,	CODTIPC 	VARCHAR	(4)
,	TOTCUOTAS 	DECIMAL	(9,0)
,	MESCARCUO 	DECIMAL	(2,0)
,	PORINT 	DECIMAL	(7,4)
,	SIAIDCD 	VARCHAR	(19)
,	NUMOPECUO 	DECIMAL	(6,0)
,	CODTERM 	VARCHAR	(16)
,	LINREF 	DECIMAL	(8,0)
,	FORPAGO 	DECIMAL	(2,0)
,	FILLER1	VARCHAR	(343)
); COMMIT;	 	 	

drop table IF EXISTS STG_SAT.TBINCINT;  
CREATE TABLE IF NOT EXISTS "STG_SAT"."TBINCINT" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"NUMINC" DECIMAL(9,0) NULL ,
	"NUMEXP" DECIMAL(9,0) NULL ,
	"CODREG" DECIMAL(2,0) NULL ,
	"NUMREFREM" DECIMAL(10,0) NULL ,
	"NUMREFFACREM" DECIMAL(5,0) NULL ,
	"INDAJENA" VARCHAR(1) NULL ,
	"INDNORCOR" DECIMAL(1,0) NULL ,
	"TIPOFAC" DECIMAL(4,0) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"TIPFRAN" DECIMAL(4,0) NULL ,
	"SECOPE" DECIMAL(12,0) NULL ,
	"NUMREF" VARCHAR(23) NULL ,
	"FECFAC" VARCHAR(10) NULL ,
	"NUMAUT" VARCHAR(6) NULL ,
	"NOMCOMRED" VARCHAR(27) NULL ,
	"CODCOM" VARCHAR(15) NULL ,
	"CODACT" DECIMAL(4,0) NULL ,
	"INDDEBCRE" DECIMAL(1,0) NULL ,
	"CLAMONDIV" DECIMAL(3,0) NULL ,
	"FECCMB" VARCHAR(10) NULL ,
	"CMBAPLI" DECIMAL(9,4) NULL ,
	"IMPDIV" DECIMAL(17,2) NULL ,
	"IMPLIQ" DECIMAL(17,2) NULL ,
	"CLAMONLIQ" DECIMAL(3,0) NULL ,
	"POBCOM" VARCHAR(24) NULL ,
	"FECALTAINC" VARCHAR(10) NULL ,
	"TIPOINC" DECIMAL(3,0) NULL ,
	"MOTINC" DECIMAL(2,0) NULL ,
	"INDERROR" VARCHAR(16) NULL ,
	"CODRAZ" DECIMAL(4,0) NULL ,
	"CODSOLINC" DECIMAL(2,0) NULL ,
	"TIPOSOL" DECIMAL(2,0) NULL ,
	"FECSOLINC" VARCHAR(10) NULL ,
	"FECLIQ" VARCHAR(10) NULL ,
	"CODFUNFRAN" DECIMAL(3,0) NULL ,
	"INDCHAPAR" VARCHAR(1) NULL ,
	"CODACTESP" DECIMAL(4,0) NULL ,
	"MODOOBTAUT" VARCHAR(2) NULL ,
	"TEXTOINICIO" VARCHAR(60) NULL ,
	"NUMCINTA" DECIMAL(17,0) NULL ,
	"INDAPLCOM" VARCHAR(1) NULL ,
	"INDAPLEXT" VARCHAR(1) NULL ,
	"INDORIINC" VARCHAR(1) NULL ,
	"INDANUL" VARCHAR(1) NULL ,
	"INDRET" DECIMAL(1,0) NULL ,
	"FECCONTA" VARCHAR(10) NULL ,
	"FECCONTASOL" VARCHAR(10) NULL ,
	"INDINCPEN" VARCHAR(1) NULL ,
	"CLAMON" DECIMAL(3,0) NULL ,
	"IMPFAC" DECIMAL(17,2) NULL ,
	"FECPROCIN" VARCHAR(10) NULL ,
	"CODSUBFRA" VARCHAR(1) NULL ,
	"CODPAIS" DECIMAL(3,0) NULL ,
	"CODRAZCHA" DECIMAL(4,0) NULL ,
	"INDCOMINC" VARCHAR(1) NULL ,
	"INDCOMPCUO" VARCHAR(1) NULL ,
	"CODTIPC" VARCHAR(4) NULL ,
	"TOTCUOTAS" DECIMAL(9,0) NULL ,
	"MESCARCUO" DECIMAL(2,0) NULL ,
	"PORINT" DECIMAL(7,4) NULL ,
	"SIAIDCD" VARCHAR(19) NULL ,
	"NUMOPECUO" DECIMAL(6,0) NULL ,
	"CODTERM" VARCHAR(16) NULL ,
	"LINREF" DECIMAL(8,0) NULL ,
	"FORPAGO" DECIMAL(2,0) NULL ,
	"FILLER1" VARCHAR(343) NULL 
)COMMIT;
------------------------------------------------
---- CONTROL DE VERSION ------------------------
------------------------------------------------
create table IF NOT EXISTS CNF.VERSION_OBJETOS (
 NOMBRE_MALLA varchar(100)
,OBJECT_NAME varchar(100)
,OBJECT_USER varchar(20)
,VERSION_COMMIT VARCHAR(100)
,VERSION_CODE VARCHAR(20)
,VERSION_DATE DATETIME
,CRDATE DATETIME null default getdate()
,CRUSER varchar(20) null default user_name()
)
;
COMMIT;

declare 
 @NOMBRE_MALLA varchar(100)
,@OBJECT_NAME varchar(100)
,@OBJECT_USER varchar(20)
,@VERSION_COMMIT VARCHAR(100)
,@VERSION_CODE VARCHAR(20)
,@VERSION_DATE DATETIME 
,@CRDATE DATETIME

select 
 @NOMBRE_MALLA = 'PPJDW08N'
,@OBJECT_NAME = 'TBINCINT'
,@OBJECT_USER = 'SAT'
,@VERSION_COMMIT = 'ae072868d6df45750dc8484029094fc50b7f0d6c'
,@VERSION_CODE = 'ae07286'
,@VERSION_DATE = 'March 18, 2019 6:54:38 PM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @OBJECT_USER = 'STG_SAT'
 ,@VERSION_COMMIT = 'e7111a248d2942648800d74574a4d9488b2b3d34'
,@VERSION_CODE = 'e7111a2'
,@VERSION_DATE = 'March 20, 2019 1:48:27 PM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

COMMIT;

-- Inserts NUEVAS MALLAS
IF NOT EXISTS(SELECT 1 FROM "CNF"."MALLAS" WHERE "NOMBRE_MALLA" = 'PPJDW08N' )
BEGIN
  INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('PPJDW08N','Incidencias',1,0);
END
COMMIT;