COMMIT
drop view IF EXISTS SAT.VW_AUTORIZACIONES;
commit;
create VIEW SAT.VW_AUTORIZACIONES
AS
-- SI SE DESEA QUE LA VISTA LEA DE TABLAS BASES EJECUTAR: SELECT * FROM SAT.SP_AUTORIZACIONES('V')
-- SI SE DESEA QUE LA VISTA LEA DE TABLA FIJA EJECUTAR..: SELECT * FROM SAT.SP_AUTORIZACIONES('L')
  SELECT 
       IDENTIFICADOR_EJECUCION 
      ,CODENT                  
      ,TIPOMSGON               
      ,CODPROON                
      ,SIAIDCD                 
      ,PAN                     
      ,CODMAR                  
      ,INDTIPT                 
      ,INDDEBCRE               
      ,IMPTRN                  
      ,CLAMONTRN               
      ,IMPCCA                  
      ,CLAMONCCA               
      ,IMPDIV                  
      ,CLAMONDIV               
      ,FECTRN                  
      ,HORTRN                  
      ,CMBAPLI                 
      ,CODACT                  
      ,CODPAIS                 
      ,MODENTDAT               
      ,SESIONORI               
      ,SESIONSIA               
      ,IMPTASAS                
      ,IDADQUIR                
      ,CODRED                  
      ,NUMREFOPE               
      ,IDTERM                  
      ,CODCOM                  
      ,NOMCOM                  
      ,LOCALIDAD               
      ,RTSITD                  
      ,DATORI                  
      ,NUMAUT                  
      ,CODRESPU                
      ,CODACCRED               
      ,TIPFRAN                 
      ,INDNORCOR               
      ,TIPOFAC                 
      ,INDPREAUT               
      ,INDCRUCE                
      ,INDANUL                 
      ,INDRETSAL               
      ,IMPTRNCON               
      ,IMPAUTCON               
      ,CLAMONCON               
      ,FECCONTA                
      ,NUMRETSAL               
      ,IMPRETSAL               
      ,CLAMONRET               
      ,CENTALTA                
      ,CUENTA                  
      ,IMPPROP                 
      ,ACCEMICRE               
      ,ACCEMIDEB               
      ,ACCMERCH                
      ,INDPROINC               
      ,FECCADTAR               
      ,CALFRAUDE               
      ,NUMPASIVO               
      ,CODBLQFRA               
      ,TIPOLIN                 
      ,LINREF                  
      ,TIPOLIM                 
      ,FORPAGO                 
      ,RESOLUTOR               
      ,COMISION                
      ,IMPUESTO                
      ,CODENTUMO               
      ,CODOFIUMO               
      ,USUARIOUMO              
      ,CODTERMUMO              
      ,CONTCUR                 
      ,DATADI                  
      ,FECENVIO                
      ,NUMBENCTA               
      ,NUMPLASTICO             
      ,PAN1                    
      ,PANANT                  
      ,CODBLQ                  
      ,FECULTBLQ               
      ,NUMKPIN                 
      ,VISAPHONE               
      ,INDTARPROV              
      ,CODBLQ1                 
      ,DESBLQ                  
      ,DESBLQRED               
      ,INDENVRED               
      ,CODBLQSIA               
      ,INDNOREN                
      ,INDREVER                
      ,INDCMBPAN               
      ,FECULTBLQ1              
      ,TEXBLQ                  
      ,INDBLQEXT               
      ,MOTBLQ                  
      ,FECENVIO1               
      ,CODESTCTA               
      ,GRUPOLIQ                
  FROM SAT.SP_AUTORIZACIONES('L') 
     