drop table IF EXISTS SAT.TBHISMOD;  CREATE TABLE IF NOT EXISTS SAT.TBHISMOD  ( 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
--MPDT068-Histórico de Modificaciones	 	 		
,	CODENT_ENC	VARCHAR	(4)	--Código de entidad
,	OFICINA	VARCHAR	(4)	--Oficina Usuario
,	USUARIO	VARCHAR	(8)	--Usuario que realiza la acción
,	TIPO_ACCION	VARCHAR	(30)	--Acción realizada por el usuario
,	TIPO_REGISTRO	VARCHAR	(1)	--REGISTRO DETALLE (alfanumerico 2300)
--1 - Log Movimientos formato  ATLOGMOV	 	 		
--2 - Histórico Modificaciones formato ATHISMOD	 	 		
--DETALLE DE COLUMNAS ATHISMOD	 	 		
,	CODENT	VARCHAR	(4)	--CÓDIGO DE ENTIDAD
,	NOMBRETAREA	VARCHAR	(20)	--NOMBRE DE TAREA (VER ATTIPMOV)
,	ORIGENOPE	VARCHAR	(4)	--ORIGEN OPERACIÓN (VER ATORIGEN)
,	FECHATAREA	DATE		--FECHA DEL SISTEMA
,	HORATAREA	TIME		--HORA DEL SISTEMA
,	SESIONTAREA	DECIMAL	(5,0)	--NÚMERO DE SESIÓN
,	INDACTUBD	DECIMAL	(2,0)	--INDICADOR DE ACTUALIZACIÓN DE BASE DE DATOS
,	CODENTUMO	VARCHAR	(4)	--ENTIDAD ÚLTIMA MODIFICACIÓN                          
,	CODOFIUMO	VARCHAR	(4)	--OFICINA ÚLTIMA MODIFICACIÓN                          
,	USUARIOUMO	VARCHAR	(8)	--USUARIO ÚLTIMA MODIFICACIÓN                          
,	CODTERMUMO	VARCHAR	(8)	--TERMINAL ÚLTIMA MODIFICACIÓN                         
,	CONTCUR	Timestamp		--CONTROL DE CONCURRENCIA                              
,	TABLA	VARCHAR	(7)	--NOMBRE DE LA TABLA
,	FILLER1	VARCHAR	(2186)	--FILLER
); COMMIT;	 	 