drop table IF EXISTS STG_SAT.TBLOGMOV;  
CREATE TABLE IF NOT EXISTS "STG_SAT"."TBLOGMOV" (
	"CODENT_ENC" VARCHAR(4) NULL ,
	"OFICINA" VARCHAR(4) NULL ,
	"USUARIO" VARCHAR(8) NULL ,
	"TIPO_ACCION" VARCHAR(30) NULL ,
	"TIPO_REGISTRO" VARCHAR(1) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"NUMSECHIS" DECIMAL(15,0) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"CODCOM" VARCHAR(15) NULL ,
	"FECHAMOD" VARCHAR(10) NULL ,
	"HORAMOD" VARCHAR(8) NULL ,
	"TIPACCES" DECIMAL(1,0) NULL ,
	"PROCESO" VARCHAR(10) NULL ,
	"DESPROCESO" VARCHAR(30) NULL ,
	"DATOMOD" VARCHAR(2) NULL ,
	"MOTIVO" VARCHAR(2) NULL ,
	"CANALMOD" VARCHAR(2) NULL ,
	"CODENTUMO" VARCHAR(4) NULL ,
	"CODOFIUMO" VARCHAR(4) NULL ,
	"USUARIOUMO" VARCHAR(8) NULL ,
	"CODTERMUMO" VARCHAR(8) NULL ,
	"CONTCUR" VARCHAR(26) NULL ,
	"TABLA" VARCHAR(3) NULL ,
	"FILLER1" VARCHAR(2106) NULL 
)COMMIT;


