drop table IF EXISTS STG_SAT.TBLOGMOV;  CREATE TABLE IF NOT EXISTS STG_SAT.TBLOGMOV  (
--LOG DE MOVIMIENTOS	 	 		
	CODENT_ENC	VARCHAR	(4)	--Código de entidad
,	OFICINA	VARCHAR	(4)	--Oficina Usuario
,	USUARIO	VARCHAR	(8)	--Usuario que realiza la acción
,	TIPO_ACCION	VARCHAR	(30)	--Acción realizada por el usuario
,	TIPO_REGISTRO	VARCHAR	(1)	--REGISTRO DETALLE (alfanumerico 2300)
--1 - Log Movimientos formato  ATLOGMOV	 	 		
--2 – Histórico Modificaciones formato ATHISMOD	 	 		
--DETALLE DE COLUMNAS ATHISMOD	 	 		
,	CODENT	VARCHAR	(4)	--CÓDIGO DE ENTIDAD
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA CUENTA DE TARJETA
,	CUENTA	VARCHAR	(12)	--CUENTA DE TARJETA
,	NUMSECHIS	DECIMAL	(15,0)	--NÚMERO SECUENCIAL DEL HISTÓRICO
,	PAN	VARCHAR	(22)	--PAN DE LA TARJETA
,	CODCOM	VARCHAR	(15)	--CÓDIGO DE COMERCIO
,	FECHAMOD	DATE		--FECHA DE MODIFICACIÓN
,	HORAMOD	TIME		--HORA DE MODIFICACIÓN
,	TIPACCES	DECIMAL	(1,0)	--TIPO DE ACCESO:
--0 – CUENTA DE TARJETA	 	 		
--1 – TARJETA	 	 		
--2 – COMERCIO	 	 		
,	PROCESO	VARCHAR	(10)	--NOMBRE DEL PROCESO QUE REALIZÓ LA MODIFICACIÓN
,	DESPROCESO	VARCHAR	(30)	--DESCRIPCIÓN DEL PROCESO O FUNCIÓN
,	DATOMOD	VARCHAR	(2)	--DATO MODIFICADO (BANCOS, BLOQUEOS, …)
,	MOTIVO	VARCHAR	(2)	--MOTIVO DE LA MODIFICACIÓN
,	CANALMOD	VARCHAR	(2)	--CANAL DE LA MODIFICACIÓN (EN PERSONA, TELÉFONO …)
,	CODENTUMO	VARCHAR	(4)	--ENTIDAD ÚLTIMA MODIFICACIÓN                          
,	CODOFIUMO	VARCHAR	(4)	--OFICINA ÚLTIMA MODIFICACIÓN                          
,	USUARIOUMO	VARCHAR	(8)	--USUARIO ÚLTIMA MODIFICACIÓN                          
,	CODTERMUMO	VARCHAR	(8)	--TERMINAL ÚLTIMA MODIFICACIÓN                         
,	CONTCUR	Timestamp		--CONTROL DE CONCURRENCIA                              
,	TABLA	VARCHAR	(3)	--NOMBRE DE TABLA MODIFICADA
,	FILLER1	VARCHAR	(2106)	--FILLER
); COMMIT;	 	 		
