drop table IF EXISTS STG_SAT.TBHISMOD;  
CREATE TABLE IF NOT EXISTS "STG_SAT"."TBHISMOD" (
	"CODENT_ENC" VARCHAR(4) NULL ,
	"OFICINA" VARCHAR(4) NULL ,
	"USUARIO" VARCHAR(8) NULL ,
	"TIPO_ACCION" VARCHAR(30) NULL ,
	"TIPO_REGISTRO" VARCHAR(1) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"NOMBRETAREA" VARCHAR(20) NULL ,
	"ORIGENOPE" VARCHAR(4) NULL ,
	"FECHATAREA" VARCHAR(10) NULL ,
	"HORATAREA" VARCHAR(8) NULL ,
	"SESIONTAREA" DECIMAL(5,0) NULL ,
	"INDACTUBD" DECIMAL(2,0) NULL ,
	"CODENTUMO" VARCHAR(4) NULL ,
	"CODOFIUMO" VARCHAR(4) NULL ,
	"USUARIOUMO" VARCHAR(8) NULL ,
	"CODTERMUMO" VARCHAR(8) NULL ,
	"CONTCUR" VARCHAR(26) NULL ,
	"TABLA" VARCHAR(7) NULL ,
	"FILLER1" VARCHAR(2186) NULL 
)COMMIT;


