drop table IF EXISTS "SAT"."ATINTCAB";
COMMIT;
CREATE TABLE "SAT"."ATINTCAB" (
	"IDENTIFICADOR_MALLA" INTEGER NULL ,
	"IDENTIFICADOR_EJECUCION" INTEGER NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"NSECFIC" VARCHAR(10) NULL ,
	"TIPOCINTA" VARCHAR(2) NULL ,
	"TIPOREG" VARCHAR(1) NULL ,
	"FECENVIO" VARCHAR(10) NULL ,
	"HORAENVIO" VARCHAR(8) NULL ,
	"NUMREGTOT" DECIMAL(12,0) NULL ,
	"FILLER_TMP" VARCHAR(61) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT1" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"TIPOREG1" VARCHAR(2) NULL ,
	"OTROSDATOSCAB" VARCHAR(857) NULL ,
	"ESTADOCINTA" VARCHAR(1) NULL ,
	"VALIDACION" VARCHAR(1) NULL 
);
COMMIT;
