drop table IF EXISTS CNF.VERSION_OBJETOS;  
create table IF NOT EXISTS CNF.VERSION_OBJETOS (
 OBJECT_NAME varchar(100)
,OBJECT_USER varchar(20)
,VERSION_COMMIT VARCHAR(100)
,VERSION_CODE VARCHAR(20)
,VERSION_DATE DATETIME
,CRDATE DATETIME null default getdate()
,CRUSER varchar(20) null default user_name()
)
;
COMMIT;
