--- creacion de grupo de usuarios SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'SAT')
BEGIN
CREATE USER SAT 
FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

--- creacion de grupo de usuarios CNF
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'CNF')
BEGIN
CREATE USER CNF
FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

drop table IF EXISTS "CNF"."MALLAS";
COMMIT;

CREATE TABLE "CNF"."MALLAS" (
	"IDENTIFICADOR_MALLA" INTEGER NULL  DEFAULT AUTOINCREMENT,
	"NOMBRE_MALLA" VARCHAR(100) NULL ,
	"DESCRIPCION" VARCHAR(500) NULL ,
	"ENCABEZADO" BIT NULL,
	"CONTROL_FECHA" BIT NULL
);
COMMIT;

drop table IF EXISTS "CNF"."MALLAS_EJECUCION";
COMMIT;
CREATE TABLE "CNF"."MALLAS_EJECUCION" (
	"IDENTIFICADOR_MALLA" INTEGER NULL ,
	"IDENTIFICADOR_EJECUCION" INTEGER NULL  DEFAULT AUTOINCREMENT,
	"NOMBRE_ARCHIVO" VARCHAR(100) NULL ,
	"ESTADO" VARCHAR(20) NULL ,
	"REPROCESO" BIT NOT NULL ,
	"NUM_FILAS_INS" DECIMAL(15,0) NULL ,
	"FECHA_CARGA" "datetime" NULL 
) 
COMMIT;

drop table IF EXISTS "SAT"."ATINTCAB";
COMMIT;
CREATE TABLE "SAT"."ATINTCAB" (
	"IDENTIFICADOR_MALLA" INTEGER NULL ,
	"IDENTIFICADOR_EJECUCION" INTEGER NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"NSECFIC" VARCHAR(10) NULL ,
	"TIPOCINTA" VARCHAR(2) NULL ,
	"TIPOREG" VARCHAR(1) NULL ,
	"FECENVIO" DATE NULL ,
	"HORAENVIO" VARCHAR(8) NULL ,
	"NUMREGTOT" DECIMAL(12,0) NULL ,
	"FILLER_TMP" VARCHAR(61) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT1" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"TIPOREG1" VARCHAR(2) NULL ,
	"OTROSDATOSCAB" VARCHAR(857) NULL ,
	"ESTADOCINTA" VARCHAR(1) NULL ,
	"VALIDACION" VARCHAR(1) NULL 
);
COMMIT;

-- Inserts
INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('MPJ38260','Posiciones credito',1,NULL);
INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('MPJ45021','Impresión Extracto Compra en Cuotas',1,NULL);
INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('MPJ51151','Impresiones Extracto de Credito',1,NULL);
INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('PPJ6110N','Nuevas Operaciones Diarias',1,NULL);
INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('PCJA84A88','Autorizaciones',0,1);
INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('MPJC8010','Documentos Identificativos de una Persona (titulares)',0,1);
INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('MPJ58091','Envío de tarjetas próximas a vencer',1,NULL);
INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('MPJ15005','Subsistema Contable Conceptos Contables',0,1);
INSERT INTO "CNF"."MALLAS" ("NOMBRE_MALLA","DESCRIPCION","ENCABEZADO","CONTROL_FECHA") VALUES('PCJ15015N','Subsistema Contable Apuntes',0,1)
 
------------------------------------------------
---- CONTROL DE VERSION ------------------------
------------------------------------------------
create table IF NOT EXISTS CNF.VERSION_OBJETOS (
 NOMBRE_MALLA varchar(100)
,OBJECT_NAME varchar(100)
,OBJECT_USER varchar(20)
,VERSION_COMMIT VARCHAR(100)
,VERSION_CODE VARCHAR(20)
,VERSION_DATE DATETIME
,CRDATE DATETIME null default getdate()
,CRUSER varchar(20) null default user_name()
)
;
COMMIT;

declare 
 @NOMBRE_MALLA varchar(100)
,@OBJECT_NAME varchar(100)
,@OBJECT_USER varchar(20)
,@VERSION_COMMIT VARCHAR(100)
,@VERSION_CODE VARCHAR(20)
,@VERSION_DATE DATETIME 
,@CRDATE DATETIME

select 
 @NOMBRE_MALLA = 'N/A.CONTROL INTERNO'
,@OBJECT_NAME = 'MALLAS_EJECUCION'
,@OBJECT_USER = 'CNF'
,@VERSION_COMMIT = '40bb5be51db41a51f139c6f2115395a340f82089'
,@VERSION_CODE = '40bb5be'
,@VERSION_DATE = '2019/02/18 6:56:42 PM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @OBJECT_NAME = 'MALLAS'
,@OBJECT_USER = 'CNF'
,@VERSION_COMMIT = '04f3eb8aaa49f4d90576ad77cdab34f030c0efcf'
,@VERSION_CODE = '04f3eb8'
,@VERSION_DATE = 'February 6, 2019 8:48:49 PM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @OBJECT_NAME = 'ATINTCAB'
,@OBJECT_USER = 'SAT'
,@VERSION_COMMIT = '12aa999451dcf490411f2a634b208d2bba5f1fcb'
,@VERSION_CODE = '12aa999'
,@VERSION_DATE = 'February 7, 2019 11:05:14 AM'
,@CRDATE = NULL


SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 


COMMIT;
