drop table IF EXISTS STG_SAT.TBPLASTI;  
CREATE TABLE IF NOT EXISTS "STG_SAT"."TBPLASTI" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"NUMPLASTICO" DECIMAL(12,0) NULL ,
	"FECENVEST" VARCHAR(10) NULL ,
	"FECRECEST" VARCHAR(10) NULL ,
	"FECACUSER" VARCHAR(10) NULL ,
	"FECULTREN" VARCHAR(10) NULL ,
	"FECRECTAR" VARCHAR(10) NULL ,
	"FCORETTAR" VARCHAR(10) NULL ,
	"HCORETTAR" VARCHAR(8) NULL ,
	"CONDEST" VARCHAR(3) NULL ,
	"FILLER_0001" VARCHAR(777) NULL
) COMMIT;


	
