if exists (select 1 from CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_CONTROVERSIAS')
BEGIN
  DELETE CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_CONTROVERSIAS'
END
INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") 
VALUES('JOB_CASE_CENTER_CTV','CC_CONTROVERSIAS',NULL,0);
COMMIT;
