DROP TABLE IF EXISTS "STG_SAT"."CUS_ADM_SCORE";  
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."CUS_ADM_SCORE" (
	"name" VARCHAR(1024) NULL ,
	"name_1" VARCHAR(1024) NULL ,
	"id" VARCHAR(1024) NULL ,
	"v" VARCHAR(1024) NULL 
);

COMMIT;
