IF EXISTS(SELECT 1 FROM CNF.CAT_JOBS WHERE NOMBRE_JOB = 'JOB_ADM_SCORE' AND NOMBRE_TABLA = 'CUS_ADM_SCORE')
BEGIN
  DELETE CNF.CAT_JOBS WHERE NOMBRE_JOB = 'JOB_ADM_SCORE' AND NOMBRE_TABLA = 'CUS_ADM_SCORE'
END
COMMIT;
INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") 
VALUES('JOB_ADM_SCORE','CUS_ADM_SCORE',NULL,0);
COMMIT;