if exists (select 1 from CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_SOLICITUDES_TARJETAS')
BEGIN
  DELETE CNF.CAT_JOBS WHERE NOMBRE_TABLA = 'CC_SOLICITUDES_TARJETAS'
END
INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") 
VALUES('JOB_CASE_CENTER_STJ','CC_SOLICITUDES_TARJETAS',NULL,0);
COMMIT;
