drop proc SAT.SP_BUCKET_MORA;
CREATE proc SAT.SP_BUCKET_MORA
 @OPERACION CHAR(1) DEFAULT 'V'
,@FECENVIO DATE DEFAULT NULL
,@FECENVIOFIN DATE DEFAULT NULL
as
declare 
  @CUENTA varchar(12)
, @BUCKET_MORA INT
, @MESACTUAL INT
, @FECHA_MESACTUAL DATE
, @FECHA_INI DATE
, @FECHA_FIN DATE
, @MONTO_MORA DECIMAL(17,2)
, @MONTO_MORA_MESANT DECIMAL(17,2)
, @FECENVIO_TRABAJO DATE

SELECT @OPERACION = UPPER(@OPERACION)
IF @OPERACION NOT IN ('V','C','L','G','B') SELECT @OPERACION = 'V'
-- TIPOS DE OPERACION:
-- V: LEER LOS RESULTADOS DE LAS TABLAS BASE. LOS RESULTADOS NO SE ALMACENAN
--     SE LEE DE LAS TABLAS DIRECTAMENTE Y EL RESULTADO SE DESPLIEGA. 
--     DEPENDE DE LOS PARAMETROS DE FECHAS, SI NO SE ENVIAN LEE TODAS LAS FECHAS
-- C: CREAR LA ESTRUCTURA DE LA TABLA. 
--     NO TIENE OUTPUT DE RESULTADO. LA TABLA SE LLAMA TB_BALANCE_SALDOS_DIARIOS
-- L: LEER LOS RESULTADOS DE LA TABLA FIJA TB_BALANCE_SALDOS_DIARIOS. 
--     DEPENDE DE LOS PARAMETROS DE FECHAS, SI NO SE ENVIAN LEE TODAS LAS FECHAS
-- G: BORRA Y GRABA NUEVAMENTE EL LA TABLA TB_BALANCE_SALDOS_DIARIOS. SI NO EXISTE LA CREA
-- B: BORRA DE LA TABLA TB_BALANCE_SALDOS_DIARIOS. SI LA TABLA NO EXISTE NO DA ERROR
---------------------------------------------------------
-- CONDICIONES DE FECHAS:
-- SI NO SE ENVIAN FECHAS SE TOMA INICIAL Y FINAL = 1 ENE 0001
-- SI NO SE ENVIA LA FECHA FINAL, LA FECHA FINAL SE IGUALA A LA FECHA INICIAL
-- SI LA FECHA INICIAL ES MAYOR A LA FINAL, LA FECHA FINAL SE IGUALA A LA FECHA INICIAL
-- SI LA FECHA INICIAL Y FINAL SON NULL (NO SE ENVIAN) SE TOMAN LOS RANGOS DEL 01 ENE 0001 AL 31 DIC 9999
---------------------------------------------------------
/****************
INDICES ASOCIADOS A LA VISTA:
-----------------------------
create HG index if not exists idx_HG_PCENVPO1_RI_CUENTA on SAT.PCENVPO1_RI(CUENTA)
create HG index if not exists idx_HG_PCENVPO1_RI_FECVENMOV on SAT.PCENVPO1_RI(FECVENMOV)
*******************/
IF @FECENVIO IS NULL
BEGIN
  SELECT @FECHA_INI = '00010101'
END
ELSE
BEGIN
  SELECT @FECHA_INI = @FECENVIO
END

IF @FECENVIOFIN IS NULL
BEGIN
  IF @FECENVIO IS NULL
    SELECT @FECHA_FIN = '99991231'
  ELSE  
    SELECT @FECHA_FIN = @FECHA_INI
END
ELSE
BEGIN
  SELECT @FECHA_FIN = @FECENVIOFIN
END
IF @FECHA_INI > @FECHA_FIN
  SELECT @FECHA_FIN = @FECHA_INI

CREATE TABLE #BUCKET_MORA (FECENVIO DATE, IDENTIFICADOR_EJECUCION INT, CUENTA VARCHAR(12), DIASMORA DECIMAL(5,0) NULL, BUCKET_MORA INT NULL 
                          ,MESES1 DECIMAL(17,2) NULL, MESES2 DECIMAL(17,2) NULL, MESES3 DECIMAL(17,2) NULL, MESES4 DECIMAL(17,2) NULL
                          ,MESES5 DECIMAL(17,2) NULL, MESES6 DECIMAL(17,2) NULL, MESES7 DECIMAL(17,2) NULL
                          ,MONTOMES1 DECIMAL(17,2) NULL, MONTOMES2 DECIMAL(17,2) NULL, MONTOMES3 DECIMAL(17,2) NULL, MONTOMES4 DECIMAL(17,2) NULL
                          ,MONTOMES5 DECIMAL(17,2) NULL, MONTOMES6 DECIMAL(17,2) NULL, MONTOMES7 DECIMAL(17,2) NULL)

if @OPERACION IN ('C','G','L') --  C = CREA ESTRUCTURA DE TABLA FIJA 
--- G = GRABA DATOS EN ESTRUCTURA DE TABLA FIJA.. SI LA TABLA NO EXISTE LA CREA..
--- L = LEE DATOS DE TABLA FIJA.. SI LA TABLA NO EXISTE LA CREA..
BEGIN
  IF EXISTS(SELECT 1 from sysobjects where name = 'TB_BUCKET_MORA' AND user_name(uid) = 'SAT') AND @OPERACION = 'C'
  BEGIN
    return 0
  END
  IF NOT EXISTS(SELECT 1 from sysobjects where name = 'TB_BUCKET_MORA' AND user_name(uid) = 'SAT')
  BEGIN
    SELECT FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA, 
           MESES1, MESES2, MESES3, MESES4,
           MESES5, MESES6, MESES7
      INTO SAT.TB_BUCKET_MORA FROM #BUCKET_MORA WHERE 1=2
    IF @OPERACION = 'L'
    BEGIN
      RETURN 0
    END
  END
  IF @OPERACION = 'C'
  BEGIN
     RETURN 0
  END
END -- 'C'

IF @OPERACION = 'L' -- LEE DATOS DE LA TABLA FIJA
BEGIN
  SELECT FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA, 
           MESES1, MESES2, MESES3, MESES4,
           MESES5, MESES6, MESES7
    FROM SAT.TB_BUCKET_MORA
   WHERE FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
  RETURN 0
END -- OPERACION = 'L'

IF @OPERACION = 'B'  --- BORRA DATOS DE LA TABLA FIJA
BEGIN
  IF NOT EXISTS(SELECT 1 from sysobjects where name = 'TB_BUCKET_MORA' AND user_name(uid) = 'SAT')
  BEGIN
    return 0
  END
  DELETE SAT.TB_BUCKET_MORA
   WHERE FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
  RETURN 0
END -- OPERACION = 'B'

create HG index if not exists idx_HG_BUCKET_MORA_CUENTA on #BUCKET_MORA(CUENTA)
create HG index if not exists idx_HG_BUCKET_MORA_FECENVIO on #BUCKET_MORA(FECENVIO)

SELECT DISTINCT 
  AT.FECENVIO,
  IC.IDENTIFICADOR_EJECUCION,
  IC.CUENTA,
  IC.DIASMORA,
(CASE WHEN DIASMORA IS NULL THEN 0
             WHEN DIASMORA BETWEEN 1 AND 30 THEN 1
             WHEN DIASMORA BETWEEN 31 AND 60 THEN 2
             WHEN DIASMORA BETWEEN 61 AND 90 THEN 3
             WHEN DIASMORA BETWEEN 91 AND 120 THEN 4
             WHEN DIASMORA BETWEEN 121 AND 150 THEN 5
             WHEN DIASMORA BETWEEN 151 AND 179 THEN 6
             ELSE 7
        END) AS BUCKET_MORA
  INTO #BUCKET_MORA_IC
  FROM SAT.PCENVPO1_IC IC, 
       SAT.ATINTCAB ATCI,
       SAT.ATINTCAB AT,
       SAT.PCENVPO1_CU A
 WHERE A.IDENTIFICADOR_EJECUCION = AT.IDENTIFICADOR_EJECUCION
   AND IC.IDENTIFICADOR_EJECUCION = ATCI.IDENTIFICADOR_EJECUCION
   AND AT.FECENVIO = ATCI.FECENVIO
   AND AT.FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN
--   AND AT.FECENVIO = '20190306'
--   AND IC.CUENTA in ('000000000004','000000000010','000000000005','000000000011')

INSERT #BUCKET_MORA (FECENVIO ,IDENTIFICADOR_EJECUCION,CUENTA, DIASMORA, BUCKET_MORA)
SELECT FECENVIO ,IDENTIFICADOR_EJECUCION,CUENTA, DIASMORA, BUCKET_MORA
  FROM #BUCKET_MORA_IC

declare my_cursor cursor for 
SELECT FECENVIO ,CUENTA, BUCKET_MORA
 FROM #BUCKET_MORA_IC
open my_cursor

fetch next my_cursor into @FECENVIO_TRABAJO, @CUENTA, @BUCKET_MORA

while(@@sqlstatus = 0)
begin
  --INSERT #BM(CUENTA, BUCKET_MORA) SELECT @CUENTA, @BUCKET_MORA
  SELECT @MESACTUAL = 1
  WHILE @BUCKET_MORA IS NOT NULL AND (@MESACTUAL <= @BUCKET_MORA)
  BEGIN

    SELECT @FECHA_MESACTUAL = MAX(FECVENMOV)
      FROM SAT.PCENVPO1_RI RI
         , SAT.ATINTCAB ATRI
     WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
       AND ATRI.FECENVIO = @FECENVIO_TRABAJO
       AND RI.CUENTA = @CUENTA

    SELECT @FECHA_MESACTUAL = CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,@FECHA_MESACTUAL)) + '-' + CONVERT(VARCHAR,DATEPART(MM,@FECHA_MESACTUAL)) + '-01')
    SELECT @FECHA_MESACTUAL = DATEADD(MM,(@BUCKET_MORA-@MESACTUAL)*-1,@FECHA_MESACTUAL)
    SELECT @FECHA_MESACTUAL = DATEADD(MM,1,@FECHA_MESACTUAL)
    SELECT @FECHA_MESACTUAL = DATEADD(SS,-1,@FECHA_MESACTUAL)
    IF @FECHA_MESACTUAL > @FECENVIO_TRABAJO
      SELECT @FECHA_MESACTUAL = @FECENVIO_TRABAJO
    
    SELECT @FECHA_MESACTUAL = MAX(FECVENMOV)
      FROM SAT.PCENVPO1_RI RI
         , SAT.ATINTCAB ATRI
     WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
       AND ATRI.FECENVIO = @FECENVIO_TRABAJO
       AND RI.CUENTA = @CUENTA
       AND RI.FECVENMOV <= @FECHA_MESACTUAL
    
    SELECT @MONTO_MORA = MAX(IMPAPL)
      FROM SAT.PCENVPO1_RI RI
         , SAT.ATINTCAB ATRI
     WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
       AND ATRI.FECENVIO = @FECENVIO_TRABAJO
       AND RI.CUENTA = @CUENTA
       AND RI.FECVENMOV = @FECHA_MESACTUAL
    
    IF @MESACTUAL = 1
    BEGIN
      UPDATE #BUCKET_MORA
         SET MESES1 = @MONTO_MORA
           , MONTOMES1 = @MONTO_MORA
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA
    END    
    IF @MESACTUAL = 2
    BEGIN
      SELECT @MONTO_MORA_MESANT = MONTOMES1
        FROM #BUCKET_MORA 
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA

      UPDATE #BUCKET_MORA
         SET MESES2 = @MONTO_MORA - @MONTO_MORA_MESANT
           , MONTOMES2 = @MONTO_MORA
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA
    END    
    IF @MESACTUAL = 3
    BEGIN
      SELECT @MONTO_MORA_MESANT = MONTOMES2
        FROM #BUCKET_MORA 
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA

      UPDATE #BUCKET_MORA
         SET MESES3 = @MONTO_MORA - @MONTO_MORA_MESANT
           , MONTOMES3 = @MONTO_MORA
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA
    END    
    IF @MESACTUAL = 4
    BEGIN
      SELECT @MONTO_MORA_MESANT = MONTOMES3
        FROM #BUCKET_MORA 
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA

      UPDATE #BUCKET_MORA
         SET MESES4 = @MONTO_MORA - @MONTO_MORA_MESANT
           , MONTOMES4 = @MONTO_MORA
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA
    END    
    IF @MESACTUAL = 5
    BEGIN
      SELECT @MONTO_MORA_MESANT = MONTOMES4
        FROM #BUCKET_MORA 
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA

      UPDATE #BUCKET_MORA
         SET MESES5 = @MONTO_MORA - @MONTO_MORA_MESANT
           , MONTOMES5 = @MONTO_MORA
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA
    END    
    IF @MESACTUAL = 6
    BEGIN
      SELECT @MONTO_MORA_MESANT = MONTOMES5
        FROM #BUCKET_MORA 
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA

      UPDATE #BUCKET_MORA
         SET MESES6 = @MONTO_MORA - @MONTO_MORA_MESANT
           , MONTOMES6 = @MONTO_MORA
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA
    END    
    IF @MESACTUAL = 7
    BEGIN
      SELECT @MONTO_MORA_MESANT = MONTOMES6
        FROM #BUCKET_MORA 
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA

      UPDATE #BUCKET_MORA
         SET MESES7 = @MONTO_MORA - @MONTO_MORA_MESANT
           , MONTOMES7 = @MONTO_MORA
       WHERE FECENVIO = @FECENVIO_TRABAJO
         AND CUENTA = @CUENTA
    END    
    
    SELECT @MESACTUAL = @MESACTUAL + 1
  END
  fetch next my_cursor into @FECENVIO_TRABAJO, @CUENTA, @BUCKET_MORA
End
close my_cursor
deallocate cursor my_cursor 

IF @OPERACION = 'V'
BEGIN
  SELECT FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA, 
           MESES1, MESES2, MESES3, MESES4,
           MESES5, MESES6, MESES7
    FROM #BUCKET_MORA
END -- 'V'

if @OPERACION = 'G' --- GRABA DATOS EN ESTRUCTURA DE TABLA FIJA.. SI EXISTEN PRIMERO LOS BORRA.. SI LA TABLA NO EXISTE LA CREA..
BEGIN
  DELETE SAT.TB_BUCKET_MORA
   WHERE FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
  INSERT SAT.TB_BUCKET_MORA
  SELECT FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA, 
           MESES1, MESES2, MESES3, MESES4,
           MESES5, MESES6, MESES7
    FROM #BUCKET_MORA
END -- OPERACION = 'G'

RETURN 0