DROP TABLE IF EXISTS SAT.TB_BUCKET_MORA;
COMMIT;
CREATE TABLE IF NOT EXISTS SAT.TB_BUCKET_MORA (FECENVIO DATE, IDENTIFICADOR_EJECUCION INT, CUENTA VARCHAR(12), DIASMORA DECIMAL(5,0) NULL, BUCKET_MORA INT DEFAULT 0 NULL 
                          ,MONTO_MORAINICIAL DECIMAL(17,2) DEFAULT 0 NULL, MORA1 DECIMAL(17,2) DEFAULT 0 NULL, MORA2 DECIMAL(17,2) DEFAULT 0 NULL, MORA3 DECIMAL(17,2) DEFAULT 0 NULL
                          ,MORA4 DECIMAL(17,2) DEFAULT 0 NULL, MORA5 DECIMAL(17,2) DEFAULT 0 NULL, MORA6 DECIMAL(17,2) DEFAULT 0 NULL)
COMMIT;