drop proc SAT.SP_BUCKET_MORA;
CREATE proc SAT.SP_BUCKET_MORA
 @OPERACION CHAR(1) DEFAULT 'V'
,@FECENVIO DATE DEFAULT NULL
,@FECENVIOFIN DATE DEFAULT NULL
as
/*
declare 
@OPERACION CHAR(1) 
,@FECENVIO DATE 
,@FECENVIOFIN DATE 
select @OPERACION = 'L'
*/
declare 
  @CUENTA varchar(12)
, @BUCKET_MORA INT
, @MESACTUAL INT
, @FECHA_MESACTUAL DATE
, @FECHA_INI DATE
, @FECHA_FIN DATE
, @MONTO_MORA DECIMAL(17,2)
, @MONTO_MORA_MESANT DECIMAL(17,2)
, @FECENVIO_TRABAJO DATE

SELECT @OPERACION = UPPER(@OPERACION)
IF @OPERACION NOT IN ('V','C','L','G','B') SELECT @OPERACION = 'V'
-- TIPOS DE OPERACION:
-- V: LEER LOS RESULTADOS DE LAS TABLAS BASE. LOS RESULTADOS NO SE ALMACENAN
--     SE LEE DE LAS TABLAS DIRECTAMENTE Y EL RESULTADO SE DESPLIEGA. 
--     DEPENDE DE LOS PARAMETROS DE FECHAS, SI NO SE ENVIAN LEE TODAS LAS FECHAS
-- C: CREAR LA ESTRUCTURA DE LA TABLA. 
--     NO TIENE OUTPUT DE RESULTADO. LA TABLA SE LLAMA TB_BALANCE_SALDOS_DIARIOS
-- L: LEER LOS RESULTADOS DE LA TABLA FIJA TB_BALANCE_SALDOS_DIARIOS. 
--     DEPENDE DE LOS PARAMETROS DE FECHAS, SI NO SE ENVIAN LEE TODAS LAS FECHAS
-- G: BORRA Y GRABA NUEVAMENTE EL LA TABLA TB_BALANCE_SALDOS_DIARIOS. SI NO EXISTE LA CREA
-- B: BORRA DE LA TABLA TB_BALANCE_SALDOS_DIARIOS. SI LA TABLA NO EXISTE NO DA ERROR
---------------------------------------------------------
-- CONDICIONES DE FECHAS:
-- SI NO SE ENVIAN FECHAS SE TOMA INICIAL Y FINAL = 1 ENE 0001
-- SI NO SE ENVIA LA FECHA FINAL, LA FECHA FINAL SE IGUALA A LA FECHA INICIAL
-- SI LA FECHA INICIAL ES MAYOR A LA FINAL, LA FECHA FINAL SE IGUALA A LA FECHA INICIAL
-- SI LA FECHA INICIAL Y FINAL SON NULL (NO SE ENVIAN) SE TOMAN LOS RANGOS DEL 01 ENE 0001 AL 31 DIC 9999
---------------------------------------------------------
/****************
INDICES ASOCIADOS A LA VISTA:
-----------------------------
create HG index if not exists idx_HG_PCENVPO1_RI_CUENTA on SAT.PCENVPO1_RI(CUENTA)
create HG index if not exists idx_HG_PCENVPO1_RI_FECVENMOV on SAT.PCENVPO1_RI(FECVENMOV)
*******************/
IF @FECENVIO IS NULL
BEGIN
  SELECT @FECHA_INI = '00010101'
END
ELSE
BEGIN
  SELECT @FECHA_INI = @FECENVIO
END

IF @FECENVIOFIN IS NULL
BEGIN
  IF @FECENVIO IS NULL
    SELECT @FECHA_FIN = '99991231'
  ELSE  
    SELECT @FECHA_FIN = @FECHA_INI
END
ELSE
BEGIN
  SELECT @FECHA_FIN = @FECENVIOFIN
END
IF @FECHA_INI > @FECHA_FIN
  SELECT @FECHA_FIN = @FECHA_INI

CREATE TABLE #BUCKET_MORA (FECENVIO DATE, IDENTIFICADOR_EJECUCION INT, CUENTA VARCHAR(12), DIASMORA DECIMAL(5,0) NULL, BUCKET_MORA INT DEFAULT 0 NULL 
                          ,MONTO_MORAINICIAL DECIMAL(17,2) DEFAULT 0 NULL, MORA1 DECIMAL(17,2) DEFAULT 0 NULL, MORA2 DECIMAL(17,2) DEFAULT 0 NULL, MORA3 DECIMAL(17,2) DEFAULT 0 NULL
                          ,MORA4 DECIMAL(17,2) DEFAULT 0 NULL, MORA5 DECIMAL(17,2) DEFAULT 0 NULL, MORA6 DECIMAL(17,2) DEFAULT 0 NULL,
                           MES1 DECIMAL(17,2) DEFAULT 0, MES2 DECIMAL(17,2) DEFAULT 0, 
                           MES3 DECIMAL(17,2) DEFAULT 0, MES4 DECIMAL(17,2) DEFAULT 0, MES5 DECIMAL(17,2) DEFAULT 0, MES6 DECIMAL(17,2) DEFAULT 0,
                           MES7 DECIMAL(17,2) DEFAULT 0)

if @OPERACION IN ('C','G','L') --  C = CREA ESTRUCTURA DE TABLA FIJA 
--- G = GRABA DATOS EN ESTRUCTURA DE TABLA FIJA.. SI LA TABLA NO EXISTE LA CREA..
--- L = LEE DATOS DE TABLA FIJA.. SI LA TABLA NO EXISTE LA CREA..
BEGIN
  IF EXISTS(SELECT 1 from sysobjects where name = 'TB_BUCKET_MORA' AND user_name(uid) = 'SAT') AND @OPERACION = 'C'
  BEGIN
    return 0
  END
  IF NOT EXISTS(SELECT 1 from sysobjects where name = 'TB_BUCKET_MORA' AND user_name(uid) = 'SAT')
  BEGIN
    SELECT FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA, 
           MONTO_MORAINICIAL, MORA1, MORA2, MORA3,
           MORA4, MORA5, MORA6
      INTO SAT.TB_BUCKET_MORA FROM #BUCKET_MORA WHERE 1=2
    IF @OPERACION = 'L'
    BEGIN
      RETURN 0
    END
  END
  IF @OPERACION = 'C'
  BEGIN
     RETURN 0
  END
END -- 'C'

IF @OPERACION = 'L' -- LEE DATOS DE LA TABLA FIJA
BEGIN
  SELECT FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA, 
           MONTO_MORAINICIAL, MORA1, MORA2, MORA3,
           MORA4, MORA5, MORA6
    FROM SAT.TB_BUCKET_MORA
   WHERE FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
  RETURN 0
END -- OPERACION = 'L'

IF @OPERACION = 'B'  --- BORRA DATOS DE LA TABLA FIJA
BEGIN
  IF NOT EXISTS(SELECT 1 from sysobjects where name = 'TB_BUCKET_MORA' AND user_name(uid) = 'SAT')
  BEGIN
    return 0
  END
  DELETE SAT.TB_BUCKET_MORA
   WHERE FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
  RETURN 0
END -- OPERACION = 'B'

create HG index if not exists idxT_HG_BUCKET_MORA_CUENTA on #BUCKET_MORA(CUENTA)
create HG index if not exists idxT_HG_BUCKET_MORA_FECENVIO on #BUCKET_MORA(FECENVIO)

-- DETERMINO CUENTAS, DIAS MORA Y CALCULO BUCKET DE MORA
SELECT DISTINCT 
  AT.FECENVIO,
  IC.IDENTIFICADOR_EJECUCION,
  IC.CUENTA,
  IC.DIASMORA,
(CASE WHEN DIASMORA IS NULL THEN 0
             WHEN DIASMORA BETWEEN 1 AND 30 THEN 1
             WHEN DIASMORA BETWEEN 31 AND 60 THEN 2
             WHEN DIASMORA BETWEEN 61 AND 90 THEN 3
             WHEN DIASMORA BETWEEN 91 AND 120 THEN 4
             WHEN DIASMORA BETWEEN 121 AND 150 THEN 5
             WHEN DIASMORA BETWEEN 151 AND 179 THEN 6
             ELSE 7
        END) AS BUCKET_MORA
  INTO #BUCKET_MORA_IC
  FROM SAT.PCENVPO1_IC IC, 
       SAT.ATINTCAB ATCI,
       SAT.ATINTCAB AT,
       SAT.PCENVPO1_CU A
 WHERE A.IDENTIFICADOR_EJECUCION = AT.IDENTIFICADOR_EJECUCION
   AND IC.IDENTIFICADOR_EJECUCION = ATCI.IDENTIFICADOR_EJECUCION
   AND AT.FECENVIO = ATCI.FECENVIO
   AND AT.FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN
--   AND AT.FECENVIO = '20190306'
--   AND IC.CUENTA in ('000000000004','000000000010','000000000005','000000000011')
--   AND IC.CUENTA in ('000000000005')

IF (SELECT COUNT(1) FROM #BUCKET_MORA_IC) <= 0
  RETURN 0;

-- OBTENER TODAS LAS FECHAS QUE PARTICIPAN
CREATE TABLE #FECHAS (IDENTIFICADOR_EJECUCION INTEGER, FECENVIO DATE, CUENTA VARCHAR(12), BUCKET_MORA INT DEFAULT 0, FECVENMOV DATE, MES1 DECIMAL(17,2) DEFAULT 0, MES2 DECIMAL(17,2) DEFAULT 0, 
                      MES3 DECIMAL(17,2) DEFAULT 0, MES4 DECIMAL(17,2) DEFAULT 0, MES5 DECIMAL(17,2) DEFAULT 0, MES6 DECIMAL(17,2) DEFAULT 0,
                      MES7 DECIMAL(17,2) DEFAULT 0,
                      DATOSMES1 INT DEFAULT 0,
                      DATOSMES2 INT DEFAULT 0,
                      DATOSMES3 INT DEFAULT 0,
                      DATOSMES4 INT DEFAULT 0,
                      DATOSMES5 INT DEFAULT 0,
                      DATOSMES6 INT DEFAULT 0,
                      DATOSMES7 INT DEFAULT 0,
                      ESTADO_FECHA INT DEFAULT 0)  --- 0 = PENDIENTE DE ACTUALIZAR    1 = ACTUALIZADA

INSERT #FECHAS (IDENTIFICADOR_EJECUCION , FECENVIO, CUENTA , BUCKET_MORA, FECVENMOV)
select RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA, max(RI.FECVENMOV) 
  from SAT.PCENVPO1_RI RI
     , #BUCKET_MORA_IC IC
     , SAT.ATINTCAB ATRI
 WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
   AND ATRI.FECENVIO = IC.FECENVIO
   AND RI.CUENTA = IC.CUENTA
   AND DATEPART(MM,RI.FECVENMOV) = DATEPART(MM,IC.FECENVIO)
   AND DATEPART(YY,RI.FECVENMOV) = DATEPART(YY,IC.FECENVIO)
   AND BUCKET_MORA > 0
GROUP BY RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA

-- OBTENER LOS MONTOS EN BASE A LAS FECHAS
UPDATE #FECHAS
   SET MES1 = RI.IMPAPL
     , DATOSMES1 = 1
     , ESTADO_FECHA = 1
  FROM SAT.PCENVPO1_RI RI
     , #FECHAS F
 WHERE RI.IDENTIFICADOR_EJECUCION = F.IDENTIFICADOR_EJECUCION
   AND RI.CUENTA = F.CUENTA
   AND RI.FECVENMOV = F.FECVENMOV
   AND F.ESTADO_FECHA = 0

INSERT #FECHAS (IDENTIFICADOR_EJECUCION , FECENVIO, CUENTA , BUCKET_MORA, FECVENMOV)
select RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA, max(RI.FECVENMOV) 
  from SAT.PCENVPO1_RI RI
     , #BUCKET_MORA_IC IC
     , SAT.ATINTCAB ATRI
 WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
   AND ATRI.FECENVIO = IC.FECENVIO
   AND RI.CUENTA = IC.CUENTA
   AND DATEPART(MM,RI.FECVENMOV) = DATEPART(MM,DATEADD(SS,-1,DATEADD(MM,0,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND DATEPART(YY,RI.FECVENMOV) = DATEPART(YY,DATEADD(SS,-1,DATEADD(MM,0,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND BUCKET_MORA > 0
GROUP BY RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA

-- OBTENER LOS MONTOS EN BASE A LAS FECHAS
UPDATE #FECHAS
   SET MES2 = RI.IMPAPL
     , DATOSMES2 = 1
     , ESTADO_FECHA = 1
  FROM SAT.PCENVPO1_RI RI
     , #FECHAS F
 WHERE RI.IDENTIFICADOR_EJECUCION = F.IDENTIFICADOR_EJECUCION
   AND RI.CUENTA = F.CUENTA
   AND RI.FECVENMOV = F.FECVENMOV
   AND F.BUCKET_MORA > 0
   AND F.ESTADO_FECHA = 0

INSERT #FECHAS (IDENTIFICADOR_EJECUCION , FECENVIO, CUENTA , BUCKET_MORA, FECVENMOV)
select RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA, max(RI.FECVENMOV) 
  from SAT.PCENVPO1_RI RI
     , #BUCKET_MORA_IC IC
     , SAT.ATINTCAB ATRI
 WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
   AND ATRI.FECENVIO = IC.FECENVIO
   AND RI.CUENTA = IC.CUENTA
   AND DATEPART(MM,RI.FECVENMOV) = DATEPART(MM,DATEADD(SS,-1,DATEADD(MM,-1,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND DATEPART(YY,RI.FECVENMOV) = DATEPART(YY,DATEADD(SS,-1,DATEADD(MM,-1,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND BUCKET_MORA > 0
GROUP BY RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA

-- OBTENER LOS MONTOS EN BASE A LAS FECHAS
UPDATE #FECHAS
   SET MES3 = RI.IMPAPL
     , DATOSMES3 = 1
     , ESTADO_FECHA = 1
  FROM SAT.PCENVPO1_RI RI
     , #FECHAS F
 WHERE RI.IDENTIFICADOR_EJECUCION = F.IDENTIFICADOR_EJECUCION
   AND RI.CUENTA = F.CUENTA
   AND RI.FECVENMOV = F.FECVENMOV
   AND F.BUCKET_MORA > 0
   AND F.ESTADO_FECHA = 0

INSERT #FECHAS (IDENTIFICADOR_EJECUCION , FECENVIO, CUENTA , BUCKET_MORA, FECVENMOV)
select RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA, max(RI.FECVENMOV) 
  from SAT.PCENVPO1_RI RI
     , #BUCKET_MORA_IC IC
     , SAT.ATINTCAB ATRI
 WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
   AND ATRI.FECENVIO = IC.FECENVIO
   AND RI.CUENTA = IC.CUENTA
   AND DATEPART(MM,RI.FECVENMOV) = DATEPART(MM,DATEADD(SS,-1,DATEADD(MM,-2,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND DATEPART(YY,RI.FECVENMOV) = DATEPART(YY,DATEADD(SS,-1,DATEADD(MM,-2,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND BUCKET_MORA > 0
GROUP BY RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA

-- OBTENER LOS MONTOS EN BASE A LAS FECHAS
UPDATE #FECHAS
   SET MES4 = RI.IMPAPL
     , DATOSMES4 = 1
     , ESTADO_FECHA = 1
  FROM SAT.PCENVPO1_RI RI
     , #FECHAS F
 WHERE RI.IDENTIFICADOR_EJECUCION = F.IDENTIFICADOR_EJECUCION
   AND RI.CUENTA = F.CUENTA
   AND RI.FECVENMOV = F.FECVENMOV
   AND F.BUCKET_MORA > 0
   AND F.ESTADO_FECHA = 0

INSERT #FECHAS (IDENTIFICADOR_EJECUCION , FECENVIO, CUENTA , BUCKET_MORA, FECVENMOV)
select RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA, max(RI.FECVENMOV) 
  from SAT.PCENVPO1_RI RI
     , #BUCKET_MORA_IC IC
     , SAT.ATINTCAB ATRI
 WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
   AND ATRI.FECENVIO = IC.FECENVIO
   AND RI.CUENTA = IC.CUENTA
   AND DATEPART(MM,RI.FECVENMOV) = DATEPART(MM,DATEADD(SS,-1,DATEADD(MM,-3,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND DATEPART(YY,RI.FECVENMOV) = DATEPART(YY,DATEADD(SS,-1,DATEADD(MM,-3,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND BUCKET_MORA > 0
GROUP BY RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA

-- OBTENER LOS MONTOS EN BASE A LAS FECHAS
UPDATE #FECHAS
   SET MES5 = RI.IMPAPL
     , DATOSMES5 = 1
     , ESTADO_FECHA = 1
  FROM SAT.PCENVPO1_RI RI
     , #FECHAS F
 WHERE RI.IDENTIFICADOR_EJECUCION = F.IDENTIFICADOR_EJECUCION
   AND RI.CUENTA = F.CUENTA
   AND RI.FECVENMOV = F.FECVENMOV
   AND F.BUCKET_MORA > 0
   AND F.ESTADO_FECHA = 0

INSERT #FECHAS (IDENTIFICADOR_EJECUCION , FECENVIO, CUENTA , BUCKET_MORA, FECVENMOV)
select RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA, max(RI.FECVENMOV) 
  from SAT.PCENVPO1_RI RI
     , #BUCKET_MORA_IC IC
     , SAT.ATINTCAB ATRI
 WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
   AND ATRI.FECENVIO = IC.FECENVIO
   AND RI.CUENTA = IC.CUENTA
   AND DATEPART(MM,RI.FECVENMOV) = DATEPART(MM,DATEADD(SS,-1,DATEADD(MM,-4,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND DATEPART(YY,RI.FECVENMOV) = DATEPART(YY,DATEADD(SS,-1,DATEADD(MM,-4,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND BUCKET_MORA > 0
GROUP BY RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA

-- OBTENER LOS MONTOS EN BASE A LAS FECHAS
UPDATE #FECHAS
   SET MES6 = RI.IMPAPL
     , DATOSMES6 = 1
     , ESTADO_FECHA = 1
  FROM SAT.PCENVPO1_RI RI
     , #FECHAS F
 WHERE RI.IDENTIFICADOR_EJECUCION = F.IDENTIFICADOR_EJECUCION
   AND RI.CUENTA = F.CUENTA
   AND RI.FECVENMOV = F.FECVENMOV
   AND F.BUCKET_MORA > 0
   AND F.ESTADO_FECHA = 0

INSERT #FECHAS (IDENTIFICADOR_EJECUCION , FECENVIO, CUENTA , BUCKET_MORA, FECVENMOV)
select RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA, max(RI.FECVENMOV) 
  from SAT.PCENVPO1_RI RI
     , #BUCKET_MORA_IC IC
     , SAT.ATINTCAB ATRI
 WHERE RI.IDENTIFICADOR_EJECUCION = ATRI.IDENTIFICADOR_EJECUCION
   AND ATRI.FECENVIO = IC.FECENVIO
   AND RI.CUENTA = IC.CUENTA
   AND DATEPART(MM,RI.FECVENMOV) = DATEPART(MM,DATEADD(SS,-1,DATEADD(MM,-5,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND DATEPART(YY,RI.FECVENMOV) = DATEPART(YY,DATEADD(SS,-1,DATEADD(MM,-5,CONVERT(DATE,CONVERT(VARCHAR,DATEPART(YY,ATRI.FECENVIO)) + '-' + CONVERT(VARCHAR,DATEPART(MM,ATRI.FECENVIO)) + '-01') ) ))
   AND BUCKET_MORA > 0
GROUP BY RI.IDENTIFICADOR_EJECUCION, ATRI.FECENVIO, RI.CUENTA, IC.BUCKET_MORA

-- OBTENER LOS MONTOS EN BASE A LAS FECHAS
UPDATE #FECHAS
   SET MES7 = RI.IMPAPL
     , DATOSMES7 = 1
     , ESTADO_FECHA = 1
  FROM SAT.PCENVPO1_RI RI
     , #FECHAS F
 WHERE RI.IDENTIFICADOR_EJECUCION = F.IDENTIFICADOR_EJECUCION
   AND RI.CUENTA = F.CUENTA
   AND RI.FECVENMOV = F.FECVENMOV
   AND F.BUCKET_MORA >  0
   AND F.ESTADO_FECHA = 0

INSERT #BUCKET_MORA (FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA )
SELECT DISTINCT FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA
  FROM #BUCKET_MORA_IC

--- ACTUALIZACION DE TABLA FINAL
UPDATE #BUCKET_MORA
   SET MONTO_MORAINICIAL = F.MES1
     , MES1 = F.MES1
 FROM #BUCKET_MORA B
    , #FECHAS F
 WHERE F.CUENTA = B.CUENTA
   AND DATOSMES1 = 1

UPDATE #BUCKET_MORA
   SET MORA1 = B.MES1 - F.MES2
     , MES2 = F.MES2
 FROM #BUCKET_MORA B
    , #FECHAS F
 WHERE F.CUENTA = B.CUENTA
   AND DATOSMES2 = 1

UPDATE #BUCKET_MORA
   SET MORA2 = B.MES2 - F.MES3
     , MES3 = F.MES3
 FROM #BUCKET_MORA B
    , #FECHAS F
 WHERE F.CUENTA = B.CUENTA
   AND DATOSMES3 = 1
   
UPDATE #BUCKET_MORA
   SET MORA3 = B.MES3 - F.MES4
     , MES4 = F.MES4
 FROM #BUCKET_MORA B
    , #FECHAS F
 WHERE F.CUENTA = B.CUENTA
   AND DATOSMES4 = 1

UPDATE #BUCKET_MORA
   SET MORA4 = B.MES4 - F.MES5
     , MES5 = F.MES5
 FROM #BUCKET_MORA B
    , #FECHAS F
 WHERE F.CUENTA = B.CUENTA
   AND DATOSMES5 = 1

UPDATE #BUCKET_MORA
   SET MORA5 = B.MES5 - F.MES6
     , MES6 = F.MES6
 FROM #BUCKET_MORA B
    , #FECHAS F
 WHERE F.CUENTA = B.CUENTA
   AND DATOSMES6 = 1

UPDATE #BUCKET_MORA
   SET MORA6 = B.MES6 - F.MES7
     , MES7 = F.MES7
 FROM #BUCKET_MORA B
    , #FECHAS F
 WHERE F.CUENTA = B.CUENTA
   AND DATOSMES7 = 1


IF @OPERACION = 'V'
BEGIN
  SELECT FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA, 
           MONTO_MORAINICIAL, MORA1, MORA2, MORA3,
           MORA4, MORA5, MORA6
    FROM #BUCKET_MORA
END -- 'V'

if @OPERACION = 'G' --- GRABA DATOS EN ESTRUCTURA DE TABLA FIJA.. SI EXISTEN PRIMERO LOS BORRA.. SI LA TABLA NO EXISTE LA CREA..
BEGIN
  DELETE SAT.TB_BUCKET_MORA
   WHERE FECENVIO BETWEEN @FECHA_INI AND @FECHA_FIN 
  INSERT SAT.TB_BUCKET_MORA (FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA, 
           MONTO_MORAINICIAL, MORA1, MORA2, MORA3,
           MORA4, MORA5, MORA6)
  SELECT FECENVIO, IDENTIFICADOR_EJECUCION, CUENTA, DIASMORA, BUCKET_MORA, 
           MONTO_MORAINICIAL, MORA1, MORA2, MORA3,
           MORA4, MORA5, MORA6
    FROM #BUCKET_MORA
END -- OPERACION = 'G'

RETURN 0