IF NOT EXISTS(SELECT 1 FROM "CNF"."CAT_JOBS" WHERE "NOMBRE_JOB" = 'JOB_GENESYS_TLV' AND "NOMBRE_TABLA" = 'BC_CL_TLV')
BEGIN
  INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") VALUES('JOB_GENESYS_TLV','BC_CL_TLV',NULL,0)
END
COMMIT;
