DECLARE 
 @USUARIO VARCHAR(100)
,@PASSWORD VARCHAR(100)
,@PATH VARCHAR(100)
,@SERVER VARCHAR(100)
,@PUERTO VARCHAR(100)

SELECT 
 @USUARIO   = 'usr_sapds'
,@PASSWORD  = 'XXXXXX'
,@PATH      = '/data/SAT/genesys/'
,@SERVER    = 'SVBCWSQL1401DA'
,@PUERTO    = '3341'

IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'U_GEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'U_UGEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('U_GEN',@USUARIO);


IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'P_GEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'P_GEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('P_GEN',@PASSWORD);


IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'PATH_GEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'PATH_GEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('PATH_GEN',@PATH);


IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'SERVER_GEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'SERVER_GEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('SERVER_GEN',@SERVER);


IF EXISTS (SELECT 1 FROM "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'PORT_GEN')
BEGIN
  DELETE "CNF"."PARAMETROS" WHERE "PARAMETRO" = 'PORT_GEN'
END

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('PORT_GEN',@PUERTO);

COMMIT;
