drop table IF EXISTS dbo.BC_CL_TLV;  
CREATE TABLE IF NOT EXISTS dbo.BC_CL_TLV (
	RECORD_ID INTEGER NULL,
	CONTACT_INFO VARCHAR(128) NULL,
	CONTACT_INFO_TYPE INTEGER NULL,
	RECORD_TYPE INTEGER NULL,
	RECORD_STATUS INTEGER NULL,
	CALL_RESULT INTEGER NULL,
	ATTEMPT INTEGER NULL,
	DIAL_SCHED_TIME INTEGER NULL,
	CALL_TIME INTEGER NULL,
	DAILY_FROM INTEGER NULL,
	DAILY_TILL INTEGER NULL,
	TZ_DBID INTEGER NULL,
	CAMPAIGN_ID INTEGER NULL,
	AGENT_ID VARCHAR(32) NULL,
	CHAIN_ID INTEGER NULL,
	CHAIN_N INTEGER NULL,
	GROUP_ID INTEGER NULL,
	APP_ID INTEGER NULL,
	TREATMENTS VARCHAR(255) NULL,
	MEDIA_REF INTEGER NULL,
	EMAIL_SUBJECT VARCHAR(255) NULL,
	EMAIL_TEMPLATE_ID INTEGER NULL,
	SWITCH_ID INTEGER NULL,
	BC_TL_EXFIN_ACC_NBR VARCHAR(25) NULL,
	BC_TL_NOMBRE VARCHAR(50) NULL,
	BC_TL_APELLIDO VARCHAR(50) NULL,
	BC_TL_EXFIN_REL_NBR VARCHAR(25) NULL,
	BC_TL_NIT VARCHAR(25) NULL,
	BC_TL_DATOS_PERSONALES VARCHAR(150) NULL,
	BC_TL_PORTAFOLEACION VARCHAR(150) NULL,
	BC_TL_BALCON VARCHAR(150) NULL,
	BC_TL_TOTAL_TC VARCHAR(150) NULL,
	BC_TL_EMAIL VARCHAR(75) NULL,
	BC_TL_OFERTA1 VARCHAR(150) NULL,
	BC_TL_OFERTA2 VARCHAR(150) NULL,
	BC_TL_OFERTA3 VARCHAR(150) NULL,
	BC_TL_OFERTA4 VARCHAR(150) NULL,
	BC_TL_OFERTA_ADICIONAL VARCHAR(150) NULL,
	BC_TL_ESTRATEGIA VARCHAR(150) NULL,
	BC_TL_FLAG_CCI VARCHAR(5) NULL,
	BC_TL_SERVICIO VARCHAR(30) NULL,
	BC_TL_BASE VARCHAR(25) NULL,
	BC_TL_DISPOSITION2 VARCHAR(40) NULL,
	BC_TL_C1 VARCHAR(25) NULL,
	BC_TL_C2 VARCHAR(25) NULL,
	BC_TL_C3 VARCHAR(25) NULL,
	LOAD_DATE TIMESTAMP NULL;
)
; COMMIT;	 	 		

drop table IF EXISTS STG.BC_CL_TLV;  
CREATE TABLE IF NOT EXISTS STG.BC_CL_TLV (
	RECORD_ID INTEGER NULL,
	CONTACT_INFO VARCHAR(128) NULL,
	CONTACT_INFO_TYPE INTEGER NULL,
	RECORD_TYPE INTEGER NULL,
	RECORD_STATUS INTEGER NULL,
	CALL_RESULT INTEGER NULL,
	ATTEMPT INTEGER NULL,
	DIAL_SCHED_TIME INTEGER NULL,
	CALL_TIME INTEGER NULL,
	DAILY_FROM INTEGER NULL,
	DAILY_TILL INTEGER NULL,
	TZ_DBID INTEGER NULL,
	CAMPAIGN_ID INTEGER NULL,
	AGENT_ID VARCHAR(32) NULL,
	CHAIN_ID INTEGER NULL,
	CHAIN_N INTEGER NULL,
	GROUP_ID INTEGER NULL,
	APP_ID INTEGER NULL,
	TREATMENTS VARCHAR(255) NULL,
	MEDIA_REF INTEGER NULL,
	EMAIL_SUBJECT VARCHAR(255) NULL,
	EMAIL_TEMPLATE_ID INTEGER NULL,
	SWITCH_ID INTEGER NULL,
	BC_TL_EXFIN_ACC_NBR VARCHAR(25) NULL,
	BC_TL_NOMBRE VARCHAR(50) NULL,
	BC_TL_APELLIDO VARCHAR(50) NULL,
	BC_TL_EXFIN_REL_NBR VARCHAR(25) NULL,
	BC_TL_NIT VARCHAR(25) NULL,
	BC_TL_DATOS_PERSONALES VARCHAR(150) NULL,
	BC_TL_PORTAFOLEACION VARCHAR(150) NULL,
	BC_TL_BALCON VARCHAR(150) NULL,
	BC_TL_TOTAL_TC VARCHAR(150) NULL,
	BC_TL_EMAIL VARCHAR(75) NULL,
	BC_TL_OFERTA1 VARCHAR(150) NULL,
	BC_TL_OFERTA2 VARCHAR(150) NULL,
	BC_TL_OFERTA3 VARCHAR(150) NULL,
	BC_TL_OFERTA4 VARCHAR(150) NULL,
	BC_TL_OFERTA_ADICIONAL VARCHAR(150) NULL,
	BC_TL_ESTRATEGIA VARCHAR(150) NULL,
	BC_TL_FLAG_CCI VARCHAR(5) NULL,
	BC_TL_SERVICIO VARCHAR(30) NULL,
	BC_TL_BASE VARCHAR(25) NULL,
	BC_TL_DISPOSITION2 VARCHAR(40) NULL,
	BC_TL_C1 VARCHAR(25) NULL,
	BC_TL_C2 VARCHAR(25) NULL,
	BC_TL_C3 VARCHAR(25) NULL,
	LOAD_DATE TIMESTAMP NULL);
COMMIT;


------------------------------------------------
---- CONTROL DE VERSION ------------------------
------------------------------------------------
create table IF NOT EXISTS CNF.VERSION_OBJETOS (
 NOMBRE_MALLA varchar(100)
,OBJECT_NAME varchar(100)
,OBJECT_USER varchar(20)
,VERSION_COMMIT VARCHAR(100)
,VERSION_CODE VARCHAR(20)
,VERSION_DATE DATETIME
,CRDATE DATETIME null default getdate()
,CRUSER varchar(20) null default user_name()
)
;
COMMIT;

declare 
 @NOMBRE_MALLA varchar(100)
,@OBJECT_NAME varchar(100)
,@OBJECT_USER varchar(20)
,@VERSION_COMMIT VARCHAR(100)
,@VERSION_CODE VARCHAR(20)
,@VERSION_DATE DATETIME 
,@CRDATE DATETIME

select 
 @NOMBRE_MALLA = 'N/A'
,@OBJECT_NAME = 'BC_CL_COB'
,@OBJECT_USER = 'dbo'
,@VERSION_COMMIT = 'f40d80830f4936351b16fca1c74336061c3a6276'
,@VERSION_CODE = 'f40d808'
,@VERSION_DATE = 'July 24, 2019 10:31:27 AM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

select 
 @OBJECT_USER = 'STG'
,@VERSION_COMMIT = '324967d5faf083a1ff1e39ea7b581499d757fcd9'
,@VERSION_CODE = '324967d'
,@VERSION_DATE = 'April 8, 2019 1:52:52 PM'
,@CRDATE = NULL

SELECT @CRDATE = create_time 
FROM SYSUSERS U, SYSTABLE T, SYSIQTABLE S
where T.table_name = @OBJECT_NAME
  and T.creator = U.uid
  and U.name = @OBJECT_USER
  and T.table_id = S.table_id
if @CRDATE IS NULL SELECT @CRDATE = getdate()

IF EXISTS(SELECT 1 from CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE)
  DELETE CNF.VERSION_OBJETOS where OBJECT_NAME = @OBJECT_NAME AND OBJECT_USER = @OBJECT_USER AND VERSION_CODE = @VERSION_CODE
insert CNF.VERSION_OBJETOS (
 NOMBRE_MALLA, OBJECT_NAME ,OBJECT_USER ,VERSION_COMMIT ,VERSION_CODE ,VERSION_DATE ,CRDATE
)
select 
 @NOMBRE_MALLA, @OBJECT_NAME ,@OBJECT_USER ,@VERSION_COMMIT,@VERSION_CODE ,@VERSION_DATE ,@CRDATE 

COMMIT;

