IF EXISTS(SELECT 1 FROM CNF.CAT_JOBS WHERE NOMBRE_JOB = 'JOB_ADM_MOE' AND NOMBRE_TABLA = 'CUS_ADM_MOE')
BEGIN
  DELETE CNF.CAT_JOBS WHERE NOMBRE_JOB = 'JOB_ADM_MOE' AND NOMBRE_TABLA = 'CUS_ADM_MOE'
END
COMMIT;

INSERT INTO "CNF"."CAT_JOBS" ("NOMBRE_JOB","NOMBRE_TABLA","TIPO_CARGA","REPROCESO") 
VALUES('JOB_ADM_MOE','CUS_ADM_MOE',NULL,0);
COMMIT;