IF EXISTS(SELECT 1 FROM CNF.PARAMETROS WHERE PARAMETRO = 'MDE' )
BEGIN
  DELETE CNF.PARAMETROS WHERE PARAMETRO = 'MDE' 
END;
COMMIT;

INSERT INTO "CNF"."PARAMETROS" ("PARAMETRO","VALOR") VALUES('MDE','/data/SAT/mde/');
commit;