DROP TABLE IF EXISTS "STG_SAT"."CUS_ADM_MOE" 
COMMIT;
CREATE TABLE IF NOT EXISTS "STG_SAT"."CUS_ADM_MOE"(
	"name" VARCHAR(1024) NULL ,
	"name_1" VARCHAR(1024) NULL ,
	"id" VARCHAR(1024) NULL ,
	"v" VARCHAR(1024) NULL ,
	"DI_FILENAME" VARCHAR(100) 
);
COMMIT;


