--- creacion de grupo de usuarios SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'SAT')
BEGIN
CREATE USER SAT 
FORCE PASSWORD CHANGE OFF;
END;
COMMIT;
--- creacion de grupo de usuarios STG_SAT
IF NOT EXISTS (SELECT 1 FROM DBO.SYSUSERS WHERE name = 'STG_SAT')
BEGIN
CREATE USER STG_SAT
FORCE PASSWORD CHANGE OFF;
END;
COMMIT;

------------------------------
-- INTERFAZ  TARJETAS PROXIMAS A VENCER
--------------------------------
-- TABLA ATINTVTO

drop table IF EXISTS SAT.ATINTVTO;  
CREATE TABLE IF NOT EXISTS SAT.ATINTVTO  (
 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CODMAR	DECIMAL	(2,0)	--CODIGO MARCA DE TARJETA
,	INDTIPT	DECIMAL	(2,0)	--INDICADOR DE TIPO DE TARJETA
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA DEL CONTRATO
,	CUENTA	VARCHAR	(12)	--CUENTA DE CONTRATO
,	CALPART	VARCHAR	(2)	--CALIDA DE PARTICIPACION
,	IDENTCLI	VARCHAR	(8)	--IDENTIFICADOR DE CLIENTE
,	TIPBON	VARCHAR	(6)	--TIPO DE BONIFICACION
,	PAN	VARCHAR	(22)	--NUMERO DE LA TARJETA
,	FECALTA	DATE		--FECHA DE ALTA DE LA TARJETA
,	FECCADTAR	DECIMAL	(6,0)	--FECHA DE CADUCIDAD DE LA TARJETA (AAAAMM)
,	CODBLQ	DECIMAL	(2,0)	--CODIGO DE BLOQUEO
); COMMIT;	 
	 		
DROP TABLE IF EXISTS "DWH_ETLS"."ATINTVTO";
COMMIT;
DROP TABLE IF EXISTS "STG"."ATINTVTO";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."ATINTVTO";
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."ATINTVTO" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CODMAR" DECIMAL(2,0) NULL ,
	"INDTIPT" DECIMAL(2,0) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"CALPART" VARCHAR(2) NULL ,
	"IDENTCLI" VARCHAR(8) NULL ,
	"TIPBON" VARCHAR(6) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"FECALTA" VARCHAR(10) NULL ,
	"FECCADTAR" DECIMAL(6,0) NULL ,
	"CODBLQ" DECIMAL(2,0) NULL 
)  COMMIT;

