DROP TABLE IF EXISTS "DWH_ETLS"."ATINTVTO";
COMMIT;
DROP TABLE IF EXISTS "STG"."ATINTVTO";
COMMIT;
DROP TABLE IF EXISTS "STG_SAT"."ATINTVTO";
COMMIT;

CREATE TABLE IF NOT EXISTS "STG_SAT"."ATINTVTO" (
	"CODENT_D" VARCHAR(4) NULL ,
	"NSECFIC_D" DECIMAL(10,0) NULL ,
	"TIPOCINTA_D" DECIMAL(2,0) NULL ,
	"TIPOREG_D" VARCHAR(1) NULL ,
	"FILLER_D" VARCHAR(91) NULL ,
	"NUMREGPROC" DECIMAL(12,0) NULL ,
	"CODENT" VARCHAR(4) NULL ,
	"CODMAR" DECIMAL(2,0) NULL ,
	"INDTIPT" DECIMAL(2,0) NULL ,
	"CENTALTA" VARCHAR(4) NULL ,
	"CUENTA" VARCHAR(12) NULL ,
	"CALPART" VARCHAR(2) NULL ,
	"IDENTCLI" VARCHAR(8) NULL ,
	"TIPBON" VARCHAR(6) NULL ,
	"PAN" VARCHAR(22) NULL ,
	"FECALTA" VARCHAR(10) NULL ,
	"FECCADTAR" DECIMAL(6,0) NULL ,
	"CODBLQ" DECIMAL(2,0) NULL 
)  COMMIT;

