drop table IF EXISTS SAT.ATINTVTO;  
CREATE TABLE IF NOT EXISTS SAT.ATINTVTO  (
 	IDENTIFICADOR_EJECUCION	INTEGER		--IDENTIFICADOR UNICO DE EJECUCION
,	CODENT_D	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	NSECFIC_D	DECIMAL	(10,0)	--NUMERO DE SECUENCIA DE LA CINTA
,	TIPOCINTA_D	DECIMAL	(2,0)	--TIPO DE LA CINTA
,	TIPOREG_D	VARCHAR	(1)	--TIPO DE REGISTRO D = DETALLE 
,	FILLER_D	VARCHAR	(91)	--FILLER
,	NUMREGPROC	DECIMAL	(12,0)	--NUMERO DE REGISTRO PROCESADO
,	CODENT	VARCHAR	(4)	--CODIGO DE ENTIDAD
,	CODMAR	DECIMAL	(2,0)	--CODIGO MARCA DE TARJETA
,	INDTIPT	DECIMAL	(2,0)	--INDICADOR DE TIPO DE TARJETA
,	CENTALTA	VARCHAR	(4)	--CENTRO DE ALTA DEL CONTRATO
,	CUENTA	VARCHAR	(12)	--CUENTA DE CONTRATO
,	CALPART	VARCHAR	(2)	--CALIDA DE PARTICIPACION
,	IDENTCLI	VARCHAR	(8)	--IDENTIFICADOR DE CLIENTE
,	TIPBON	VARCHAR	(6)	--TIPO DE BONIFICACION
,	PAN	VARCHAR	(22)	--NUMERO DE LA TARJETA
,	FECALTA	DATE		--FECHA DE ALTA DE LA TARJETA
,	FECCADTAR	DECIMAL	(6,0)	--FECHA DE CADUCIDAD DE LA TARJETA (AAAAMM)
,	CODBLQ	DECIMAL	(2,0)	--CODIGO DE BLOQUEO
); COMMIT;	 	 		
